- src/api/BaseUpload.js
- src/api/Chunk.js
- src/api/ChunkedUpload.js
- src/api/PlainUpload.js
- src/components/ContentUploader/ContentUploader.js
- src/components/ContentUploader/Footer.js
- src/constants.js
- Consolidate upload error & retry logic for plain and chunked uploads
- Add exponential back-off for non-429 retries
- Properly handle 429 retries based on the `Retry-After` header
> Fix: Better error and retry handling for Uploader

- src/api/Chunk.js
- src/api/ChunkedUpload.js
- src/components/ContentUploader/ContentUploader.js
- src/wrappers/ContentUploader.js
- test/uploader.html
- Add 'upload' and 'error' events that are emitted when single files are either uploaded successfully or not
- When uploads fail, show an error indicator per row instead of cancelling all uploads
- Allow retries of failed uploads
> New: Upload & error events per file and manual retries

- package.json
- src/api/Base.js
- src/api/uploads/BaseMultiput.js
- src/api/uploads/MultiputPart.js
- src/api/uploads/MultiputUpload.js
- src/api/uploads/__tests__/BaseMultiput-test.js
- src/api/uploads/__tests__/MultiputPart-test.js
- src/api/uploads/__tests__/MultiputUpload-test.js
- src/flowTypes.js
- src/util/uploads.js
- src/util/url.js
- src/util/webcrypto.js
- yarn.lock
- create session (initiation, error, success, retry)
- upload part (initiation, error, success, retry, progress)
> New: MultiputUpload part2

- package.json
core-js is already imported in the enzyme adaptor
> Chore: Remove unnecessary inclusion of babel-polyfill

- src/api/uploads/UploadReachability.js
- src/api/uploads/__tests__/UploadsReachability-test.js
On the staging environment when uploading from the webapp, the preflight returns 204 with no upload_url. Also, this API behavior is undocumented.
Adding an extra check to handle this case.
> Fix: upload reachability test should accept empty preflight response

- README.md
- src/components/ContentExplorer/ContentExplorer.js
- src/components/ContentPicker/ContentPicker.js
- src/components/ContentPreview/ContentPreview.js
- src/components/ContentSidebar/ContentSidebar.js
- src/components/ContentTree/ContentTree.js
- src/components/ContentUploader/ContentUploader.js
- src/wrappers/ES6Wrapper.js
And remove it from the wrapper, so that developers are not forced
to import it themselves other than adding peer dep.
> Update: Import regnerator runtime as part of React components

- README.md
- src/components/ContentExplorer/ContentExplorer.js
- src/components/ContentExplorer/PreviewDialog.js
- src/components/ContentPicker/ContentPicker.js
- src/components/ContentPreview/ContentPreview.js
- src/components/ContentSidebar/ContentSidebar.js
- src/components/ContentTree/ContentTree.js
- src/components/ContentUploader/ContentUploader.js
- src/components/UploadDialog/UploadDialog.js
- src/flowTypes.js
- src/util/Xhr.js
- test/explorer-no-react.html
- test/preview.html
Adds interceptors for adding custom headers and/or query params to the request OR filtering the response data. Prior prop `responseFilter` renamed to `responseInterceptor` for consistency. Uses the format as shown here https://github.com/axios/axios#interceptors except that the `config` attribute will additionally have a `parsedUrl` object that breaks the API url into its fragments to help with filtering. See syntax below and working example [here](test/explorer-no-react.html).
```js
explorer.show(ID, TOKEN, {
...
requestInterceptor: (config) => {
// Do something with config per https://github.com/axios/axios#interceptors
return config;
},
responseInterceptor: (response) => {
// Do something with response.data per https://github.com/axios/axios#interceptors
return response;
}
});
```
> Breaking: Add request and response intercepting to the elements

- src/api/Item.js
- src/api/__tests__/Item-test.js
Also refactors Cache.js to create a new object as opposed to editing attributes on the existing object.
> Chore: Refactor merge to return the merged item

- package.json
- src/components/Breadcrumbs/BreadcrumbDropdown.js
- src/components/Breadcrumbs/Breadcrumbs.js
- src/components/Breadcrumbs/InlineBreadcrumbs.js
- src/components/ContentExplorer/ContentExplorer.js
- src/components/ContentExplorer/ItemList.js
- src/components/ContentExplorer/moreOptionsCellRenderer.js
- src/components/ContentPicker/ContentPicker.js
- src/components/ContentPicker/ItemList.js
- src/components/ContentUploader/ContentUploader.js
- src/components/ContentUploader/DroppableContent.js
- src/components/ContentUploader/ItemAction.js
- src/components/ContentUploader/ItemList.js
- src/components/ContentUploader/UploadsManager.js
- src/components/ContentUploader/actionCellRenderer.js
- src/components/Item/ItemDetails.js
- src/components/Item/nameCellRenderer.js
- src/components/SubHeader/Add.js
- src/components/SubHeader/Sort.js
- src/components/SubHeader/SubHeader.js
- src/components/SubHeader/SubHeaderLeft.js
- src/components/SubHeader/SubHeaderRight.js
- src/components/base.scss
- test/preview.html
- yarn.lock
Previously they used to render into the UI Element's container element. This has been causing issues when the UI Element was rendered in some 3rd party library modal (#183) due to stacking context issues (absolute/fixed positioning) and compatibility with tether.js positioning via bodyElement.
This change removes use of bodyElement making tether render the popups directly into the document body. While this breaks a bit of encapsulation, at least now tether should be able to position them better.
However the tooltip or dropdown menu can be hidden due to z-index issues. In that case, the parent app, folks using the UI Element, need to override and add z-index based on their app's use case. 
Classes to add z-index to would be `dropdown-menu-element` and `tooltip-element`. And z-index only …
> Breaking: Render dropdowns and tooltips popups into body

- src/components/ContentExplorer/PreviewDialog.js
- src/components/ContentPreview/ContentPreview.js
- test/explorer-no-react.html
- test/pickers-no-react.html
- test/preview.html
- test/uploader-no-react.html
So that the preview is not focusing itself and making the parent page jump. Auto focus helps with keyboard shortcuts. Autofocus is set to true when using content explorer.
Fixes typo in options to prevent preview library attach its own hotkey handlers.
Also fixes references to React 16 in test files. UI Elements aren't compatible with React 15.
> Fix: Only focus preview when auto focus is allowed

- package.json
- src/components/ContentSidebar/__tests__/__snapshots__/SidebarAccessStats-test.js.snap
- src/components/ContentSidebar/__tests__/__snapshots__/SidebarVersions-test.js.snap
- yarn.lock
Snapshots were not being serialized correctly, thus we were getting massive unreadable snapshots. This fixes the serialization and adds correct snapshots
> Chore: use enzyme-to-json to serialize snapshots

- README.md
The `ContentTree` was a prototype and we aren't actively maintaining it. Removing documentation as a first step.
> Docs: Remove Content Tree documentation

- src/api/Base.js
- src/api/Comments.js
- src/api/Tasks.js
- src/api/__tests__/Tasks-test.js
Note that adding an assignee or list of assignees can only be done through the /task_assignment endpoint, so this only allows the creation, update, and deletion of task messages and due dates. Assignment stuff will come in the next PR.
> Chore: Adding task CRUD operations 

- src/components/ContentExplorer/ContentExplorer.js
this prevents a debounced call from being executed after our query is cleared, when someone deletes the string quickly.
> Fix: Cancel debounced search when query is deleted

- src/components/ContentSidebar/ActivityFeed/activity-feed/ActivityFeed.js
- src/components/ContentSidebar/ActivityFeed/activity-feed/__tests__/ActivityFeed-test.js
This handles behavior for: create comment/task, delete comment/task, edit task.
Notifications to the user will come in a separate PR. We will also have to handle task resolution once the success cases are handled.
> Fix: correct error handling responses for activity feed actions

- src/components/ContentSidebar/ActivityFeed/approval-comment-form/ApprovalCommentForm.js
- src/components/ContentSidebar/ActivityFeed/approval-comment-form/__tests__/ApprovalCommentForm-test.js
We actually need it to properly set pending UI on task create
> Fix: Pass full approvers object on task create

- i18n/en-US.properties
- src/api/uploads/FolderUpload.js
- src/api/uploads/FolderUploadNode.js
- src/api/uploads/__tests__/FolderUpload-test.js
- src/api/uploads/__tests__/FolderUploadNode-test.js
- src/components/ContentUploader/ContentUploader.js
- src/components/ContentUploader/OverallUploadsProgressBar.js
- src/components/ContentUploader/UploadsManager.js
- src/components/ContentUploader/__tests__/OverallUploadsProgressBar-test.js
- src/components/ContentUploader/__tests__/__snapshots__/OverallUploadsProgressBar-test.js.snap
- src/components/messages.js
- src/util/__tests__/uploads-test.js
- src/util/uploads.js
- test/uploader-window-view.html
- adds an `isUploadsManagerVisible` prop to the `ContentUploader` to allow the UploadsManager to be shown when there's no ongoing uploads
- adds an empty state to the UploadsManager which instructs user to drop file to upload
> New: UploadsManager drag and drop upload empty state

- src/components/base.scss
Allows for buttons (info button and trash/pencil) to have browser highlight, meeting webapp parity for accessibility
> Chore: Allow buttons to have outline on focus

- src/components/ContentUploader/ContentUploader.js
- src/components/ContentUploader/OverallUploadsProgressBar.js
- src/components/ContentUploader/UploadsManager.js
- src/components/ContentUploader/__tests__/OverallUploadsProgressBar-test.js
- src/components/ContentUploader/__tests__/__snapshots__/OverallUploadsProgressBar-test.js.snap
- Drag and drop prompt should be shown when UploadsManager is invisible or is dragging files
> Fix: UploadsManager should show correct message

- src/components/ContentSidebar/SidebarNavButton.js
- src/components/ContentSidebar/SidebarNavButton.scss
- src/components/ContentSidebar/__tests__/__snapshots__/SidebarNavButton-test.js.snap
The Tooltip component applies `tabindex=0` to its immediate child, which causes two focus events per button upon keyboard navigation. I've eliminated the wrapper between Tooltip and PlainButton to avoid the issue.
> Fix: Support keyboard navigation between sidebar tabs

- src/components/ContentSidebar/ActivityFeed/approval-comment-form/ApprovalCommentForm.scss
- This causes the @mentions dialog to hide. We only want to hide the overflow inside the draftjs placeholders
> Fix: Don't hide CSS overflow w/in .bcs-comment-input

- src/components/ContentSidebar/ActivityFeed/comment/Comment.scss
Doesn't look like `display: inline-block` makes a difference in any browser. Images below are with it removed.
Chrome:
IE 11:
Safari:
Firefox:
> Chore: removed display style from bcs-comment-mention

- src/components/ContentSidebar/SidebarContent.scss
Now matching font-weight of sidebar header titles in Webapp
> Fix: Match font-weight of header titles in sidebar

- .babelrc
- examples/src/ContentSidebar/ContentSidebarExample.scss
- flow-typed/box-ui-elements.js
- src/api/Feed.js
- src/api/File.js
- src/api/Folder.js
- src/api/Recents.js
- src/api/Search.js
- src/api/__tests__/File-test.js
- src/api/__tests__/Folder-test.js
- src/api/__tests__/Recents-test.js
- src/api/__tests__/Search-test.js
- src/components/ContentExplorer/ContentExplorer.js
- src/components/ContentExplorer/__tests__/ContentExplorer-test.js
- src/components/ContentPicker/ContentPicker.js
- src/components/ContentPicker/__tests__/ContentPicker-test.js
- src/components/ContentPreview/ContentPreview.js
- src/components/ContentPreview/__tests__/ContentPreview-test.js
- src/components/ContentSidebar/ContentSidebar.js
- src/components/ContentSidebar/__tests__/ContentSidebar-test.js
- src/components/ContentTree/ContentTree.js
- src/util/Cache.js
- src/util/__tests__/fields-test.js
- src/util/fields.js
- src/wrappers/ContentExplorer.js
- src/wrappers/ContentPicker.js
- test/preview.html
Fetching file details are now isolated between explorer/picker, preview and sidebar.
The file API will fetch file fields that are missing from the cached file object.
eg:
If explorer wants { a, b } => it will request for a and b
If preview wants { a, b, c } => it will request for b and c using cache from explorer if available
If sidebar wants { b, c, d } => it will request for d using cache from preview if available
Also changes babelrc to have presets per environment so that we target latest chrome and firefox only for dev builds which makes testing easier. It will not need babel transform to use generators as such break points will work for debugging. Only will work in dev mode.
**TODO: Fix broken tests / add more tests**
> Update: Improve file fetch isolation across elements

- flow/DraftJSFlowStub.js.flow
- src/components/ContentSidebar/ActivityFeed/approval-comment-form/ApprovalCommentForm.js
If there currently exists a `tagged_message`, don't show the placeholder message in the `DraftJSMentionSelector`, but instead initialize the `EditorState` with the message instead of an empty state.
> Update: Edit task message

- i18n/en-US.properties
- src/components/ContentSidebar/__tests__/__snapshots__/MetadataSidebar-test.js.snap
- src/components/ContentUploader/__tests__/__snapshots__/UploadState-test.js.snap
- src/components/messages.js
What this PR does:
Changes a typo in the messages key from occured to => occurred
> Chore: fix occurred typos in messages

- src/components/ContentOpenWith/ContentOpenWith.js
Fixes the codepen case where we are operating in a sandboxed iframe. Setting the URL first allows the redirect to happen, although chrome still throws errors.
> Fix: Fix sandboxed iframe case for GET integrations

- .eslintignore
Fixes eslint hanging when this folder is present
> Chore: add styleguide to .eslintignore

- src/api/uploads/MultiputUpload.js
If MultiputUpload is used as Upload Embed Widget, the format of the response data of xhr is different. Instead of having "entries" as an attribute in "data", "data" itself is entries[0].
> Fix: Update MultiputUpload successHandler to parse the response

- build/prod.js
Based on the conversation with @wenboyu2 this should prevent some of the memory related issues we are seeing on Jenkins.
> Chore: Decrease parallelization in production job

- src/api/Metadata.js
- src/api/__tests__/Metadata-test.js
- src/components/ContentSidebar/ContentSidebar.js
- src/components/ContentSidebar/MetadataSidebar.js
- src/components/ContentSidebar/Sidebar.js
- src/components/ContentSidebar/SidebarUtils.js
- src/components/ContentSidebar/__tests__/ContentSidebar-test.js
- src/components/ContentSidebar/__tests__/SidebarUtils-test.js
- Remove classification and non-properties global templates from being able to be added via drop down
- Don't show sidebar if feature is disabled and no metadata to show
- Show sidebar even when feature is disabled but there is metadata to show
> Fix: Metadata sidebar fixes

- src/components/ContentUploader/ContentUploader.js
- src/components/ContentUploader/__tests__/ContentUploader-test.js
fixes #685
Removed setting of isUploadsManagerExpanded to existing state in updateViewAndCollection.  Also added isAutoExpanded flag to ContentUploader to keep track of auto-expansion to close when all uploads have completed.
> fix(uploader): autoexpand when uploading more than 5 files

- src/components/ContentSidebar/ActivityFeed/approval-comment-form/ApprovalCommentForm.js
- src/components/ContentSidebar/ActivityFeed/approval-comment-form/__tests__/ApprovalCommentForm-test.js
The date can come in as null, and thus the date never gets reset from the previously set date.
> fix(sidebar): allow approval date to be reset

- .prettierignore
- README.md
- src/components/ContentUploader/ContentUploader.js
- src/components/ContentUploader/__tests__/ContentUploader-test.js
- src/wrappers/ContentUploader.js
UEW -> Upload Embed Widget for Webapp.
onStage is the new event that gets introduced for the purposes of the UEW.
The general idea is that the way the new v2 Upload Widget wasn't properly set up for handling drag and dropping files into the UEW.
If a user did drag and drop, it was querying the ItemList React Virtualized Column to render the items name.
However for the v2 UEW it was requested that the item size would also be included in the rendered item info.
And the item list didn't have a column for item size, and it would be best if we passed a file object back to the UEW. (Props to jpress for the suggestion!)
Therefore this onStage event was introduced, The idea being that if a user drags or drops an item into the Upload embed widget it then emits an event that can be intercepted by …
> fix(uploader): add new event for upload widget

- src/components/ContentUploader/ContentUploader.js
- src/components/ContentUploader/__tests__/ContentUploader-test.js
There is currently a bug with the uploader that when cancel is hit, the itemIds are not reset when updateViewAndCollection is called. 
The problem being if a user hits cancel, and then tries to upload the same file, because the itemId already exists in state, it will deny the upload.
This PR checks to see if the argument passed to updateViewAndCollection if is an empty arr, if it is it resets the itemIds when it resets state.
> fix(uploader): reset state when items are empty

- src/components/ContentOpenWith/IconFileMap.js
the platform version of the gsuite integrations will be considered "beta" for now. This change will allow the correct icons to be used during and after this beta period.
> feat(openwith): Add support for 'beta' google integrations

- src/api/Metadata.js
- src/api/__tests__/Metadata-test.js
Even though the API request limit is 1000, the template hard limit is 500 while the instance hard limit is 100. Which means you can only have 500 enterprise templates and only 100 of the overall (ent+global) templates can be applied to a file or folder.
> fix(metadata): increase template fetch limit to 1000 max limit

- src/components/ContentSidebar/ContentSidebar.js
- src/components/ContentSidebar/Sidebar.js
- src/components/ContentSidebar/__tests__/ContentSidebar-test.js
- src/components/ContentSidebar/__tests__/Sidebar-test.js
- src/components/ContentSidebar/__tests__/__snapshots__/Sidebar-test.js.snap
Introduce `isOpen` state in sidebar in order to persist toggle state when navigating across different files
> fix(sidebar): Maintain toggle state across file navigation

- flow-typed/box-ui-elements.js
- src/components/ContentOpenWith/ContentOpenWith.js
- src/components/ContentOpenWith/OpenWithDropdownMenu.js
- src/components/ContentOpenWith/__tests__/__snapshots__/ContentOpenWith-test.js.snap
- test/openwith.html
Exposing a BRUI prop in Dropdown to avoid the problem of rendering the open with button near the left edge of the screen:
With `isRightAligned` set to `false`.
> feat(openwith): Expose dropdown alignment prop

- src/api/uploads/MultiputPart.js
The `uploadErrorHandler` would frequently attempt to check properties on an undefined XHR object leading an exception and the part not being properly retried. This PR fixes that.
> fix(uploader): ContentUploader did not properly handle multiput errors

- src/utils/__tests__/LocalStore-test.js
It looks like the latest versions of Jest have some issues with reassigning global/window methods. I've added a workaround for now that seems to work correctly in both node 8 and node 10.
> chore: Fix localStore unit test to work with node 8

- .npmignore
- .nvmrc
- .travis.yml
- package.json
BREAKING: makes min required node version to build
> build: make node 10 min version

- examples/src/features.js
- i18n/en-US.properties
- src/elements/common/messages.js
- src/elements/content-sidebar/ActivitySidebar.js
- src/elements/content-sidebar/AddTaskButton.js
- src/elements/content-sidebar/ContentSidebar.js
- src/elements/content-sidebar/__tests__/__snapshots__/ActivitySidebar-test.js.snap
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.js
- src/elements/content-sidebar/activity-feed/activity-feed/__tests__/__snapshots__/ActivityFeed-test.js.snap
- src/elements/content-sidebar/activity-feed/task-form/TaskForm.js
- src/elements/content-sidebar/activity-feed/task-form/TaskForm.scss
- src/elements/content-sidebar/activity-feed/task-form/__tests__/TaskForm-test.js
- src/elements/content-sidebar/activity-feed/task-form/index.js
- src/elements/content-sidebar/activity-feed/task/Task.js
- src/elements/content-sidebar/activity-feed/task/__tests__/__snapshots__/Task-test.js.snap
- test/integration/content-sidebar/TaskForm.e2e.test.js
- test/sidebar.html
> feat(tasks): Add "add task" button and modal in Activity Sidebar

- jsconfig.json
https://code.visualstudio.com/docs/languages/jsconfig#_best-practices
Intellisense is currently disabled because the TS server detects too many files with the new settings
> chore(ide): fix vscode intellisense

- package.json
- yarn.lock
Resolves an issue with Cypress and Chrome 72+ where the `cy.visit` command doesn’t work properly in some cases.
https://docs.cypress.io/guides/references/changelog.html#3-1-5
> chore(tests): Upgrade Cypress to resolve issues with Chrome 72+

- CONTRIBUTING.md
- DEVELOPING.md
- README.md
- babel.config.js
- package.json
- yarn.lock
BREAKING CHANGE: The babel compiled output will now include SCSS imports. This commit removes the `babel-plugin-transform-require-ignore` which was responsible for removing lines such as `import './ContentPreview.scss'` from the babel compiled version of `ContentPreview.js`. This forced customers to manually include styles via `import 'box-ui-elements/dist/preview.css'`. With this change, the babel compiled output will now include `import './ContentPreview.scss'` and no manual import of `preview.css` will be required. This change however requires that [webpack is configured properly](https://github.com/box/box-ui-elements#stylesheets) to handle `.scss` files. As a customer, you will notice the change as shown below:
**Before**
-----------
Notice the import of `preview.css`.
```jsx
import …
```
> build: include scss imports within babel compiled output

- src/elements/content-sidebar/activity-feed/comment/Comment.js
- src/elements/content-sidebar/activity-feed/comment/Comment.scss
- src/elements/content-sidebar/activity-feed/comment/__tests__/__snapshots__/Comment-test.js.snap
- this moves the timestamp to its own line following latest design
- cleans up conditional with explicit booleans
> feat(tasks): new comment layout

- conf/cut_release.sh
- examples/gitignore
gh-pages branch does not need anything except the `build` folder, the `index.html` and `main.css` files. Github has a problem parsing `{{ }}` from React within .md files that results in errors like
```
The variable `{{ retentionPolicyDescription: 'Retention', policyType: 'finite', openModal: () => { alert('Retention Modal'); }` on line 51 in `src/features/item-details/ItemProperties.md` was not properly closed with `}}`.
```
> build(examples): add gitignore for gh-pages branch

- src/elements/content-uploader/ContentUploader.js
- src/elements/content-uploader/__tests__/ContentUploader-test.js
What this PR Does: 
We shouldn't ideally set state by mutating it directly. One should typically call setState, in order to do state changes. 
this PR simply refactors the anti pattern and uses setState to not cause unnecessary side effects.
> fix(uploader): refactor anti pattern in addFilesToUploadQueue

- .eslintignore
- .flowconfig
- .npmignore
- babel.config.js
- conf/cut_release.sh
- flow-typed/box-ui-elements.js
- flow-typed/npm/react-intl_v2.x.x.js
- src/elements/content-sidebar/ContentSidebar.js
- src/elements/content-sidebar/activity-feed/task-form/TaskForm.js
- src/elements/content-sidebar/activity-feed/version/Version.js
- src/utils/Xhr.js
* Includes global flow types inside the npm package so that parent projects can reference it.
* Also fixes references and eslint issues within the global flow types file.
* Restricts react-intl message extractor plugin to npm (used in prepush and release scripts) builds only so that the properties file is generated based on all JS modules and not just those that are referenced. NPM build touches all JS modules and such suffices to extract any and every message.
* Changes release script to build assets and locales before running semantic release to detect any potential missing locales.
> build: include global flow types, disable react-intl for dev

- src/elements/content-sidebar/activity-feed/comment/UserLink.js
This only affects at mentions that don't have a corresponding link.
Before:
After:
> fix(sidebar): At mentions with no link should render inline

- i18n/en-US.properties
- src/features/unified-share-modal/UnifiedShareModal.scss
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkSection-test.js.snap
- src/features/unified-share-modal/messages.js
Changes in this PR include: 
- Update `linkShareOn` and `linkShareOff` strings for shared link toggle in unified share modal. 
- Add CSS to show pointer cursor on shared link toggle label.
>  chore(unified-share-modal): Update shared link call to action strings

- src/components/pill-selector-dropdown/PillSelector.js
- src/components/pill-selector-dropdown/SuggestedPillsRow.js
- src/components/pill-selector-dropdown/__tests__/SuggestedPillRow-test.js
- src/components/pill-selector-dropdown/__tests__/__snapshots__/PillSelector-test.js.snap
Problem: this was build under the assumption that all pills contained an "id" value, which is not true. All pill do have a "value". Value is typically either an "id" or an "email" so we can filter the list of suggested pills by both.
> fix(pill-selector-dropdown): update suggested pills filter

- src/features/query-bar/__tests__/Condition-test.js
- src/features/query-bar/__tests__/FilterButton-test.js
- src/features/query-bar/__tests__/ValueField-test.js
- src/features/query-bar/__tests__/__snapshots__/ColumnButton-test.js.snap
- src/features/query-bar/__tests__/__snapshots__/ColumnButtonOverlay-test.js.snap
- src/features/query-bar/__tests__/__snapshots__/Condition-test.js.snap
- src/features/query-bar/__tests__/__snapshots__/ValueField-test.js.snap
- src/features/query-bar/components/filter/Condition.js
- src/features/query-bar/components/filter/FilterButton.js
- src/features/query-bar/components/filter/ValueField.js
- src/features/query-bar/components/fixtures.js
- src/features/query-bar/constants.js
- src/features/query-bar/flowTypes.js
- src/features/query-bar/styles/Condition.scss
- Update Condition flowtype `value` and `operator` property to be `Array<string>` instead of `string`
- Use `MultiSelectField` in ValueField.js
- Add multi-enum object into columns array in `fixtures.js` for use in the styleguide
- Cleaned up `fixtures.js` by moving copy/pasted column objects to a constant and share that with other constants
- Update Condition.scss to include error state for MultiSelectField
- Handle handler logic when deleting a date from the DatePicker, ran into a bug earlier where there was an error that said `cannot toString null`
> feat(query-bar): Implement multi enum in filter button

- conf/cut_release.sh
So that gh-pages branch isn't getting prior committed files
> build(examples): remove cached files that are git ignored

- .flowconfig
First, in version 0.57 of Flow, [the feature](https://github.com/facebook/flow/releases/tag/v0.57.1) as described below added
New Features:
Flow will now only check the files in node_modules/ which are direct or transitive dependencies of the non-node_modules code.
Also, [the document ](https://flow.org/en/docs/config/options/#toc-module-system-node-resolve-dirname-string)explains about setting module.system.node.resolve_dirname as below.
module.system.node.resolve_dirname (string)
By default, Flow will look in directories named node_modules for node modules. You can configure this behavior with this option.
from https://github.com/facebook/flow/issues/5180#issuecomment-341887514
> fix(flow): type issues

- i18n/en-US.properties
- src/features/shared-link-settings-modal/SharedLinkSettingsModal.js
- src/features/shared-link-settings-modal/SharedLinkSettingsModal.scss
- src/features/shared-link-settings-modal/VanityNameSection.js
- src/features/shared-link-settings-modal/__tests__/VanityNameSection-test.js
- src/features/shared-link-settings-modal/messages.js
- src/icons/badges/QuarantineBadge.js
- src/utils/__tests__/datetime-test.js
update the design so that vanity URLs display is consistent with other fields, and offers a content privacy disclosure when requested
> fix(link-settings): Use checkbox to check and load/reset vanity URLs

- i18n/en-US.properties
- src/elements/common/messages.js
- src/elements/content-uploader/progressCellRenderer.js
- Add error case for uploading a file with a name that already exists
> feat(upload-manager): Add error case to upload manager name conflict

- conf/webpack.config.js
We’ll need to look into re-enabling the option if we decide to support deep linking in the future, likely via an environment flag of some kind. It's not needed right now, though.
> build(webpack): Remove devServer option interfering with yarn start:dev

- src/components/avatar/Avatar.js
- src/components/avatar/Avatar.scss
- src/components/avatar/__tests__/Avatar-test.js
- src/elements/content-sidebar/activity-feed/__tests__/__snapshots__/Avatar-test.js.snap
- src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/Task-test.js.snap
Adds a size prop (currently restricted to "large") for avatars. The default CSS matches the design for the components using HeaderFlyout (44px width, 14px font size).
> feat(avatar): add size prop to avatars

- i18n/en-US.properties
- src/features/query-bar/__tests__/__snapshots__/ValueField-test.js.snap
- src/features/query-bar/components/filter/Condition.js
- src/features/query-bar/components/filter/ValueField.js
- src/features/query-bar/constants.js
- src/features/query-bar/messages.js
- `TextInput` fields now have an error tooltip that says `Please enter a value`
- Use constants instead of hardcoded strings in Condition.js and ValueField.js
- Fix UI issue with single select enum where the placeholder isn't shown when empty string is passed in
> fix(query-bar): fix tooltip text for Condition

- src/features/query-bar/QueryBar.js
- src/features/query-bar/__tests__/FilterButton-test.js
- src/features/query-bar/components/filter/FilterButton.js
- FilterButton now accepts ```conditions``` prop passed down from EUA
- FilterButton's original state called ```conditions``` is now called ```transientConditions```
- Upon closing the FilterButton dropdown, ```this.state.transientConditions``` will get set to an empty Array
- Upon any changes between ```this.props.condition``` in FilterButton and ```this.state.transientConditions```, ```componentDidUpdate``` will handle hydrating local state with Redux state
> chore(query-bar): Reference conditions from parent app

- examples/src/MetadataViewQueryBarExamples.js
- src/components/avatar/Avatar.js
- Pass conditions into styleguide for Query Bar
- Default size to be empty string for Avatar.js
- Resolves two flow errors currently being shown in the console
> chore(query-bar): pass conditions into styleguide

- src/features/unified-share-modal/EmailForm.js
- src/features/unified-share-modal/UnifiedShareModal.scss
- src/features/unified-share-modal/__tests__/__snapshots__/EmailForm-test.js.snap
Reverting back to original sizes because the extra height is no longer necessary. This will also help USM to better support smaller screen sizes.
> fix(unified-share-modal): reduce default text box height

- src/components/tooltip/Tooltip.js
- src/components/tooltip/__tests__/Tooltip-test.js
- src/features/unified-share-modal/EmailForm.js
- src/features/unified-share-modal/SharedLinkAccessMenu.js
- src/features/unified-share-modal/SharedLinkSection.js
- src/features/unified-share-modal/UnifiedShareModal.js
- src/features/unified-share-modal/__tests__/SharedLinkAccessMenu-test.js
- src/features/unified-share-modal/__tests__/SharedLinkSection-test.js
- src/features/unified-share-modal/__tests__/__snapshots__/EmailForm-test.js.snap
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkAccessMenu-test.js.snap
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkSection-test.js.snap
- src/features/unified-share-modal/__tests__/__snapshots__/UnifiedShareModal-test.js.snap
- src/features/unified-share-modal/flowTypes.js
> feat(unified-share-modal): add contextual callout tooltips

- src/features/query-bar/__tests__/__snapshots__/FilterButton-test.js.snap
- src/features/query-bar/components/filter/FilterButton.js
- Pass portaledClasses so that clicking on the Month/Day button will no longer close the entire Flyout
> Modifier dropdown gets closed datepicker

- src/components/modal/ModalDialog.js
Increases the contrast ratio of the icon to >3:1 which is the WCAG AA standard for non-text UI.
> chore(accessibility): Increase the contrast of modal close button to 3:1

- src/features/list-view/ListView.js
- src/features/list-view/README.md
- src/features/list-view/__tests__/ListView-test.js
- src/features/list-view/constants.js
- src/features/list-view/examples/ListViewExamples.js
- src/features/list-view/flowTypes.js
Before the fix, the List View displays empty whitespace to the right of the right-most column. 
With the fix...
> Smart Views columns should stretch to fill the container width

- conf/jest/enzyme-adapter.js
- flow-typed/box-ui-elements.js
- src/api/Feed.js
- src/constants.js
- src/elements/content-sidebar/activity-feed/task-new/TaskActions.js
- src/elements/content-sidebar/activity-feed/task-new/__tests__/Task-test.js
- src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/Task-test.js.snap
- Fixes the task API to use the new enum format for task_types
- Removes the possibility to "fall through" to general task since the field is non-nullable and the update PUT payload must match the task type
> fix(tasks): correct task type enum

- src/constants.js
- src/elements/content-sidebar/versions/Versions.js
- src/elements/content-sidebar/versions/VersionsItem.js
- src/elements/content-sidebar/versions/VersionsItemButton.js
- src/elements/content-sidebar/versions/VersionsList.js
- src/elements/content-sidebar/versions/VersionsSidebar.js
- src/elements/content-sidebar/versions/VersionsSidebarContainer.js
- src/elements/content-sidebar/versions/__tests__/VersionsItem-test.js
- src/elements/content-sidebar/versions/__tests__/VersionsItemButton-test.js
- src/elements/content-sidebar/versions/__tests__/VersionsList-test.js
- src/elements/content-sidebar/versions/__tests__/VersionsSidebarContainer-test.js
- src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsItem-test.js.snap
- src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsItemButton-test.js.snap
- src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsList-test.js.snap
- src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsSidebarContainer-test.js.snap
- src/utils/__tests__/dom-test.js
- src/utils/dom.js
- test/integration/content-sidebar/ContentSidebar.e2e.test.js
This change ended up being fairly large, so I wanted to break it into its own pull request. It should be merged before #1035. The new delete and promote actions will require programatic access to set the currently-selected version. Managing this state in the container centralizes the navigation logic nicely.
>  refactor(versions): Move history logic from version item to container

- i18n/en-US.properties
- src/features/shared-link-settings-modal/messages.js
Update section heading and form label for custom URLs in shared link settings modal.
> fix(shared-link-settings-modal): Update custom URL label

- conf/styleguide.styles.scss
- src/elements/common/base.scss
- src/elements/common/breadcrumbs/Breadcrumb.scss
- src/elements/content-sidebar/activity-feed/approval-comment-form/ApprovalCommentForm.scss
- src/features/access-stats/AccessStatsItem.js
- src/features/access-stats/AccessStatsItem.scss
- src/features/access-stats/__tests__/__snapshots__/AccessStatsItem-test.js.snap
- src/features/item-details/ItemProperties.scss
- src/features/metadata-instance-editor/fields/DateField.scss
This PR addresses the following issues:
- **Critical**: Preview, rename, share, and create folder modals do not show at all in ContentExplorer or ContentPicker
- Access Stats items flash on hover in EUA due to specificity issues with PlainButton
- Access Stats anchor text and icons are not vertically centered
- Access Stats anchor text has its own hover treatment rather than using that of its parent button
- Breadcrumb list show a large gap before subsequent breadcrumbs when viewing a folder with a short name
- Metadata instance editor date fields did not take up the full width of the sidebar in the same way as standard text inputs
> style(elements): Fix various style specificity issues; fix modal height

- flow-typed/box-ui-elements.js
- src/elements/content-preview/ContentPreview.js
- src/elements/content-sidebar/versions/VersionsSidebarContainer.js
- src/elements/content-sidebar/versions/__tests__/VersionsSidebarContainer-test.js
This callback will allow ContentPreview/ContentExplorer or other consumers to control the header when a version is previewed.
Open Questions:
1. Should we send the whole version info back in the callback? This will allow consumers to skip additional network calls and directly add the new version info into their redux store/state.
2. Can we always assume that the current version will be at the beginning of the versions array?
> chore(content-preview): Trigger callback when a new version is previewed

- src/features/query-bar/__tests__/ValueField-test.js
- src/features/query-bar/components/filter/ValueField.js
- Check to see if `selectedValues` is an array of a null element, if so, return undefined
^The case above is due to the user clicking on the X button when deleting the Datepicker input
> fix(query-bar): blank page shown on clicking x button in date input

- src/elements/content-sidebar/DetailsSidebar.js
- src/elements/content-sidebar/__tests__/DetailsSidebar-test.js
- src/elements/content-sidebar/__tests__/__snapshots__/DetailsSidebar-test.js.snap
Returning `null` in render causes the Details sidebar to momentarily collapse, which is causing issues with the sidebar navigation tooltips.
> fix(sidebar): Details sidebar render no longer collapses on load

- src/features/list-view/styles/ListView.scss
- Use 11px for height and width instead of 17px to maintain consistency with parent app
> fix(list-view): use smaller sort icon

- src/features/query-bar/__tests__/FilterButton-test.js
- src/features/query-bar/components/filter/FilterButton.js
- handle two distinct cases:
1. whether or not the initial condition should be set
2. whether or not we want to reinitialize conditions from the parent app
> fix(query-bar): persist changes after closing flyout

- src/elements/content-preview/ContentPreview.scss
This fixes an issue in the beta versions of Chrome 74 and 75 where Preview is not shown on the shared files page. Using `height: 100%` inside a flex parent without its own height defined can be very flaky.
> fix(preview): Preview now expands to fill its flex parent when possible

- flow-typed/box-ui-elements.js
- src/api/Metadata.js
- src/api/__tests__/Metadata-test.js
- src/elements/content-sidebar/DetailsSidebar.js
- src/elements/content-sidebar/SidebarFileProperties.js
- src/elements/content-sidebar/__tests__/DetailsSidebar-test.js
- src/elements/content-sidebar/__tests__/SidebarFileProperties-test.js
- src/elements/content-sidebar/__tests__/__snapshots__/SidebarFileProperties-test.js.snap
Removes fetching of classification from within the details sidebar and relies on the value passed in.
Classification value was being passed in via the `bannerPolicy` prop which is now renamed to `classification` with a more descriptive object structure.
> fix(details-sidebar): classification for collaborators

- i18n/en-US.properties
- src/elements/common/messages.js
- src/elements/content-sidebar/activity-feed/task-new/AssigneeStatus.js
- src/elements/content-sidebar/activity-feed/task-new/Assignees.js
- src/elements/content-sidebar/activity-feed/task-new/Task.js
- src/elements/content-sidebar/activity-feed/task-new/Task.scss
- src/elements/content-sidebar/activity-feed/task-new/__tests__/Assignees-test.js
- src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/Assignees-test.js.snap
- src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/Task-test.js.snap
- This currently renders the full assignee list in a dropdown
when the +N icon next to the first 3 assignment avatars is clicked
- A followup commit will add pagination via infinite scroll
> feat(tasks): show full task assignee list in dropdown

- src/components/tooltip/Tooltip.js
- src/components/tooltip/__tests__/Tooltip-test.js
- src/features/left-sidebar/LeftSidebarLink.js
- src/features/left-sidebar/__tests__/__snapshots__/LeftSidebarLink-test.js.snap
- src/features/left-sidebar/styles/LeftSidebar.scss
- src/styles/common/_links.scss
As part of the accessibility push, links should have a blue outline by default
Changes include:
- Removing `outline: none` around links
- Added `makeTabbable` property to tooltip to prevent active state of left sidebar links from showing
- Changing `line-height` of left sidebar link to smooth out outline
> style(links): restore default link outline

- src/features/list-view/ListView.js
- src/features/list-view/examples/ListViewExamples.js
- src/features/list-view/styles/ListView.scss
- Take in isGridHeaderSortable handler that determines whether or not a column header is sortable
- Apply ```cursor: pointer``` if they column header is sortable
> fix(list-view): show pointer on hover of metadata column header

- src/features/list-view/styles/ListView.scss
- make icon sort chevron have a height / width of 12px
- adjust margins to center the icon
> fix(list-view): add styles for icon sort chevron

- src/components/text-input-with-copy-button/TextInputWithCopyButton.js
What this PR does: 
This always guarantees that the field that is focused in the modal starts on the left, rather than the right.
> fix(modal): fix focus issue

- src/features/metadata-instance-editor/fields/FloatField.js
- src/features/metadata-instance-editor/fields/__tests__/validateField-test.js
- src/features/metadata-instance-editor/fields/validateField.js
FloatField was took an optional `allowTrailingPeriod` which wasn't passed in all field validations. This caused inconsistent behavior.
Since there isn't a clear use case for disallowing trailing period, I'm removing the extra option.
> fix(floatfield): always allow trailing period for float field

- src/components/text-input/README.md
- src/components/tooltip/Tooltip.js
- src/components/tooltip/__tests__/Tooltip-test.js
- src/components/tooltip/__tests__/__snapshots__/Tooltip-test.js.snap
If text is absent for the tooltip it rendered only its children otherwise a tethered component. As such the DOM is re-rendered when tooltip gets text and thus the underlying input loses focus.
This partially reverts #1066
> fix(text-input): looses focus when tooltip toggles

- src/features/metadata-instance-editor/TemplateDropdown.scss
The template dropdown uses the Flyout component which wraps a SelectorDropdown component.
Both of these components use the Overlay component in its implementation.
This results in the TemplateDropdown component having two layers of Overlay components.
This isn't a problem for most cases for in Safari causes the vertical scroll bar to disappear because of the nested transform CSS properties.
This change manually removes the CSS transform of the inner Overlay component to fix this bug.
> fix(metadata): template dropdown scrollbar issue in safari

- conf/styleguide.config.js
Param and Plural should not be in the styleguide.conf.  These are covered by the documentation for FormattedCompMessage already.
> Fix styleguidest warnings for new i18n components

- src/api/Users.js
- src/api/__tests__/Users-test.js
Default avatar url returned by the API is 28*28. The avatar is 32*32 in the UI which makes the avatar look blurry. Fixing avatar urls in activity sidebar to add the pic_type param so we can specify next size up in the API for avatars which will return 40*40 image resolution.
> fix(api): Fix avatar resolution in activity sidebar

- src/elements/content-sidebar/activity-feed/comment/Comment.js
- src/elements/content-sidebar/activity-feed/comment/Comment.scss
- src/elements/content-sidebar/activity-feed/comment/__tests__/Comment-test.js
- Fixed condition to make sure comment menu renders given the right `permissions`
- Reorder CTA buttons inside delete confirmation overlay.
> fix(tasks): comments menu does not appear on activity sidebar in preview

- src/components/footer-indicator/FooterIndicator.js
- src/components/footer-indicator/FooterIndicator.md
- src/components/footer-indicator/__tests__/__snapshots__/FooterIndicator-test.js.snap
The current footer indicator tooltip appears to the right of the indicator, which causes unwanted scrollbars to appear in certain browsers and pages and long text to get cut off at the bottom of the viewport.
This pull request fixes the above issues by changing the position of the footer indicator tooltip from `middle-right` to `top-right`.
> fix(footer-indicator): move tooltip to appear above footer indicator

- src/icons/file-icon/FileIcon.js
- src/icons/file-icon/__tests__/FileIcon-test.js
- src/icons/file-icon/__tests__/__snapshots__/FileIcon-test.js.snap
- src/icons/microsoft-office/OfficeDesktopIcon.js
- src/icons/microsoft-office/OfficeOnlineIcon.js
- src/icons/microsoft-office/__tests__/OfficeDesktopIcon-test.js
- src/icons/microsoft-office/__tests__/OfficeOnlineIcon-test.js
Updating the icon for xlsb files to match the excel spreadsheet icon currently used for xlsx and xlsm files.
> feat(office-online): adding excel spreadsheet icon for xlsb files

- src/elements/content-sidebar/activity-feed/comment/Comment.scss
Client apps which might have more deeply-nested structure will require a standard, higher z-index value. This applies one to the tethered container.
> fix(comment): use overlay z-index for confirmation dialog

- src/components/sidebar-toggle-button/README.md
- src/components/sidebar-toggle-button/SidebarToggleButton.js
- src/components/sidebar-toggle-button/SidebarToggleButton.scss
- src/components/sidebar-toggle-button/__tests__/SidebarToggleButton-test.js
- src/components/sidebar-toggle-button/__tests__/__snapshots__/SidebarToggleButton-test.js.snap
- src/components/sidebar-toggle-button/index.js
- src/elements/common/interactionTargets.js
- src/elements/content-sidebar/SidebarNav.js
- src/elements/content-sidebar/SidebarNav.scss
- src/elements/content-sidebar/SidebarNavButton.js
- src/elements/content-sidebar/__tests__/__snapshots__/SidebarNav-test.js.snap
- test/integration/content-sidebar/ContentSidebar.e2e.test.js
> feat(sidebar): Toggle button

- conf/prepush.sh
So that files that may be generated during the build process are either cleaned up or committed and tested.
> build(prepush): add check for uncommitted files before pushing

- src/components/selector-dropdown/SelectorDropdown.js
The auto scroll for the selector dropdown will scroll the item in to
center of the container when hover over. The correct behavior should
only scroll the item into the nearest view of the container.
> fix(scroll-if-needed): fix scroll-if-needed on selector dropdown

- src/api/uploads/MultiputUpload.js
- src/api/uploads/__tests__/MultiputUpload-test.js
`partsUploaded` was a field that was never updated, so we entered into a race condition: (1) uploading all the chunked parts and (2) sha1Worker computing all the digests. If (2) finishes first (which is the case in probably all of the other browsers), then there is no issue. But if (1) finishes first (which is the case in IE11), committing the upload session was at the mercy of `onWorkerMessage` which was referencing the value of `partsUploaded` which was never updated and as a result, `undefined`.
The fix below was to redirect the logic when the `done` event is sent from the sha1Worker back to `processNextParts` which will commit the session
> fix(uploader): MultiputUploads stop hanging in IE11

- .travis.yml
- package.json
- scripts/prepush.sh
- scripts/release.sh
- yarn.lock
- Upgrades husky to the latest version
- Adds back pre-push hook except for when running a release
- Disables husky hooks for CI also
- Reverts back to checking uncommitted files during pre-push
> build: disable husky for release build

- src/elements/content-sidebar/activity-feed/task-form/TaskForm.js
Events within the add/edit modal for tasks fail to send because of missing component value.
> fix(tasks_new): add missing resin component

- src/components/nav-sidebar/NavSidebar.scss
- src/features/left-sidebar/LeftSidebar.md
Reduces the size of the sidebar toggle button to reduce the overflow of the focus outline, which is a bit jarring when hovering other items. Below shows the reduced size.
Before
After
> fix(nav-sidebar): reduce size of toggle button to fix focus outline

- src/elements/content-sidebar/activity-feed/task-new/AssigneeList.js
- src/elements/content-sidebar/activity-feed/task-new/AssigneeList.scss
- src/elements/content-sidebar/activity-feed/task-new/AvatarGroupAvatar.js
- src/elements/content-sidebar/activity-feed/task-new/AvatarGroupAvatar.scss
- src/elements/content-sidebar/activity-feed/task-new/_mixins.scss
- This pulls out the CSS for the avatar component so that it imports its own stylesheet instead of relying on the AvatarGroup stylesheet
- Slight refactors:
- Offset the border by nudging badges by 1px
- Change avatar inner component size to 100% of the container instead of hardcoding the size twice. This makes it so adding a class to the container will set the width for both without referencing private classes or increasing specificity.
> refactor(task-new): componentize task assignee css

- src/features/metadata-instance-editor/TemplateDropdown.js
- src/features/metadata-instance-editor/__tests__/TemplateDropdown-test.js
- add onMenuToggleHandler because in the client app there is a use case where the caret icon needs to be transformed depending on if the menu is open or not
> fix(template-dropdown): add onMenuToggle handler to TemplateDropdown

- i18n/en-US.properties
- src/features/unified-share-modal/EmailForm.js
- src/features/unified-share-modal/UnifiedShareModal.js
- src/features/unified-share-modal/__tests__/EmailForm-test.js
- src/features/unified-share-modal/messages.js
Add property to limit the number of contact pills that can be created at one time.
Remove reset of error on contact input.  This preserves the contact limit error.
> feat(unified-share-modal): add property to limit the number of contacts

- src/icons/badges/MetadataActiveBadge.js
- src/icons/badges/MetadataDefaultBadge.js
- src/icons/badges/__tests__/__snapshots__/MetadataActiveBadge-test.js.snap
- src/icons/badges/__tests__/__snapshots__/MetadataDefaultBadge-test.js.snap
As requested by design, the background for these icons should be set to none
> chore: update metadata icon background color

- src/features/metadata-instance-editor/TemplateDropdown.js
- src/features/metadata-instance-editor/__tests__/TemplateDropdown-test.js
- Change onMenuToggle to onDropdownToggle as the client app is now using onDropdownToggle
> chore: rename onMenuToggle to onDropdownToggle

- src/elements/content-sidebar/AddTaskMenu.scss
Missed this visual difference before in my last PR. Trying to remove as many CSS overrides as we can so it matches with other similar menus like the "Open with" menu.
> fix(task-new): Minor visual tweak to add tasks menu

- src/elements/content-sidebar/activity-feed/comment/Comment.js
- src/elements/content-sidebar/activity-feed/comment/Comment.scss
- set default button to "cancel" on confirm mini-modal is open
- allow for escape to close when confirm mini-modal is open
- use consistent button padding/margin so if buttons stack they have space between (and sync up spacing with other buttons)
> fix(comment): padding and a11y adjustments for comment UI

- src/styles/common/_buttons.scss
Changes buttons to not have a default horizontal margin, except between other buttons. The current 5px margin is almost always overridden when used.
> fix(button): remove horizontal margin from buttons

- .circleci/config.yml
- package.json
- scripts/prepush.sh
1. Only builds the explorer entry point that includes explorer, preview, sidebar and open with. Does not include content picker so we may need another job for that but that can be added later.
2. Fixes an issue in circle config that was preventing PR builds
3. Combines babel and webpack build for circle
4. Removes a couple of steps from pre-push hook
Should show circle under checks tab now
> build: perf improvements and fixes

- .circleci/config.yml
- README.md
Fixes an issue where yarn cache was getting bust due to branch/PR name, which was adding 1-2m to the build time.
Also adds a badge <img src="https://circleci.com/gh/box/box-ui-elements/tree/master.svg?style=shield"/>
>  build: fix caching for circle ci

- scripts/styleguide.config.js
Adds a config option that formats component paths in the documentation in a way that can be copy-pasted into consuming apps
> docs(styleguide): create usable import paths

- i18n/en-US.properties
- src/features/classification/AddClassificationBadge.js
- src/features/classification/AddClassificationBadge.scss
- src/features/classification/ClassifiedBadge.js
- src/features/classification/ClassifiedBadge.scss
- src/features/classification/__tests__/__snapshots__/AddClassificationBadge-test.js.snap
- src/features/classification/__tests__/__snapshots__/ClassifiedBadge-test.js.snap
- src/features/classification/_mixins.scss
- src/features/classification/messages.js
Just a few small UI updates for the classification badge:
- Changed "Add Classification" text to "Classify"
- Updated "Classify" button text color for better accessibility
- Capitalized "Classify" for better i18n
- Removed tag icon
- Alignment adjustment
> fix(classification): Classification badge UX tweaks

- src/elements/content-uploader/ItemAction.js
- src/elements/content-uploader/OverallUploadsProgressBar.js
- src/elements/content-uploader/UploadsManager.js
- src/elements/content-uploader/__tests__/OverallUploadsProgressBar-test.js
- src/elements/content-uploader/__tests__/__snapshots__/ItemAction-test.js.snap
- src/elements/content-uploader/__tests__/__snapshots__/OverallUploadsProgressBar-test.js.snap
Adding resin tracking for retrying failed uploads and expanding/collapsing the uploads manager.
> feat(uploads): add resin tracking for uploads manager

- src/elements/content-sidebar/versions/VersionsSidebarContainer.js
Currently, the host application isn't informed when a version is promoted, which can lead to stale data and user confusion. This is a temporary workaround to avoid a launch blocker; I intend to follow-up with a better solution soon.
> fix(versions): Reload the page when a version is promoted (temporary)

- src/elements/content-sidebar/activity-feed/comment/Comment.js
- src/elements/content-sidebar/activity-feed/comment/CommentDeleteConfirmation.js
- src/elements/content-sidebar/activity-feed/comment/__tests__/CommentDeleteConfirmation-test.js
- src/elements/content-sidebar/activity-feed/comment/__tests__/__snapshots__/CommentDeleteConfirmation-test.js.snap
I initially started splitting the comment delete confirmation out into a separate component to address what I thought was an accessibility bug, but then realized it was behaving as intended. Anyhow, this is probably still better as a separate component.
> refactor(comment): move comment delete to separate component

- src/elements/content-preview/PreviewLoading.js
- src/elements/content-preview/__tests__/__snapshots__/PreviewLoading-test.js.snap
- src/icons/states/README.md
- src/icons/states/SecurityBlockedState.js
- src/icons/states/__tests__/SecurityBlockedState-test.js
- src/icons/states/__tests__/__snapshots__/SecurityBlockedState-test.js.snap
> feat(preview): new icon for security blocking

- src/elements/content-sidebar/versions/VersionsItem.js
Watermarked files currently do not support preview for older versions. I hope to be able to revert this change in the future, but the timeline is uncertain.
> fix(versions): Disable prior version preview for watermarked files

- scripts/prepush.sh
small change to the prepush script which prevents building against stale files that are `.gitignore`d. (e.g., i18n/json and i18n/*.js)
- run all the bundle builds prior to tests and localization updates
- remove duplicate call to `yarn build:i18n` (which would build translations against the contents of es/ *before* updating it)
Tested via:
- populating en-US.js, messages.json, and es/**/messages.js with dummy data to make sure they were updated prior to the uncommited file check
- same as № 1 but adding a new message
- same as № 1 and № 2, but also removing the newly-added message to make sure .properties got updated properly
> build(scripts): Build and update all files prior to push

- src/api/Versions.js
- src/api/__tests__/Versions-test.js
- src/elements/content-sidebar/versions/VersionsSidebarAPI.js
- src/elements/content-sidebar/versions/VersionsSidebarContainer.js
- src/elements/content-sidebar/versions/__tests__/VersionsSidebarAPI-test.js
- src/elements/content-sidebar/versions/__tests__/VersionsSidebarContainer-test.js
The versions container was getting a bit large, so it seemed like a good idea to extract the data access layer to its own class.
> refactor(versions): Move version api helper methods to a separate class

- .circleci/config.yml
- scripts/commitlint.sh
- Uses the same cypress docker image for all jobs since it has all the necessary tools needed for all jobs. So cache can get re-used. Can be seen here https://github.com/cypress-io/cypress-docker-images/blob/master/base/10.16.0/Dockerfile
- Combines the unit tests and build jobs since they combined still take less than the e2e job which is the bottleneck. Frees up a container.
- Switches commit lint script to use node instead of JQ for json parsing as the latter may not be available on all docker images
- Gives names to job tasks
> build: cleanup and optimizations

- src/components/radio/RadioGroup.js
- src/components/radio/__tests__/RadioGroup-test.js
The rest of the props are not being passed from radio group to the radio button input. Fixed that in this PR.
> fix(radio-group): pass rest of props to radio input

- src/components/radio/RadioGroup.js
- src/components/radio/__tests__/RadioGroup-test.js
Had to add the `value` prop explicitly as it was extracted from the props and was not part of the `...rest`
> fix(radio-group): fix radio group by passing the value prop

- examples/src/DraftJSMentionSelectorExamples.js
- flow/DraftJSFlowStub.js.flow
- src/components/form-elements/draft-js-mention-selector/DraftMentionItem.js
- src/components/form-elements/draft-js-mention-selector/README.md
- src/components/form-elements/draft-js-mention-selector/__tests__/createMentionSelectorState-test.js
- src/components/form-elements/draft-js-mention-selector/createMentionSelectorState.js
- src/components/form-elements/draft-js-mention-selector/index.js
- src/elements/content-sidebar/activity-feed/comment-form/CommentForm.js
- src/elements/content-sidebar/activity-feed/comment/Comment.js
Followup to #1468 - fixes issue with the draftjs comment editor where text already containing mentions was turned back into plaintext, which destroys the references on save.
> fix(comments): format existing mentions in editor

- i18n/en-US.properties
- src/components/i18n/Composition.js
- src/components/i18n/FormattedCompMessage.js
- src/components/i18n/__tests__/Composition-test.js
- src/components/i18n/__tests__/FormattedCompMessage-test.js
- src/components/i18n/__tests__/__snapshots__/FormattedCompMessage-test.js.snap
A message like this:
```jsx
<FormattedCompMessage
description="Body for tooltip pointing to add user button"
id="adminConsole.components.Onboarding.addUserButtonTooltipBodyText"
>
<b>Managed users</b> are employees in your Box Enterprise. They often share your company domain(s) and require a greater amount of control, while <b>External users</b> are clients or partners who have been invited to collaborate on specific content in your enterprise.
</FormattedCompMessage>
```
Caused an exception even though it is perfectly valid.
> fix(i18n): Fix bug where messages starting with HTML cause an exception

- scripts/utils/bdlColorManager
add additional parsing dollar-sign check to make sure partial color names aren't found and replaced.
> fix(bdl): Add SCSS check for color variable name

- src/components/date-picker/DatePicker.js
- src/elements/content-sidebar/activity-feed/task-form/TaskForm.js
In some languages, the day and month are reversed, and so when this is converted to a `new Date()` it gets the incorrect date. Example in German: September 7, 2019 would do `new Date('7.9.2019')` which would create a JS object for July 9, 2019.
In the long term, we'd like to revisit and update the datepicker input field so that the input isn't so freeform, but rather divided into 3 separate fields so that we can distinguish which part is the month, day, and year. This would have the benefit of giving the user an indication of the expected format and prevent them from inputing invalid data.
An example from a credit card form:
For now, though, this PR simply stops allowing freeform input for the task form to sidestep the issue.
Ticket to track this: …
> fix(task-form): disallow text input in date picker

- src/components/select-field/BaseSelectField.js
- src/components/select-field/__tests__/BaseSelectField-test.js
- src/components/select-field/__tests__/__snapshots__/BaseSelectField-test.js.snap
This update will allow passing a `optionRenderer` function to `BaseSelectField`, which can be used to render custom select options. 
This PR also contains the following fixes:
- Avoid scrolling options into view when hovering with the mouse (will still do this for keyboard actions).
- Clicking on the scrollbar (when overlay is set to `overflow: auto` and has max height) no longer closes the dropdown.
- Changed `scrollIntoView` mode in order to make the transition less jarring.
> feat(select-field): Allow rendering custom options

- src/features/left-sidebar/LeftSidebar.js
- src/features/left-sidebar/LeftSidebarLink.js
- src/features/left-sidebar/__tests__/LeftSidebar-test.js
- src/features/left-sidebar/__tests__/__snapshots__/LeftSidebar-test.js.snap
- src/features/left-sidebar/__tests__/__snapshots__/defaultNavLinkRenderer-test.js.snap
- src/features/left-sidebar/__tests__/defaultNavLinkRenderer-test.js
- src/features/left-sidebar/defaultNavLinkRenderer.js
- src/features/left-sidebar/index.js
Follow up to #1495 
This prop allows for changing Left Nav menu items with UI treatment or wrapping the `defaultNavLinkRenderer` with another component or both!
> feat(left-sidebar): LeftSidebar supports custom navLinkRenderer

- src/features/left-sidebar/LeftSidebar.js
- src/features/left-sidebar/LeftSidebarDropWrapper.js
- src/features/left-sidebar/__tests__/LeftSidebarDropWrapper-test.js
- src/features/left-sidebar/__tests__/__snapshots__/LeftSidebarDropWrapper-test.js.snap
- src/features/left-sidebar/__tests__/__snapshots__/LoadingIndicatorWrapper-test.js.snap
**Reviewers:** I had to close the previous PR as it was not created from my fork. For reference: https://github.com/box/box-ui-elements/pull/1507
This PR allows you to set `showDropZoneOnHover` for menu items in left sidebar. 
`showDropZoneOnHover`  when true it will only show drop veil on hover. 
`showDropZoneOnHover`  when false it will show drop veil for the duration of items being dragged.
Updated: GIF to show behavior on favorites
>  feat(leftsidebar): Show drop zones only on hover

- scripts/utils/bdlClassnameManager
Add script to update bdl namespace to classes in JS and SCSS files. See `scripts/utils/bdlClassnameManager` for usage guide. See https://github.com/swfree/box-ui-elements/pull/2 to take a look at the script's results.
> feat(bdl): Add script for SCSS bdl scoping

- src/elements/content-sidebar/versions/VersionsItemAction.js
- src/elements/content-sidebar/versions/VersionsItemAction.scss
I've confirmed that Resin events are still firing as expected with this change; the buttons were never necessary.
> fix(versions): Update version actions to avoid unnecessary buttons

- src/features/left-sidebar/LeftSidebar.js
- src/features/left-sidebar/styles/LeftSidebar.scss
When `NavList` is wrapped in `LoadingIndicatorWrapper`, it appends a `LoadingIndicator` as a child which `:last-child` pseudo class rule does not account for.
Added additional rules when loading indicator is present.
> fix(left-sidebar): Adjust margins for loading indicator

- src/elements/content-sidebar/SidebarNav.js
- src/elements/content-sidebar/SidebarNav.scss
- src/elements/content-sidebar/additional-tabs/AdditionalTabs.scss
- src/elements/content-sidebar/additional-tabs/AdditionalTabsLoading.js
- src/elements/content-sidebar/additional-tabs/MoreTabPlaceholder.js
Currently, previewing a file with a high number of recommended apps with a short (>500px) viewport causes the preview header to overflow off the top of the screen. This change resolves the issue by allowing the recommended apps section to shrink and scroll.
> fix(sidebar): Limit maximum height of additional tabs in sidebar nav

- flow-typed/box-ui-elements.js
- i18n/en-US.properties
- src/elements/content-sidebar/__tests__/DetailsSidebar-test.js
- src/elements/content-sidebar/__tests__/SidebarClassification-test.js
- src/elements/content-sidebar/__tests__/__snapshots__/DetailsSidebar-test.js.snap
- src/elements/content-sidebar/__tests__/__snapshots__/SidebarClassification-test.js.snap
- src/features/classification/Classification.js
- src/features/classification/Classification.scss
- src/features/classification/ClassifiedBadge.js
- src/features/classification/README.md
- src/features/classification/__tests__/Classification-test.js
- src/features/classification/__tests__/__snapshots__/Classification-test.js.snap
- src/features/classification/__tests__/__snapshots__/ClassifiedBadge-test.js.snap
- src/features/classification/messages.js
- src/features/shared-link-settings-modal/SharedLinkSettingsModal.js
- src/features/shared-link-settings-modal/__tests__/__snapshots__/SharedLinkSettingsModal-test.js.snap
- src/features/unified-share-modal/UnifiedShareModalTitle.js
- src/features/unified-share-modal/__tests__/UnifiedShareModal-test.js
- src/features/unified-share-modal/__tests__/__snapshots__/UnifiedShareModalTitle-test.js.snap
- test/sidebar.html
BREAKING CHANGE: Also changes advisoryMessage prop to definition to keep terminology consistent
UI will now show a "Definition" label on top of the definition text:
> feat(classification): updated ui for classification

- src/api/uploads/MultiputUpload.js
- src/api/uploads/__tests__/MultiputUpload-test.js
- src/elements/content-uploader/ContentUploader.js
- src/elements/content-uploader/__tests__/ContentUploader-test.js
Allow single uploads that are being uploaded in parts via the Chunked Upload API to be resumed from the middle of an existing upload session rather than restarting from the beginning with a new upload session, using the retry button on each individual item in the uploads manager.
**Note:** This PR is for a portion of the changes being made in [this PR](https://github.com/box/box-ui-elements/pull/1497), with the changes being made for multiple file resuming and some of the refactoring from that original PR separated out to be merged later, so that more incremental changes can be merged in to minimize impact, and each smaller section can be tested by QA separately.
> feat(uploads): resume a single file upload

- babel.config.js
Message files are currently built along the following path, with the responsible script on top and associated files below:
```
Developer         -> build:*:es -> build:i18n (for both)
src/*/messages.js -> i18n/json  -> i18n/*.properties -> i18n/*.js
```
Unfortunately, the second step was failing silently for scripts such as `yarn start:npm` due to a misconfigured Babel environment setting. Even with this change, it will still be necessary to run `yarn build:i18n` manually after changing a message. The watcher doesn't run it automatically.
> build(i18n): Update babel to build i18n/json for local development

- i18n/en-US.properties
- src/api/Feed.js
- src/api/__tests__/Feed-test.js
- src/elements/content-sidebar/activity-feed/task-form/TaskError.js
- src/elements/content-sidebar/activity-feed/task-form/TaskForm.js
- src/elements/content-sidebar/activity-feed/task-form/__tests__/TaskError-test.js
- src/elements/content-sidebar/activity-feed/task-form/__tests__/TaskForm-test.js
- src/elements/content-sidebar/activity-feed/task-form/__tests__/__snapshots__/TaskError-test.js.snap
- src/elements/content-sidebar/activity-feed/task-form/messages.js
add support for handling race conditions that can occur when altering a task in a certain way. 
- if a task is being edited to follow the "any" completion rule, any existing approvers/completers could trigger the rule stating that the task is done.
- we need to make sure that we perform the checks in a better sequence to preserve changes to tasks, collaborators, and status in the safest order possible
- re-sequencing the work such that task details are updated before removals
- adding new message for any attempts to remove assignees **after** a task is updated to "any" status
> feat(tasks): handle new error message with title and description

- src/elements/content-uploader/ContentUploader.js
- src/elements/content-uploader/__tests__/ContentUploader-test.js
After an upload fails and has an error tied to the item, this error is currently never removed when retrying an upload. If this error exists when the retried upload finishes, the status of the item in the uploads manager is not set to completed, and so the item will continue to show the loading bar in the uploads manager (and because it is in a staged state, cannot be removed from the uploads manager due to the remove button being disabled). This PR removes the error after an upload is retried, so that the uploads manager will show the upload as completed after it finishes.
> fix(uploads): reset item error after retry

- src/elements/content-sidebar/activity-feed/common/user-link/UserLink.scss
Allow long user names to wrap in comments and tasks.
Before:
After:
> fix(user-link): allow wrapping of long user names

- src/elements/content-sidebar/activity-feed/comment/Comment.js
- src/elements/content-sidebar/activity-feed/comment/Comment.scss
- src/elements/content-sidebar/activity-feed/comment/__tests__/__snapshots__/Comment-test.js.snap
- src/elements/content-sidebar/activity-feed/task-new/Task.js
- src/elements/content-sidebar/activity-feed/task-new/Task.scss
- src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/Task-test.js.snap
Follow-up to https://github.com/box/box-ui-elements/pull/1602 that fixes long username wrapping in Edge. Sorry in advance for the browser targeting, but I tried and tried and couldn't find a better way that didn't break other browsers and fixed Edge... :(
> fix(activity-feed): fix long user names in tasks/comments in Edge

- i18n/en-US.properties
- src/elements/content-sidebar/versions/VersionsSidebar.js
- src/elements/content-sidebar/versions/VersionsSidebar.scss
- src/elements/content-sidebar/versions/__tests__/VersionsSidebar-test.js
- src/elements/content-sidebar/versions/messages.js
This will show a message if a user has reached the max version history of 1,000 entries. **The screen shot shows a max history of 2, but that is just for demonstration purposes. Actual message is set to a length of 1,000.**
> feat(react): Add text for max version history

- DEVELOPING.md
- src/components/avatar/Avatar.js
- src/components/avatar/__tests__/Avatar-test.js
Refactoring `Avatar` to use hooks (take 2). The first iteration worked fine but due to a few libraries using their own version of React (and also during node_module linking), this was reverted.
Now with `yarn resolutions`, we can avoid having duplicate React instances and multiple versions of react.
> refactor(avatar): Convert Avatar to hooks implementation

- src/elements/content-sidebar/activity-feed/activity-feed/EmptyState.js
> fix(sidebar): remove unwanted parentheses in empty state

- src/elements/content-sidebar/SidebarPanels.js
- src/elements/content-sidebar/__tests__/__snapshots__/SidebarPanels-test.js.snap
I guess regex + optional parameters don't work.
> fix(sidebar): Fix deeplinking for version history sidebar

- src/elements/common/KeyBinder.js
- src/elements/common/__tests__/KeyBinder.js
Move from `componentDidUpdate` to use the  `getDerivedStateFromProps` function. This also adds tests for the arrow keys and prop updates.
> fix(arrow-stepper): Fix arrow stepper in KeyBinding component

- src/elements/common/sub-header/SubHeaderRight.js
- src/elements/common/sub-header/__tests__/SubHeaderRight-test.js
This change removes the view change (grid view) button unless there is a provided `gridColumnCount` prop. Content Picker was showing the grid view button when it doesn't support grid view.
> fix(subheader): Add logic around grid view

- src/features/classification/ClassifiedBadge.js
- src/features/classification/ClassifiedBadge.scss
- src/features/classification/__tests__/__snapshots__/ClassifiedBadge-test.js.snap
- src/features/security/README.md
- src/features/security/SecurityBadge.js
- src/features/security/SecurityBadge.scss
- src/features/security/__tests__/SecurityBadge-test.js
- src/features/security/__tests__/__snapshots__/SecurityBadge-test.js.snap
- src/features/security/_mixins.scss
- src/features/security/index.js
This update will move out the actual badge markup from the `ClassifiedBadge` to a slightly more re-usable `SecurityBadge` component. This will allow us to use the same look and feel of classification with other security-related badges.
> feat(security): adding SecurityBadge component

- src/features/security/SecurityBadge.js
The `SecurityBadge`, unlike the `ClassifiedBadge`, should allow a `React.Node` as a message.
> fix(security-badge): Fixing SecurityBadge flow type

- src/features/unified-share-modal/UnifiedShareModal.scss
> fix(usm): "Link Settings" should not line wrap

- src/components/select-field/SelectField.scss
Does not change menu item padding
**Before**
**After**
> fix: slight adjust in check mark alignment

- src/features/unified-share-modal/SharedLinkAccessMenu.js
- src/features/unified-share-modal/SharedLinkSection.js
- src/features/unified-share-modal/UnifiedShareModal.js
- src/features/unified-share-modal/__tests__/SharedLinkAccessMenu.test.js
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkAccessMenu.test.js.snap
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkSection.test.js.snap
- src/features/unified-share-modal/flowTypes.js
When creating shared links, this changes the access level drop down to show menu items in a disabled state if disabled by an access policy. Before such happened just based on the fact that some classification existed or not, which is incorrect since you can just have classifications without any applicable policies.
Additionally a small cleanup/refactor of the menu generation.
When access levels are disabled due to a policy
When access levels are disabled but due to other reasons
> fix(unfied-share-modal): shared link access levels

- src/components/select-field/BaseSelectField.js
- src/components/select-field/SelectField.scss
- src/components/select-field/SingleSelectField.js
- src/components/select-field/__tests__/BaseSelectField.test.js
- src/constants.js
- src/features/metadata-instance-editor/fields/EnumField.js
- src/features/metadata-instance-editor/fields/MultiSelectField.js
- src/features/metadata-instance-editor/fields/__tests__/__snapshots__/EnumField.test.js.snap
- src/features/metadata-instance-editor/fields/__tests__/__snapshots__/MultiSelectField.test.js.snap
This PR sets a maximum height for the `SelectField` component, which enables arrow key scrolling in dropdown menus.
**Chrome**
**Firefox**
**Safari**
**IE11**
**In a large viewport**
**In a small viewport**
**With fields above the expanded field**
> fix(select-field): Enable arrow scrolling in select fields

- src/components/pill-selector-dropdown/PillSelectorDropdown.js
- src/components/pill-selector-dropdown/__tests__/PillSelectorDropdown.test.js
- src/components/pill-selector-dropdown/__tests__/__snapshots__/PillSelectorDropdown.test.js.snap
Recommend ignoring whitespace to review. The main change is to move the `<Label>` outside of the `<SelectorDropdown>` so that the `<PillSelector>` is the root of the `selector` prop. This is needed in order to properly pass the `aria-*` attributes to the `textfield`.
> fix(pill-selector-dropdown): fix aria attributes

- src/components/label/Label.js
The docs for the `<Label>` component were ordered incorrectly.
> docs(label): fix label docs

- src/components/modal/ModalDialog.js
This looks visually the same (due to absolute positioning), but results in the screen reader reading the title of the modal before saying "Close button" (for browsers like Chrome that read the contents of the modal... it seems Safari doesn't read it all out).
> fix(modal): move close button after header for better screen reader a11y

- src/components/tooltip/Tooltip.scss
Old error tooltip with low color contrast text and misaligned close button (when shown):
New error tooltip with better color contrast and improved layout of close button (when shown):
> fix(tooltip): color contrast and layout fixes

- package.json
- yarn.lock
Fixes warnings caused by deprecated lifecycle methods
Also contains a fix for 1.x rerender issues
> chore(react-tether): Upgrade react-tether to 1.0.5

- src/components/media/Media.scss
> style(media): Correctly size Media body flex container for MS Edge

- src/icons/general/IconLogin.js
- src/icons/general/IconLogin.md
- src/icons/general/IconStorage.js
- src/icons/general/IconStorage.md
- src/icons/general/__tests__/IconLogin.test.js
- src/icons/general/__tests__/IconStorage.test.js
> feat(icon): create login and storage icon

- src/features/classification/Classification.js
- src/features/classification/ClassifiedBadge.js
- src/features/classification/ClassifiedBadge.scss
- src/features/classification/__tests__/Classification.test.js
- src/features/classification/__tests__/ClassifiedBadge.test.js
- src/features/classification/__tests__/__snapshots__/Classification.test.js.snap
- src/features/classification/__tests__/__snapshots__/ClassifiedBadge.test.js.snap
An issue with certain versions of IE11, where rendering a tooltip inside the button breaks. So making the tooltip be the wrapper for button.
> fix(classification): classification tooltip not showing in IE11

- src/elements/content-sidebar/MetadataSidebar.js
onApiError wasn't bound properly to the class so calls to extract onError would fail.
> fix(metadata-sidebar): bind onApiError properly

- src/components/i18n/Composition.js
- src/components/i18n/__tests__/FormattedCompMessage.test.js
- src/components/i18n/__tests__/__snapshots__/FormattedCompMessage.test.js.snap
Fixed a bug where a Param component inside of another component or HTML inside of the children of a FormattedCompMessage would not have its value substituted into the string for translated versions of that string.
Had to unmock the IntlProvider class from react-intl in the FormattedCompMessage tests so that we could use the real react-intl code to do translations. This bug didn't show up if we only used the English string, and the mocked version of the react-intl stuff doesn't support real translations. This also meant we had to do real tests for the Russian plurals tests using react-intl, which is better anyways because it works correctly and we're testing the real thing.
It also meant we had to do a little fancy footwork to get enzyme to work correctly because when you test with real …
> fix(i18n): formatted comp message

- i18n/en-US.properties
- src/features/classification/security-controls/__tests__/SecurityControls.test.js
- src/features/classification/security-controls/__tests__/__snapshots__/SecurityControls.test.js.snap
- src/features/classification/security-controls/__tests__/utils.test.js
- src/features/classification/security-controls/appRestrictionsMessageMap.js
- src/features/classification/security-controls/messages.js
- src/features/classification/security-controls/utils.js
`SecurityControls` component was using the same message for application restrictions regardless of whether the list of apps was allowed or disallowed. We will now use a separate message for each case.
> fix(classification): Added missing application restriction messages

- i18n/en-US.properties
- src/features/classification/security-controls/__tests__/__snapshots__/SecurityControls.test.js.snap
- src/features/classification/security-controls/messages.js
Changing from `;` to `:` in app restriction messages.
> fix(classification): Updated Security Controls messages

- src/components/pill-cloud/PillCloud.js
- src/components/pill-cloud/__tests__/__snapshots__/PillCloud.test.js.snap
- src/components/pill-selector-dropdown/Pill.js
- src/components/pill-selector-dropdown/PillSelector.js
- src/components/pill-selector-dropdown/PillSelectorDropdown.js
- src/components/pill-selector-dropdown/SuggestedPill.js
- src/components/pill-selector-dropdown/__tests__/__snapshots__/Pill.test.js.snap
- src/components/pill-selector-dropdown/__tests__/__snapshots__/PillSelector.test.js.snap
- src/components/pill-selector-dropdown/__tests__/__snapshots__/PillSelectorDropdown.test.js.snap
- src/components/pill-selector-dropdown/__tests__/__snapshots__/SuggestedPill.test.js.snap
This PR brings back legacy class names for pill components, to maintain backwards compatibility in apps that consume BUIE. Related to #1734 and #1745.
> fix(css): Add legacy class names to pill components

- src/features/classification/Classification.js
- src/features/classification/__tests__/Classification.test.js
- src/features/classification/security-controls/SecurityControls.js
- src/features/classification/security-controls/SecurityControlsItem.js
- src/features/classification/security-controls/SecurityControlsItem.scss
- src/features/classification/security-controls/__tests__/__snapshots__/SecurityControlsItem.test.js.snap
The information for the `SecurityControls` will normally be fetched separately from the item's own classification data and will be subsequently cached. We're adding a loading indicator in order to allow displaying classification while this additional data is being retrieved.
This PR also includes some style tweaks for the `SecurityControlsItem` tooltip styles.
> feat(classification): Adding loading indicator for SecurityControls

- i18n/en-US.properties
- src/features/classification/security-controls/__tests__/__snapshots__/SecurityControls.test.js.snap
- src/features/classification/security-controls/messages.js
Just removing an extra "and" from one of the messages
> fix(classification): Fixing typo on security controls message

- i18n/en-US.properties
- src/features/classification/security-controls/__tests__/__snapshots__/SecurityControls.test.js.snap
- src/features/classification/security-controls/__tests__/utils.test.js
- src/features/classification/security-controls/messages.js
- src/features/classification/security-controls/utils.js
This contains the following fixes/updates:
- Fixed an issue in which `Sharing restriction applies` message was being shown for `SecurityControls` in short format when a sharing restriction object with `accessLevel="public"` was provided. 
- Fixed an issue in which the message for sharing restriction for company and collaborators was being shown instead of the one for collaborators only, and vice versa.
- Updated the messages for download restrictions that apply to external users in order to remove ambiguity.
- Fixed typo in web download restriction for external users message
> fix(classification): Fixing messages for sharing restrictions

- src/components/select-field/BaseSelectField.js
- src/components/select-field/__tests__/BaseSelectField.test.js
- src/features/metadata-instance-editor/fields/MultiSelectField.js
- src/features/metadata-instance-editor/fields/__tests__/__snapshots__/MultiSelectField.test.js.snap
Issue: misaligned dropdown in Chrome (Mac), IE11 & Edge
**Mac Chrome - before**
**Mac Chrome - after**
**Edge - before**
**Edge - after**
**IE11 - before**
**IE11 - after**
**Safari - after**
**Firefox - after**
> fix(metadata): Fix misaligned multiselect dropdown

- src/api/uploads/MultiputPart.js
- src/api/uploads/MultiputUpload.js
- src/api/uploads/__tests__/MultiputPart.test.js
- src/api/uploads/__tests__/MultiputUpload.test.js
- src/utils/Xhr.js
Adds pause state and resets uploading process for all parts on error. Updates state and retries upload on unpausing the parts. This change stops all auto-resuming after we display an error message to the user.
> fix(uploads): fix auto retry after timeout

- src/elements/content-uploader/ItemAction.js
- src/elements/content-uploader/UploadsManagerAction.js
- src/elements/content-uploader/__tests__/__snapshots__/ItemAction.test.js.snap
- src/elements/content-uploader/__tests__/__snapshots__/UploadsManagerAction.test.js.snap
Adding tracking attributes on the `Resume`/`Resume All` buttons.
> feat(content-uploader): Add tracking on upload resume buttons

- src/components/select-field/SelectField.scss
This PR reintroduces separators into `BaseSelectField` components.
A `SingleSelectField` without the intended separators:
The same `SingleSelectField`, fixed:
> fix(select-field): Reintroduce separators

- src/features/targeting/README.md
- src/features/targeting/constants.js
- src/features/targeting/contexts.js
- src/features/targeting/index.js
- src/features/targeting/message-api.js
- src/features/targeting/targeting-api.js
- src/features/targeting/types.js
most of the types were copied from EUA's in-app-messenger directory. Another PR will remove EUA's same type and import those here.
> feat(targeting): add types used for targeting

- src/common/types/upload.js
- src/elements/content-uploader/ContentUploader.js
- src/elements/content-uploader/__tests__/ContentUploader.test.js
Adds a new optional field on upload item that saves the mb uploaded so far for an item when user resumes an upload
> feat(uploads): save the mb uploaded on resume

- src/components/accessible-svg/index.ts
- src/components/avatar/index.ts
- src/components/button/index.ts
- src/components/loading-indicator/index.ts
- src/components/primary-button/index.ts
- src/components/radar/index.ts
`export * from foo` currently seems to cause a problem with jest/rewire and breaks tests in projects using rewire.
> fix(typescript): migrate to explicit exports

- src/components/collapsible/Collapsible.js
- src/components/collapsible/Collapsible.scss
- src/components/collapsible/__tests__/Collapsible.test.js
- src/components/collapsible/__tests__/__snapshots__/Collapsible.test.js.snap
UX change was requested to add hover effect to the Collapsible component, and they are ok with having this as the default behavior of the component.
Expected behavior: In collapsed state, hovering over the card header should display the Edit button and underline the card title.
> feat(collapsible): display action button when collapsed and hovered

- src/components/date-picker/DatePicker.js
- src/components/date-picker/DatePicker.scss
- src/components/text-area/TextArea.js
- src/components/text-area/TextArea.scss
- src/components/text-area/__tests__/__snapshots__/TextArea.test.js.snap
- src/components/text-input/TextInput.js
- src/components/text-input/TextInput.scss
- src/components/text-input/__tests__/__snapshots__/TextInput.test.js.snap
DatePicker
- make description a \<div\> instead of a \<i\> and have it respect accessibility
- add error accessibility
TextArea
- make description a \<div\> instead of a \<i\>
TextInput
- make description a \<div\> instead of a \<i\>
> fix(form): make description more customizable for components

- src/components/accessible-svg/index.ts
- src/components/avatar/UnknownUserAvatar.tsx
- src/components/avatar/index.ts
- src/components/button/index.ts
- src/components/loading-indicator/index.ts
- src/components/primary-button/PrimaryButton.tsx
- src/components/radar/index.ts
Since they get compiled out and don't exist in the final output. It was causing unnecessary warnings when compiling in consuming repos.
> fix(typescript): remove prop exports

- scripts/utils/bdlClassnameManager
This PR enables bdlClassnameManager to modify class names within TypeScript files (specifically, TSX files).
> chore(typescript): Update bdlClassnameManager to handle TypeScript files

- package.json
- yarn.lock
Note: v2.1.2+ requires a TextEncoder polyfill
> chore: Pin @hapi/address to 2.1.1 to prevent IE11 breakage

- src/features/shared-link-settings-modal/SharedLinkSettingsModal.scss
> fix(modal): Fix shared link setting modal input overflow

- src/features/content-explorer/content-explorer/ContentExplorer.scss
> fix(explorer): Fix search dropdown too long

- CODEOWNERS
It looks like Mergify doesn't fully support CODEOWNERS without `review-requested=0` due to an open [issue](https://github.com/Mergifyio/mergify-engine/issues/448), which would be needed to support multiple owners. We'll want to keep owners as simple as possible for now.
> chore(codeowners): Simplify codeowners to support mergify restrictions

- src/components/flyout/__tests__/Flyout.test.js
This fixes a warning that appears when running tests. Only affects a faked component, so won't affect component behavior.
> fix(flyout): add non-DOM prop to default values in `FakeOverlay`

- src/features/content-explorer/item-list/ItemListButton.js
make the field `readOnly` as the checkbox is cosmetic
> fix(content-explorer): fix prop usage warning in content explorer

- src/features/shared-link-settings-modal/AllowDownloadSection.js
tests and the Item object treat `classification` as a string value, but here it was set as object.
update to clear the warning when performing `yarn test` on these components
> fix(shared-link-settings): match classification type to value

- src/features/metadata-instance-editor/__tests__/TemplateDropdown.test.js
fixes a "list should have a `key`" warning associated with this component
> fix(metadata-instance-editor): fix test warning in componentDidUpdate()

- src/components/radio/RadioGroup.js.flow
- src/components/radio/RadioGroup.tsx
- src/components/radio/__tests__/RadioGroup.test.tsx
- src/components/radio/stories/RadioGroup.stories.tsx
This update will add support for using `RadioGroup` with custom radio button components, so long as they accept and implement the same props as `RadioButton`. This will allow us to support use cases in which a single value needs to be selected, but the appearance and behavior of the UI itself is slightly different from `RadioButton` (e.g. color picker radio buttons).
This change is backward compatible because our existing usages of `RadioGroup` all declare `RadioButton` children, so the only difference is that these will now be cloned instead of replaced with a new `RadioButton` declaration.
> feat(radio-group): Add support for custom radio button components

- src/components/i18n/FormattedCompMessage.js
- src/components/i18n/Plural.js
- src/components/i18n/index.js
- use the react-intl v3 components instead, as they are standard
and will be supported going forward
- FormattedCompMessage -> FormattedMessage
- Plural -> FormattedPlural
> feat(i18n): deprecate FormattedCompMessage and Plural

- i18n/en-US.properties
- src/components/time/messages.js
- src/elements/content-sidebar/activity-feed/task-new/Task.js
- src/elements/content-sidebar/activity-feed/task-new/Task.scss
- src/elements/content-sidebar/activity-feed/task-new/TaskActions.js
- src/elements/content-sidebar/activity-feed/task-new/TaskCompletionRuleIcon.js
- src/elements/content-sidebar/activity-feed/task-new/TaskCompletionRuleIcon.scss
- src/elements/content-sidebar/activity-feed/task-new/TaskDueDate.js
- src/elements/content-sidebar/activity-feed/task-new/TaskDueDate.scss
- src/elements/content-sidebar/activity-feed/task-new/TaskStatus.js
- src/elements/content-sidebar/activity-feed/task-new/TaskStatus.scss
- src/elements/content-sidebar/activity-feed/task-new/__tests__/Task.test.js
- src/elements/content-sidebar/activity-feed/task-new/__tests__/TaskCompletionRuleIcon.test.js
- src/elements/content-sidebar/activity-feed/task-new/__tests__/TaskDueDate.test.js
- src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/Task.test.js.snap
- src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/TaskDueDate.test.js.snap
- src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/TaskStatus.test.js.snap
- src/elements/content-sidebar/activity-feed/task-new/messages.js
This PR reflects only layout changes made to tasks in preview. 
Will be making changes to the LabelPill component (to adjust the any/all icon and bold text) as well as ReadableTime in a follow up PR to reflect desired design.
Will not be merging this PR until follow up PR's have been made.
Examples of updates:
> feat(tasks): updating task layout in preview

- src/elements/content-sidebar/activity-feed/Avatar.js
- src/elements/content-sidebar/activity-feed/__tests__/Avatar.test.js
this prevents calls to update state when a component has unmounted prior to the promise resolving
> fix(avatar): check for mount status before calling promise

- src/utils/__tests__/Xhr.test.js
The test was able to pass before because of how mocks were created. Change it so that the expectations are checked after handling the error that this function always generates in this condition.
> test(xhr): use `.catch` to handle promise reject in test

- src/utils/__tests__/fields.test.js
- src/utils/fields.js
This PR fixes a bug in which bookmarks in the Content Explorer pointed to blank pages.
> fix(content-explorer): Add URL parameter to folders API call

- .storybook/preview-body.html
- src/elements/content-preview/ContentPreview.js
- src/elements/content-preview/__tests__/ContentPreview.test.js
- src/elements/content-preview/stories/ContentPreview.stories.js
* Add annotations to ContentPreview stories and enable knobs for file id and access_token
* Add a test for injecting boxAnnotations, needed for using the most up to date package of annotations.
* Updated the heights for the existing content preview and sidebar stories
> docs(storybook): add annotations to ContentPreview stories

- src/utils/createTheme.stories.js
fixes theme docs page so you can show the default theme without the createTheme() logic
> docs(theme): allow viewing defaultTheme in docs

- examples/src/SelectableTableExamples.js
- src/components/table/__tests__/makeSelectable.test.js
- src/components/table/makeSelectable.js
The `makeSelectable` function takes a component (let's call it `BaseTable`) and returns another (let's call this one `SelectableTable`.)
`SelectableTable`, under the hood, renders the `BaseTable` and adds selection-related functionality to it. It provides specific functions as props such as `onRowClick` and `onRowFocus` to the `BaseTable` which in turn calls those functions upon the appropriate user actions (i.e. DOM events.)
`SelectableTable` internally manages a `focusIndex` state which determines which item in the list is considered "focused." The `BaseTable` implementation may show a different UI treatment for the focused item.
The problem this change solves is: Once `focusIndex` gets set, it never gets unset. As a result, once a `BaseTable` implementation shows an item as focused, …
> feat(table): Add option for blur detection to selectable tables

- i18n/en-US.properties
- src/features/unified-share-modal/SharedLinkSection.js
- src/features/unified-share-modal/__tests__/SharedLinkSection.test.js
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkSection.test.js.snap
- src/features/unified-share-modal/messages.js
Problem:
The current shared link toggle shows the wrong message when it's
disabled for creation
Fix:
Add new condition to show the create disable message
> fix(usm): handle create disabled shared link toggle tooltip

- src/api/uploads/BaseUpload.js
- src/api/uploads/MultiputUpload.js
- src/api/uploads/PlainUpload.js
- src/api/uploads/__tests__/BaseUpload.test.js
- src/api/uploads/__tests__/MultiputUpload.test.js
- src/api/uploads/__tests__/PlainUpload.test.js
allows for an additional callback to be called on 409 where the client can specify how they want to rename the file they are trying to upload
> feat(uploads): add conflictCallback option

- i18n/en-US.properties
- src/features/classification/flowTypes.js
- src/features/classification/security-controls/SecurityControls.js
- src/features/classification/security-controls/SecurityControlsItem.js
- src/features/classification/security-controls/SecurityControlsModal.js
- src/features/classification/security-controls/__tests__/SecurityControls.test.js
- src/features/classification/security-controls/__tests__/SecurityControlsItem.test.js
- src/features/classification/security-controls/__tests__/SecurityControlsModal.test.js
- src/features/classification/security-controls/__tests__/__snapshots__/SecurityControls.test.js.snap
- src/features/classification/security-controls/__tests__/__snapshots__/SecurityControlsItem.test.js.snap
- src/features/classification/security-controls/__tests__/__snapshots__/SecurityControlsModal.test.js.snap
- src/features/classification/security-controls/__tests__/utils.test.js
- src/features/classification/security-controls/messages.js
- src/features/classification/security-controls/utils.js
This PR adds a tooltip at the end of FULL formatted security controls for application restrictions when the number of apps exceeds maximum. 
The tooltip content displays the list of all applications' names.
> feat(classification): add tooltip to display all applications name list

- i18n/en-US.properties
- src/elements/content-sidebar/ActivitySidebar.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActiveState.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.js
- src/elements/content-sidebar/activity-feed/activity-feed/__tests__/ActiveState.test.js
- src/elements/content-sidebar/activity-feed/activity-feed/__tests__/__snapshots__/ActiveState.test.js.snap
- src/elements/content-sidebar/activity-feed/task-new/Task.js
- src/elements/content-sidebar/activity-feed/task-new/Task.scss
- src/elements/content-sidebar/activity-feed/task-new/TaskActions.js
- src/elements/content-sidebar/activity-feed/task-new/TaskCompletionRuleIcon.scss
- src/elements/content-sidebar/activity-feed/task-new/TaskMultiFileIcon.js
- src/elements/content-sidebar/activity-feed/task-new/__tests__/Task.test.js
- src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/Task.test.js.snap
- src/elements/content-sidebar/activity-feed/task-new/messages.js
Having the "View Task Details" button handler be a function instead of an href allows the consumer (e.g EUA) to route to the URL without causing a page refresh
> feat(content-sidebar): Support multifile tasks

- src/elements/content-explorer/ContentExplorer.js
- src/elements/content-explorer/PreviewDialog.js
Expose `staticPath` and `previewLibraryVersion` props from `ContentExplorer` down to `ContentPreview`
> chore(explorer): expose staticPath and previewLibraryVersion props

- src/utils/__tests__/getFileSize.test.js
- src/utils/getFileSize.js
This causes incorect number format in getFileSize. For example,
123.4 KB should be 123,4 KB when the locale is German.
> fix(getfilesize): locale is not being set to format number

- src/constants.js
This PR enables customers with PDF optimization enabled to view linearized representations of PDFs within the Content Explorer.
> fix(content-explorer): Get PDF reps in initial /folders call

- src/components/select-field/BaseSelectField.js
- src/components/select-field/__tests__/BaseSelectField.test.js
Fixes https://github.com/box/box-ui-elements/issues/1934. This issue is seen on both Mac Firefox & Mac Safari.
Tested fix in Mac Chrome/Safari/Firefox and Windows Edge.
For more info on the inconsistent Firefox & Safari behavior (we're using a div instead of a button in this component, but the same focus rules apply):
https://zellwk.com/blog/inconsistent-button-behavior/
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus
> fix(baseselect): click to close dropdown for safari and firefox

- src/elements/common/annotator-context/__tests__/withAnnotations.test.tsx
- src/elements/common/annotator-context/types.ts
- src/elements/common/annotator-context/withAnnotations.tsx
- src/elements/content-preview/ContentPreview.js
> feat(annotations): reset annotator context when destroying preview

- i18n/en-US.properties
- src/common/types/feed.js
- src/elements/common/annotator-context/AnnotatorContext.ts
- src/elements/common/annotator-context/__tests__/withAnnotations.test.tsx
- src/elements/common/annotator-context/__tests__/withAnnotatorContext.test.tsx
- src/elements/common/annotator-context/types.ts
- src/elements/common/annotator-context/withAnnotations.tsx
- src/elements/common/annotator-context/withAnnotatorContext.tsx
- src/elements/content-preview/ContentPreview.js
- src/elements/content-sidebar/ActivitySidebar.js
- src/elements/content-sidebar/ContentSidebar.js
- src/elements/content-sidebar/Sidebar.js
- src/elements/content-sidebar/SidebarPanels.js
- src/elements/content-sidebar/__tests__/Sidebar.test.js
- src/elements/content-sidebar/__tests__/__snapshots__/ActivitySidebar.test.js.snap
- src/elements/content-sidebar/activity-feed/activity-feed/ActiveState.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.scss
- src/elements/content-sidebar/activity-feed/activity-feed/__tests__/ActiveState.test.js
- src/elements/content-sidebar/activity-feed/activity-feed/__tests__/__snapshots__/ActiveState.test.js.snap
- src/elements/content-sidebar/activity-feed/activity-feed/messages.js
- src/elements/content-sidebar/activity-feed/annotations/AnnotationActivity.js
- src/elements/content-sidebar/activity-feed/annotations/AnnotationActivity.scss
Adding handler to update URL from annotation activity card, and call the callback from contentPreview to handle selecting annotation in Preview
> feat(annotations): update url on annotation selection

- src/features/unified-share-modal/SharedLinkSection.js
- src/features/unified-share-modal/UnifiedShareModal.js
- src/features/unified-share-modal/__tests__/SharedLinkSection.test.js
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkSection.test.js.snap
- src/features/unified-share-modal/__tests__/__snapshots__/UnifiedShareModal.test.js.snap
- src/utils/Browser.js
- src/utils/__tests__/Browser.test.js
by using the two onLoad props on the USM (`createSharedLinkOnLoad` and `focusSharedLinkOnLoad`), enable copying the URL to the clipboard for new and existing shared links.
> feat(usm): add ability to trigger copy to clipboard on modal open

- src/elements/content-sidebar/activity-feed/activity-feed/ActiveState.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.js
- src/elements/content-sidebar/activity-feed/activity-feed/__tests__/ActivityFeed.test.js
Add support for:
-  `AnnotationActivity` being scrolled into view. 
- Add support for `activeEntryId` changing triggering scroll into view logic
> feat(annotation): scroll into view on activeEntryId change

- src/components/form-elements/draft-js-mention-selector/DraftJSMentionSelectorCore.js
- src/components/form-elements/draft-js-mention-selector/__tests__/DraftJSMentionSelectorCore.test.js
- src/components/form-elements/draft-js-mention-selector/__tests__/utils.test.js
- src/components/form-elements/draft-js-mention-selector/index.js
- src/components/form-elements/draft-js-mention-selector/utils.js
I think no new tests are needed cause the original tests have already covered all of the content in utils file.
> feat(draftjs): Extract functions into utils for other libs to reuse

- src/components/select-field/BaseSelectField.js
- src/components/select-field/MultiSelectField.js
- src/components/select-field/MultiSelectField.md
- src/components/select-field/SingleSelectField.js
- src/components/select-field/SingleSelectField.md
- src/components/select-field/__tests__/BaseSelectField.test.js
- src/components/select-field/__tests__/MultiSelectField.test.js
- src/components/select-field/__tests__/SingleSelectField.test.js
- src/components/select-field/constants.js
- Bugfix for BaseSelectField: when a search filter is applied and the user tries to select an item, we should be updating the correct item in the original options array
> fix(select-field): no longer selecting the wrong item

- src/components/select-field/BaseSelectField.js
- src/components/select-field/SelectField.scss
- we should be using a custom selector to target the search container when it is being used inside of SelectField components so that we are not affecting other components on the page that have a SearchForm even though the SearchForm does not live inside the SelectField component
> fix(select-field): use custom selector for SearchForm component

- src/elements/content-preview/ContentPreview.js
- src/elements/content-preview/__tests__/ContentPreview.test.js
- src/elements/content-sidebar/ActivitySidebar.js
- src/elements/content-sidebar/SidebarPanels.js
- src/elements/content-sidebar/__tests__/ActivitySidebar.test.js
- src/elements/content-sidebar/__tests__/SidebarPanels.test.js
- src/elements/content-sidebar/__tests__/__snapshots__/ActivitySidebar.test.js.snap
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.js
- src/elements/content-sidebar/activity-feed/activity-feed/__tests__/ActivityFeed.test.js
This allows partial links to previous file versions from annotation deep links. 
For example:
Selecting an annotation will change the `sb` param to: `/activity/annotations/123/456`
Deselecting the annotation will change the `sb` param to: `/activity/annotations/123`
The same applies to previous file versions.
This will enable another app to control the file versioning via the url 
TODO
> feat(annotations): support partial link to file versions

- i18n/en-US.properties
- src/features/share/__tests__/ShareMenu.test.js
- src/features/share/messages.js
- src/features/shared-link-modal/SharedLinkModal.js
- src/features/shared-link-modal/messages.js
- src/features/shared-link-settings-modal/messages.js
- src/features/unified-share-modal/__tests__/UnifiedShareModal.test.js
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkSection.test.js.snap
- src/features/unified-share-modal/constants.js
- src/features/unified-share-modal/messages.js
- string changes for references to shared links, descriptions, and labels to use shared terminology
> fix(copy): update casing and language for shared links in components

- src/features/virtualized-table/DraggableVirtualizedTable.js
- src/features/virtualized-table/__tests__/DraggableVirtualizedTable.test.js
- src/features/virtualized-table/__tests__/__snapshots__/DraggableVirtualizedTable.test.js.snap
In contrast to the regular `VirtualizedTable`, the new `DraggableVirtualizedTable` component is only meant to be used in circumstances in which all of the rows have been rendered by the time user interaction begins. 
This update will enforce a fixed height relative to the row count so that the `DraggableVirtualizedTable` component is not accidentally used in "scrollable window" mode, which is not supported.
> fix(virtualized-table): Enforce fixed height on draggable table

- src/elements/common/annotator-context/withAnnotations.tsx
- src/elements/content-sidebar/ActivitySidebar.js
- src/elements/content-sidebar/__tests__/ActivitySidebar.test.js
Handles the scenario where preview is direct loaded with a partial deep link to an annotation, i.e. `?sb=/activity/annotations/:fileVersionId` instead of `?sb=/activity/annotations/:fileVersionId/:annotationId`.
This can lead to a bug where clicking on an annotation that is actually on the previous file version will not trigger a file version change because according to the location, we're already on that file version.
In this scenario we will rewrite the url to be the current file version id, so as to maintain the consistency of the `sb` location being the source of truth for which version is being previewed
> feat(annotations): Rewrite deep-linked file version to current

- src/features/collapsible-sidebar/CollapsibleSidebar.stories.js
- src/features/collapsible-sidebar/CollapsibleSidebarMenuItem.js
- src/features/collapsible-sidebar/__tests__/CollapsibleSidebarMenuItem.test.js
Removing text and content from being mutually exclusive. Helps to make use of containers tooltip on overflowing text appropriately
> fix(collapsiblesidebar): Update menu item to take text and content

- src/elements/content-sidebar/ActivitySidebar.js
- src/elements/content-sidebar/DetailsSidebar.js
- src/elements/content-sidebar/MetadataSidebar.js
- src/elements/content-sidebar/SidebarPanels.js
- src/elements/content-sidebar/SkillsSidebar.js
- src/elements/content-sidebar/__tests__/ActivitySidebar.test.js
- src/elements/content-sidebar/__tests__/SidebarPanels.test.js
- src/elements/content-sidebar/versions/VersionsSidebarContainer.js
Since Sidebar unmounts and mounts the individual Sidebar panels when collapsing and expanding, I added knowledge in the `SidebarPanels` to keep track of whether the component has loaded for the first time and pass that as a prop into the individual sidebars.
`ActivitySidebar` can use this knowledge to know whether or not to treat it as a first mount or a remount
> fix(annotations): Avoid path rewrite when ActivitySidebar remounts

- src/components/pill-selector-dropdown/PillSelector.js
- src/components/pill-selector-dropdown/PillSelector.scss
- src/components/pill-selector-dropdown/PillSelectorDropdown.js
- src/components/pill-selector-dropdown/PillSelectorDropdown.stories.js
- src/components/pill-selector-dropdown/RoundPill.js
- src/components/pill-selector-dropdown/RoundPill.scss
- src/components/pill-selector-dropdown/__tests__/PillSelector.test.js
- src/components/pill-selector-dropdown/__tests__/RoundPill.test.js
- src/components/pill-selector-dropdown/flowTypes.js
Storybook updates for rounded pills (non-avatar pills) and imageless avatar pills (with and without external badge). These pills will be used in USM.
Rounded Pills (Non-Avatar Pills) - if `showRoundedPills` is true and `showAvatars` is false
Avatar Pills - if `showRoundedPills` and `showAvatar` is true
Additional pill states appear in order: 
1. error - if prop `isValid` is false. error trumps warning.
2. warning - if prop `hasWarning` is true
3. disabled - if prop `isDisabled` is true. disabled trumps all.
4. selected - if prop `isSelected` is true and `isDisabled` is false. selected trumps errors and warnings.
Rounded Pills (Non-Avatar Pills) Additional States in Pill Selector Dropdown
Avatar Pills Additional States in Pill Selector Dropdown
> feat(pill-selector-dropdown): add new avatar pill for pill selector

- src/components/contact-datalist-item/ContactDatalistItem.js
- src/components/contact-datalist-item/__tests__/ContactDatalistItem.test.js
- src/features/unified-share-modal/ContactsField.js
- src/features/unified-share-modal/EmailForm.js
- src/features/unified-share-modal/UnifiedShareForm.js
- src/features/unified-share-modal/__tests__/ContactsField.test.js
- src/features/unified-share-modal/__tests__/__snapshots__/ContactsField.test.js.snap
- src/features/unified-share-modal/flowTypes.js
allow for specifying a method for retrieving the avatar URL. flexible to support custom schemes or url patterns to tie into other systems, or refer to other assets
> feat(unified-share-modal): support method to get image url for avatars

- src/components/pill-selector-dropdown/PillSelector.js
- src/components/pill-selector-dropdown/PillSelectorDropdown.js
- src/components/pill-selector-dropdown/RoundPill.js
- src/components/pill-selector-dropdown/__tests__/RoundPill.test.js
- src/components/pill-selector-dropdown/__tests__/__snapshots__/RoundPill.test.js.snap
- src/features/unified-share-modal/ContactsField.js
use the existing support for avatar images on round pills, which allows the selected pills to fetch an avatar via URL
> feat(pill-selector-dropdown): add ability to set round pill image urls

- i18n/en-US.properties
- src/common/types/annotations.js
- src/elements/content-preview/ContentPreview.js
- src/elements/content-preview/__tests__/ContentPreview.test.js
- src/elements/content-sidebar/ActivitySidebar.js
- src/elements/content-sidebar/__tests__/ActivitySidebar.test.js
- src/elements/content-sidebar/activity-feed/annotations/AnnotationActivity.js
- src/elements/content-sidebar/activity-feed/annotations/AnnotationActivity.scss
- src/elements/content-sidebar/activity-feed/annotations/AnnotationActivityLink.tsx
- src/elements/content-sidebar/activity-feed/annotations/__tests__/AnnotationActivity.test.js
- src/elements/content-sidebar/activity-feed/annotations/__tests__/__snapshots__/AnnotationActivityLink.test.js.snap
- src/elements/content-sidebar/activity-feed/annotations/messages.js
When a file version is unavailable, disable the activity link button and show a grayed out message `Version Unavailable`
> feat(annotations): Handle file versions unavailable

- src/elements/content-sidebar/__tests__/withSidebarAnnotations.test.js
- src/elements/content-sidebar/withSidebarAnnotations.js
The previous implementation relied on an oddity in the event handling between the Annotations SDK, Preview SDK, and withAnnotations component. The withAnnotations component received/receives events in the following order, with the new behavior being the desired sequence:
```
old: create_pending (add to feed) -> active_change (navigate) -> create_success (refresh sidebar)
new: create_pending (add to feed) -> create_success (refresh sidebar) -> active_change (navigate)
> fix(annotations): Avoid error when adding initial annotation on a file

- src/elements/content-sidebar/activity-feed/annotations/AnnotationActivityLink.tsx
- src/elements/content-sidebar/activity-feed/annotations/__tests__/AnnotationActivityLink.test.js
- src/elements/content-sidebar/activity-feed/annotations/__tests__/__snapshots__/AnnotationActivityLink.test.js.snap
Sorry for the multiple PRs, but I wanted to avoid `onMouseDown` managing the invocation of the `onClick` callback.
> refactor(annotations): Separate mouse event handlers for links

- src/elements/content-preview/ContentPreview.js
- src/elements/content-preview/__tests__/ContentPreview.test.js
The prerequisite of https://github.com/box/box-annotations/pull/542
> feat(preview): Add currentFileVersionId in preview options

- i18n/en-US.properties
- src/features/classification/Classification.js
- src/features/classification/__tests__/Classification.test.js
- src/features/classification/__tests__/__snapshots__/Classification.test.js.snap
- src/features/classification/messages.js
Adds information on when a classification was last updated when it is provided in the props. Also adds a Restrictions label to Security Controls per Product.
> feat(classification): Render classification modified info when provided

- i18n/en-US.properties
- src/features/classification/Classification.js
- src/features/classification/__tests__/__snapshots__/Classification.test.js.snap
- src/features/classification/messages.js
- src/features/classification/security-controls/SecurityControls.js
- src/features/classification/security-controls/__tests__/SecurityControls.test.js
- src/features/classification/security-controls/messages.js
The changes to the Classifications component caused a `Restrictions` label to render even if no restrictions existed. Moved label rendering to the SecurityControls component and use a prop to selectively render it.
> fix(sidebar): Only render restrictions label when items exist

- src/elements/content-explorer/__tests__/ContentExplorer.test.js
- src/features/content-explorer/content-explorer/ContentExplorer.js
- src/features/content-explorer/content-explorer/__tests__/__snapshots__/ContentExplorer.test.js.snap
- src/features/content-explorer/item-list/ItemList.js
- src/features/content-explorer/item-list/__tests__/ItemList.test.js
Adding test ids to key elements in `ContentExplorer` in order to allow matching them in a more robust fashion while running e2e tests.
Updates include:
- Adding test id on main `ContentExplorer` element to allow scoping element searches (e.g., using `.within()` with Cypress(.
- Adding test id to each row item. Items are currently hard to match since the actual inputs are hidden and the clickable element (parent row) is a few levels above and does not have any identifying attributes apart from CSS classes.
> chore(content-explorer): Add test ids for e2e testing

- src/utils/LocalStore.js
This addresses this issue - 
https://stackoverflow.com/questions/30481516/iframe-in-chrome-error-failed-to-read-localstorage-from-window-access-deni
> fix(localstore): handle error with access restriction to local storage

- src/api/Item.js
- src/elements/content-sharing/ContentSharing.js
- src/elements/content-sharing/SharingModal.js
- src/elements/content-sharing/SharingNotification.js
- src/elements/content-sharing/__tests__/SharingModal.test.js
- src/elements/content-sharing/__tests__/useSharedLink.test.js
- src/elements/content-sharing/hooks/useInvites.js
- src/elements/content-sharing/hooks/useSharedLink.js
- src/elements/content-sharing/types.js
- src/features/unified-share-modal/utils/convertData.js
Show loading animations in the ContentSharing Element.
> feat(content-sharing): Add loading states to ContentSharing

- src/common/types/metadata.js
- src/common/types/metadataQueries.js
- src/elements/content-explorer/Content.js
- src/elements/content-explorer/ContentExplorer.js
- src/elements/content-explorer/__tests__/ContentExplorer.test.js
- src/features/metadata-based-view/MetadataBasedItemList.js
- src/features/metadata-based-view/MetadataBasedItemList.scss
- src/features/metadata-based-view/MetadataQueryAPIHelper.js
- src/features/metadata-based-view/__tests__/MetadataBasedItemList.test.js
- src/features/metadata-based-view/__tests__/MetadataQueryAPIHelper.test.js
- src/features/metadata-based-view/__tests__/__snapshots__/MetadataBasedItemList.test.js.snap
This PR handles the change in the `/metadata_queries` API request response change. The new syntax is mentioned here: https://developer.box.com/guides/metadata/quick-start/create-query/
Earlier, developers would pass an array of fields/columns to `<ContentExplorer />` as a prop `metadataColumnsToShow`. Now they can include that piece of info as part of the query syntax (`fields` clause).
> refactor(metadata-view): update metadata queries API interaction

- i18n/en-US.properties
- src/elements/content-sharing/ContentSharing.js
- src/elements/content-sharing/SharingModal.js
- src/elements/content-sharing/SharingNotification.js
- src/elements/content-sharing/__tests__/ContentSharing.test.js
- src/elements/content-sharing/__tests__/SharingModal.test.js
- src/elements/content-sharing/__tests__/useSharedLink.test.js
- src/elements/content-sharing/hooks/useSharedLink.js
- src/elements/content-sharing/messages.js
- src/elements/content-sharing/types.js
Close the USM in ContentSharing after certain actions, mirroring the behavior of the WebApp.
After sending an invitation:
After removing a shared link:
> feat(content-sharing): Close modal after certain actions

- src/elements/content-sharing/ContentSharing.js
- src/elements/content-sharing/SharingModal.js
- src/elements/content-sharing/stories/ContentSharing.stories.js
- src/features/unified-share-modal/SharedLinkSection.js
- src/features/unified-share-modal/UnifiedShareForm.js
- src/features/unified-share-modal/__tests__/SharedLinkSection.test.js
- src/features/unified-share-modal/flowTypes.js
Add a configuration object that hides the email button in the USM.
An example of the ContentSharing UI Element without the email button:
The default USM:
> feat(content-sharing): Add config for email button

- src/components/thumbnail-card/ThumbnailCardDetails.js
- define the type of textRef as an object that has current which may be null or HTMLElement
> fix(thumbnail-card): use different flow typing for textRef

- src/components/thumbnail-card/ThumbnailCardDetails.js
- src/features/collapsible-sidebar/CollapsibleSidebarMenuItem.js
- src/utils/dom.js
- remove typeof undefined from the useIsContentOverflowed method declaration
- update usages in ContentSidebarMenuItem and ThumbnailCardDetails.js
> fix(thumbnail-card): fix flow issue with thumbnailCardDetails

- src/components/thumbnail-card/ThumbnailCardDetails.js
- after many attempts at solutions, we are going to suppress the Flow error that is coming from this component
- we think that the issue may be with Flow because it doesn't make sense that the <div> needs the textRef to be a HTMLDivElement when HTMLElement is a parent of HTMLDivElement
- cleaned up the implementation by reducing the number of lines
> fix(thumbnail-card): suppress flow issue

- src/components/datalist-item/DatalistItem.scss
- src/components/pill-selector-dropdown/PillSelectorDropdown.scss
- src/components/pill-selector-dropdown/_mixins.scss
- src/features/unified-share-modal/UnifiedShareModal.scss
- src/styles/mixins/_overlay.scss
Move the styles used for the new BDL-style overlays to a common area, to be used for other components with overlay behavior.
This change should be a visual no-op; the same styles should be used on the components where originally applied.
> fix(style): move generic BDL overlay styles to shared mixin directory

- src/features/unified-share-modal/SharedLinkSection.js
The email button in the unified shared modal needs an aria-label for accessibility purposes
> fix(unified-share-modal): adding aria-label attribute to email button

- src/elements/wrappers/ContentOpenWith.js
BREAKING CHANGE: if a user passes in onError & onExecute options, those will now replace the equivalent methods on the ES6 wrapper. This is the expected behavior according to the docs, but I'm marking this as a breaking change since its an options update.
The Developer Docs already lists these callbacks as options in https://developer.box.com/guides/embed/ui-elements/open-with/#options
> fix(open-with): fix onError and onExecute callback options

- src/elements/content-sharing/SharingNotification.js
- src/elements/content-sharing/__tests__/SharingModal.test.js
- src/elements/content-sharing/__tests__/SharingNotification.test.js
- src/elements/content-sharing/__tests__/useAvatars.test.js
- src/elements/content-sharing/__tests__/useCollaborators.test.js
- src/elements/content-sharing/__tests__/useContacts.test.js
- src/elements/content-sharing/__tests__/useInvites.test.js
- src/elements/content-sharing/__tests__/useSharedLink.test.js
- src/elements/content-sharing/hooks/useAvatars.js
- src/elements/content-sharing/types.js
- src/features/unified-share-modal/utils/__mocks__/USMMocks.js
- src/features/unified-share-modal/utils/__tests__/convertData.test.js
- src/features/unified-share-modal/utils/convertData.js
Retrieve avatar URLs in the ContentSharing Element.
> feat(content-sharing): Display avatars

- src/elements/content-picker/ItemList.js
Before:
ja-JP
After:
ja-JP
fr-FR
en-US
> fix(content-picker): Fix shared-access width issue

- src/elements/content-uploader/ContentUploader.js
- src/elements/content-uploader/__tests__/ContentUploader.test.js
- src/utils/__tests__/uploads.test.js
- src/utils/uploads.js
Added a check for if an item is a folder before attempting to get the file size to prevent errors when attempting to cancel a single folder upload or multiple folder uploads. 
Additionally, changed the ID assigned when there are not API Options for a DataTransferItem to be identical to that for a File (where only the name is used as the ID when there are not API Options available), so that behavior for folders being uploaded is identical to that of files.
> fix(content-uploader): allow cancellation of folder uploads

- src/elements/content-sharing/ContentSharing.js
Needed for when the element is used via the ES6 wrapper
> fix(content-sharing): add regenerator-runtime to content sharing element

- src/constants.js
- src/elements/content-sharing/types.js
- src/features/unified-share-modal/utils/__tests__/convertData.test.js
- src/features/unified-share-modal/utils/convertData.js
This PR updates the disabled reasons field name **allowed_shared_link_access_levels_disabled_reasons**, in accordance with the API.
> fix(content-sharing): Update disabled reasons field name

- scripts/webpack.config.js
This PR addresses following issue:
https://github.com/zloirock/core-js/issues/514
Before:
Here is the exception you see in IE11 with the current combination of webpack 4.x, babel-core 7.x and core-js 3.x
After
No exception and the react-styleguidist page loads and works as expected.
> build(ie11): Exclude core-js module from babel loader

- src/elements/content-sharing/SharingModal.js
- src/features/collaborator-avatars/CollaboratorList.js
- src/features/collaborator-avatars/__tests__/__snapshots__/CollaboratorList.test.js.snap
- src/features/shared-link-settings-modal/AllowDownloadSection.js
- src/features/shared-link-settings-modal/AllowDownloadSection.scss
- src/features/shared-link-settings-modal/ExpirationSection.js
- src/features/shared-link-settings-modal/PasswordSection.js
- src/features/shared-link-settings-modal/SharedLinkSettingsModal.js
- src/features/shared-link-settings-modal/VanityNameSection.js
- src/features/unified-share-modal/InviteePermissionsMenu.js
- src/features/unified-share-modal/RemoveLinkConfirmModal.js
- src/features/unified-share-modal/SharedLinkSection.js
- src/features/unified-share-modal/UnifiedShareForm.js
- src/features/unified-share-modal/UnifiedShareModal.js
- src/features/unified-share-modal/UnifiedShareModal.scss
- src/features/unified-share-modal/__tests__/__snapshots__/InviteePermissionsMenu.test.js.snap
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkSection.test.js.snap
- src/features/unified-share-modal/__tests__/__snapshots__/UnifiedShareModal.test.js.snap
- test/sharing-no-react.html
- test/sharing.html
Box styling was missing or being overridden when using the element on a standalone page
> fix(content-sharing): style issues when using element via ES6 wrapper

- src/elements/content-sharing/ContentSharing.js
- src/elements/content-sharing/SharingModal.js
- src/elements/content-sharing/__tests__/ContentSharing.test.js
- src/elements/content-sharing/__tests__/SharingModal.test.js
This PR fixes a bug in which the Content Sharing Element could only be opened once via a custom button. The top-level component (`ContentSharing`) now unmounts the secondary component (`SharingModal`) when the X button is closed and then reinstantiates it when the custom button is clicked again.
> fix(content-sharing): Enable reinstantiation via a custom button

- src/features/shared-link-settings-modal/AllowDownloadSection.scss
- src/features/unified-share-modal/UnifiedShareModal.scss
- src/styles/mixins/_buttons.scss
Fixes:
- "Dancing" manage all button on collaborators page when hovered
- Rounded corners on right side of text portion of text w/ copy button components
- Collaborator avatars too close to invite textbox
Standalone -
EUA -
> fix(content-sharing): Small styling issues with standalone element

- i18n/en-US.properties
- src/constants.js
- src/elements/common/messages.js
- src/elements/content-uploader/ContentUploader.js
- src/elements/content-uploader/__tests__/ContentUploader.test.js
- src/elements/content-uploader/progressCellRenderer.js
- src/utils/Browser.js
- src/utils/__tests__/Browser.test.js
- src/utils/__tests__/uploads.test.js
- src/utils/uploads.js
This change allows the upload manager to properly identify it has received a [package file](https://en.wikipedia.org/wiki/Package_(macOS)), and attempt to upload it. 
In Safari, this will fail predictably, so we allow detection of the error type, and show a specific error message detailing the issue with a workaround.
> fix(upload): add support for detecting and handling package files

- src/constants.js
- src/elements/content-sharing/SharingModal.js
- src/elements/content-sharing/SharingNotification.js
- src/elements/content-sharing/__tests__/SharingModal.test.js
- src/elements/content-sharing/__tests__/SharingNotification.test.js
- src/elements/content-sharing/types.js
- src/features/unified-share-modal/constants.js
- src/features/unified-share-modal/utils/__tests__/convertData.test.js
- src/features/unified-share-modal/utils/convertData.js
- src/utils/__tests__/file.test.js
- src/utils/file.js
SFC collabs should only be shown viewer and editor permissions, and G Suite files should never have the can download shared link permission available
> fix(content-sharing): limit collab and link permissions

- src/elements/content-sharing/ContentSharing.js
- src/elements/content-sharing/__tests__/ContentSharing.test.js
- src/elements/wrappers/ContentSharing.js
Enable the ContentSharing ES6 wrapper to refresh (and thus reopen) the ContentSharing React component by passing a new `uuid` property whenever the wrapper calls `ReactDOM.render()`.
> fix(content-sharing): Refresh component from ES6 wrapper

- src/elements/content-sharing/ContentSharing.js
- src/elements/content-sharing/SharingModal.js
- src/elements/content-sharing/__tests__/SharingModal.test.js
Show error notifications when initial data API calls fail. These notifications replace the `ErrorMask`, which previously took up the entire page.
> fix(content-sharing): Show notifications for initial data calls

- src/elements/content-sidebar/activity-feed/annotations/AnnotationActivity.js
- src/elements/content-sidebar/activity-feed/annotations/__tests__/AnnotationActivity.test.js
- src/elements/content-sidebar/activity-feed/comment-form/CommentForm.js
The issue is that before when we clicked on the Modify button, the form input would show up but the Cancel / Post buttons would not show up until the user clicks to focus the input field.
The correct UX is that when the user clicks on the Modify button, we should immediately see the Cancel / Post buttons.
> fix(annotations): use correct value for isOpen prop

- i18n/en-US.properties
- src/components/pill-selector-dropdown/RoundPill.js
- src/components/pill-selector-dropdown/RoundPill.scss
- src/components/pill-selector-dropdown/__tests__/__snapshots__/RoundPill.test.js.snap
- src/features/unified-share-modal/ContactRestrictionNotice.js
- src/features/unified-share-modal/ContactRestrictionNotice.scss
- src/features/unified-share-modal/ContactsEmailsTooltip.js
- src/features/unified-share-modal/ContactsEmailsTooltip.scss
- src/features/unified-share-modal/EmailForm.js
- src/features/unified-share-modal/__tests__/ContactRestrictionNotice.test.js
- src/features/unified-share-modal/__tests__/ContactsEmailsTooltip.test.js
- src/features/unified-share-modal/__tests__/EmailForm.test.js
- src/features/unified-share-modal/__tests__/__snapshots__/ContactsEmailsTooltip.test.js.snap
- src/features/unified-share-modal/__tests__/__snapshots__/EmailForm.test.js.snap
- src/features/unified-share-modal/messages.js
Partial update that adds the UI components needed for the new Business Justifications flow for external collab restrictions. The components have been integrated with `EmailForm`, but the `UnifiedShareForm` updates needed to integrate with the apis and EUA are still pending. 
**Note:** There is also some pending UI polish that will be handled separately. The updates will not yet be visible and should be backwards compatible.
**After submitting with restricted external collabs:**
**Restricted collabs email tooltip:**
**Submitting without selecting justification:**
(Note: Tooltip margin needs to be fixed)
**After justification reason is selected:**
> feat(usm): Adding UI for business justifications

- src/api/Feed.js
- src/elements/content-sidebar/activity-feed/annotations/AnnotationActivityMenu.js
- src/elements/content-sidebar/activity-feed/annotations/__tests__/AnnotationActivity.test.js
- src/elements/content-sidebar/activity-feed/annotations/__tests__/AnnotationActivityMenu.test.js
- add flag to hide Modify menu item
- revert update comment UX
> fix(annotations): disable modify menu item

- scripts/commitlint.sh
Fixes an issue where CircleCI does not set the `CIRCLE_PR_NUMBER` env variable correctly. This is very apparent on `dependabot` commits
> ci: Fix CircleCI issue with missing PR Number

- src/elements/content-sidebar/activity-feed/annotations/AnnotationActivityMenu.js
> fix(annotations): use correct pencil icon

- i18n/en-US.properties
- src/features/unified-share-modal/ContactRestrictionNotice.js
- src/features/unified-share-modal/ContactRestrictionNotice.scss
- src/features/unified-share-modal/EmailForm.js
- src/features/unified-share-modal/UnifiedShareForm.js
- src/features/unified-share-modal/__tests__/ContactRestrictionNotice.test.js
- src/features/unified-share-modal/__tests__/EmailForm.test.js
- src/features/unified-share-modal/__tests__/UnifiedShareForm.test.js
- src/features/unified-share-modal/__tests__/__snapshots__/UnifiedShareForm.test.js.snap
- src/features/unified-share-modal/messages.js
Partial update that adds and integrates the UI for the new external collab restriction flow. Previously it was possible to submit non-restricted invitees along with invitees restricted by an Access Policy (unrestricted invites would succeed, but a red error banner would be shown for restricted ones). Once the new flow is enabled, it will no longer be possible to submit the form with restricted invitees, and the user will be asked to remove them.
Changes should be backwards compatible and the new flow will not yet be enabled.
Additionally, this PR also switches the messages from `FormattedCompMessage` to `FormattedMessage`, given that currently there are some unresolved issues with `FormattedCompMessage` that prevent us from using it. Note that the design had to be altered a bit in order …
> feat(usm): Adding new external collab restriction flow

- src/components/form-elements/draft-js-mention-selector/DraftJSMentionSelectorCore.js
**Issue:**
In the current experience, when the user starts typing '@' into the CommentForm, the empty search state does not show up. This is because in `componentDidUpdate`, we are performing an incorrect check of `prevContacts !== currentContacts`. 
Since prevContacts and currentContacts are two different variables, this will always result in true.
**Solution:**
The solution is to instead compare the lengths of the two variables to see if the if condition is satisfied.
**Demo:**
> fix(comment-form): use length check

- src/elements/content-sidebar/activity-feed/annotations/AnnotationActivityMenu.js
- src/elements/content-sidebar/activity-feed/annotations/__tests__/AnnotationActivity.test.js
- src/elements/content-sidebar/activity-feed/annotations/__tests__/AnnotationActivityMenu.test.js
> chore(annotations): remove modify annotation feature flip logic

- src/features/unified-share-modal/ContactRestrictionNotice.js
- src/features/unified-share-modal/ContactRestrictionNotice.scss
Text was overlapping in cases in which the remove button fit within the last line of the paragraph and justifications were disabled.
**Before:**
**After:**
> fix(usm): Fix line overlap on ContactRestrictionNotice

- i18n/en-US.properties
- src/features/classification/security-controls/__tests__/utils.test.js
- src/features/classification/security-controls/messages.js
- src/features/classification/security-controls/utils.js
Updating the copy for app restrictions in which all app downloads are blocked.
Note: Translations for the new copy are already available.
> feat(security-controls): Update app restriction copy

- src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.scss
**Main Issue:**
There was an intermittent bug found in IE11 where when the user deletes a comment in the activity sidebar, sometimes the comments in the sidebar would get truncated.
**Solution:**
The fix is to move the `width: 100%` style on the `.bcs-activity-feed-active-state` element to the parent element.
**Demo:**
> fix(activity): annotation activity width truncation after deletion

- src/icon/line/Key16.js.flow
- src/icon/line/Key16.stories.tsx
- src/icon/line/Key16.tsx
Adding Key icon asset from `design-assets`
> feat(assets): Add Key icon asset

- src/features/collapsible-sidebar/CollapsibleSidebar.stories.js
- src/features/collapsible-sidebar/CollapsibleSidebar.stories.md
- src/features/collapsible-sidebar/CollapsibleSidebarNav.js
- src/features/collapsible-sidebar/__tests__/CollapsibleSidebarNav.test.js
- src/features/collapsible-sidebar/__tests__/__snapshots__/CollapsibleSidebarNav.test.js.snap
- CollapsibleSidebar was not intended to support horizontal scroll
and allowing it can cause issues. Adds `noScrollX` prop
to the custom scrollbar library to prevent it.
- Also adds `customScrollBarProps` to allow consumers to add/change
props to the `react-custom-scrollbars` package. (Custom props
should be used sparingly to avoid coupling with 3rd party API
instead of the internal defaults).
- https://github.com/xobotyi/react-scrollbars-custom#props
> fix(collapsible-sidebar): prevent h-scrollbar from appearing

- src/utils/Browser.js
- src/utils/__tests__/Browser.test.js
- src/utils/__tests__/uploads.test.js
- src/utils/uploads.js
Multiput uploads is not supported on Mobile Safari, and instead will use Plain Upload for all file sizes. This is due to a WebkitBlobResourceError when blob urls are attempted to be read to upload file data. The blob urls are created internally by the browser.
> fix(uploads): update multiput support for mobile safari

- src/styles/common/_buttons.scss
white buttons doesn't compliant a11y standards, so we have to add a visual indicator for focus states.
- Adds border color that fulfill 3:1 contrast
- white buttons focus state now is a11y compliant
> fix(button): tweak white-buttons with poor focus states

- src/utils/__tests__/uploads.test.js
- src/utils/uploads.js
File uploads on mobile chrome on ios will use Plain Uploads and no longer support multiput uploads.
> fix(uploads): update multiput support for mobile chrome ios

- src/elements/content-preview/ContentPreview.js
Pass PreviewExperiences From ContentPreview Component to Preview Options that will be used by Content Preview
> feat(preview/tooltip): pass preview experiences to preview

- src/elements/common/item/ItemSubDetails.scss
In the Content Picker, the modified-by user tag and the item size tag sit right next to each other, without any spacing. This PR fixes this bug by reusing styles from the Content Explorer in the Content Picker. There are no changes to the Content Explorer.
**Before:**
**After:**
> fix(content-picker): Add spacing between user and size tags

- src/components/tooltip/Tooltip.js.flow
- src/components/tooltip/Tooltip.tsx
- src/components/tooltip/__tests__/Tooltip.test.tsx
- src/components/tooltip/__tests__/__snapshots__/Tooltip.test.tsx.snap
- Add the ability to add a specific class to the tether element. We don't necessarily want to target all .tooltip-element classes. My use case changing z-index:
before:
after (with class):
> feat(tooltip): add classname to tether element component

- src/components/pill-selector-dropdown/PillSelector.js
- src/components/pill-selector-dropdown/__tests__/__snapshots__/PillSelector.test.js.snap
fix(CreateNewFolder): [A11Y]- Add aria described by pilled selector
Error Messages are provided but not in an accesible way in Pill selector component (Create New Folder Form). Screen reader users get no indication of the error.  I added a missing `aria-describedby` attribute in the `textarea` to be read when a form validation occurs. `Aria-invalid` (exists in Tooltips component) and `aria-describedby` are used together to indicate an error when any field are not in the expected format.
> fix(CreateNewFolder): [A11Y]- Add aria described by pilled selector

- src/components/flyout/Flyout.js
- src/constants.js
Hey guys! The Flyouts button can't be used while navigating on keyboard, so we had to make some adjustments in order to be  focusable and activated with the Enter key.
> fix(flyouts): made flyout button keyboard accessible

- src/components/tab-view/TabViewPrimitive.js
- src/components/tab-view/__tests__/TabViewPrimitive.test.js
fix(AccountSettings): A11Y- incorrect use of nav tag in TabviewPrimitive
Page regions such as `<header>, <nav>, <main>, <aside>, and <footer>` programmatically define the essential semantic structure of a page. The `<nav>` region should usually be applied only to the primary navigation, for this reason I changed the nav tag for a div tag.
> fix(AccountSettings): A11Y- incorrect use of nav tag in TabviewPrimitive

- src/components/tooltip/Tooltip.tsx
- src/components/tooltip/__tests__/Tooltip.test.tsx
- src/components/tooltip/__tests__/__snapshots__/Tooltip.test.tsx.snap
add optional prop `shouldTooltipShowAferUserClose` to `Tooltip.tsx`
add logic to allow for the tooltip to be opened again if it was closed by the user for restarting onboarding experiences multiple times
> fix(tooltip): Modify tooltip to allow rerender after closed by user

- i18n/en-US.properties
- src/components/toggle/Toggle.js
- src/components/toggle/__tests__/__snapshots__/ToggleField.test.js.snap
- src/features/unified-share-modal/SharedLinkSection.js
- src/features/unified-share-modal/UnifiedShareForm.js
- src/features/unified-share-modal/__tests__/UnifiedShareForm.test.js
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkSection.test.js.snap
fix(Toggle): A11Y - When shared link does not exist maintain focus on the switch
When the sharing option has been deactivated and `Create shared link` is triggered, the form changes and focus is set to the read-only textbox that contains the URL. This skips over the `Link Settings` option, meaning a screen reader user will not know that this option is available. Instead of setting focus to the URL, maintain focus on the switch.
> fix(Toggle): A11Y - When shared link does not exist maintain focus on the switch

- src/elements/common/header/Header.js
- src/elements/content-picker/ContentPicker.js
- src/elements/content-picker/README.md
> feat(content-picker): pass flag to hide logo in ContentPicker

- src/features/in-app-messenger/contextual/templates/PreviewTitleBodyTwoButtonsModalTemplate.js
- src/features/in-app-messenger/contextual/templates/PreviewTitleBodyTwoButtonsPopoutTemplate.js
- src/features/in-app-messenger/contextual/templates/__tests__/PreviewTitleBodyTwoButtonsModalTemplate.test.js
- src/features/in-app-messenger/contextual/templates/styles/PreviewTitleBodyTwoButtonsModalTemplate.scss
- src/features/in-app-messenger/types/index.js
- src/features/in-app-messenger/types/template-params.js
Add new template for in-app messenger leveraging preview component
> feat(in-app-messenger): add new template for modal

- src/elements/content-sidebar/SidebarSection.js
In the tab panel, the"Access States" and "File Properties" buttons should have aria-expanded. I just added this aria attribute in `SidebarSection`  component.
> fix(SidebarSection): A11Y - add aria-expanded in sidebar section component

- src/elements/content-picker/ContentPicker.js
- src/elements/content-picker/README.md
> feat(content-picker): add flag for hiding pagination buttons

- src/elements/content-sidebar/activity-feed/comment-form/CommentForm.scss
The grey (#09090) "@mention users to notify them" text presents an insufficient contrast ratio of 3.2:1 with the white background
The fix should change the color to #767676:
> fix(commentform): A11Y - color contrast correction

- src/icons/general/IconEdit.tsx
- src/icons/general/__tests__/__snapshots__/IconEdit.test.tsx.snap
The edit icon on the Metadata section used to have a #999 fill color, which does not meet the minimum contrast requirement over white background. 
Color had to be changed to #767676 in order to meet minimum contrast required.
> fix(metadata): improved color contrast on edit icon button

- src/components/date-picker/DatePicker.scss
The cancel button on the date picker used to have a #a7a7a7 fill color which has low contrast.
It has been adjusted to #909090 to improve the contrast ratio
> fix(datepicker): improving color contrast

- src/components/draft-js-editor/DraftJSEditor.scss
placeholder text had insufficient contrast color
Before
After
> fix(draftjs): Tweak contrast color

- package.json
- src/styles/colors.stories.tsx
- yarn.lock
- Show WCAG contrast ratio (against white) next to colors, to make it easier to pick accessible color combinations
- Slightly more compact and responsive layout for the palette documentation
Wide:
Narrow:
> docs(colors): show contrast ratios

- i18n/en-US.properties
- src/components/draft-js-editor/DraftJSEditor.js
- src/components/draft-js-editor/DraftJSEditor.stories.js
- src/components/draft-js-editor/__tests__/DraftJSEditor.test.js
- src/components/form-elements/draft-js-mention-selector/DraftJSMentionSelector.js
- src/components/form-elements/draft-js-mention-selector/DraftJSMentionSelectorCore.js
- src/elements/content-sidebar/activity-feed/comment-form/CommentForm.js
- src/elements/content-sidebar/activity-feed/comment-form/messages.js
Adds verbose description for screenReader users, explaining how to use the draftJS **mention** feature
> fix(draftjs): Adds description for screenReader users

- src/features/presence/PresenceAvatarList.tsx
- src/features/presence/__tests__/PresenceAvatarList.test.tsx
Adds prop to hide the additional collaborator count when it exceeds `maxDisplayedAvatars`
> feat(presence): Hide additional collaborator count

- i18n/en-US.properties
- src/elements/content-sidebar/additional-tabs/__tests__/__snapshots__/AdditionalTab.test.js.snap
- src/elements/content-sidebar/additional-tabs/messages.js
This is part of an update to unify tooltip wording for various shield restrictions.
The old tooptip:
The new tooltip:
> fix: update shield tooltip wording

- i18n/en-US.properties
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkAccessMenu.test.js.snap
- src/features/unified-share-modal/messages.js
This is part of a series of changes to unify tooltip wording for shield access restrictions.
The old tooltip:
The new tooltip:
> fix: tooltip text for shield access restriction

- src/constants.js
Fixes an issue in Content Explorer where previewing large .txt files would remain stuck in a loading state, due to the pending status of their pdf representations. Now we're fetching the text representation, which is the expected representation for .txt files. I tested for any regressions in Content Explorer by previewing all supported file types.
Before:
After:
> fix(content-explorer): Get text reps in initial /folders call

- src/components/badge/Badge.scss
Improved color contrast for the pills text since it failed to be compliant with Accessibility standards.
> fix(pills): improved color contrast for accessibility

- src/components/badge/Badge.scss
- src/components/draft-js-editor/DraftJSEditor.js
- src/components/draft-js-editor/__tests__/DraftJSEditor.test.js
According to the communication held with WebAim, the role combobox had to be switched to textbox and the aria-multiline attribute had to be added.
> fix(comments): Added Aria attributes to enhance accessibility

- src/components/checkbox/Checkbox.tsx
To test this we should be located in AccountSettings > Sharing:
Email Notifications:
Checkbox render a Label element. It should be not rendered in case label text is not setted.
> fix(checkbox): render label in case text exist

- i18n/en-US.properties
- src/features/unified-share-modal/SharedLinkPermissionMenu.js
- src/features/unified-share-modal/SharedLinkSection.js
- src/features/unified-share-modal/UnifiedShareForm.js
- src/features/unified-share-modal/UnifiedShareModal.js
- src/features/unified-share-modal/__tests__/SharedLinkPermissionMenu.test.js
- src/features/unified-share-modal/__tests__/SharedLinkSection.test.js
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkPermissionMenu.test.js.snap
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkSection.test.js.snap
- src/features/unified-share-modal/__tests__/__snapshots__/UnifiedShareModal.test.js.snap
- src/features/unified-share-modal/constants.js
- src/features/unified-share-modal/flowTypes.js
- src/features/unified-share-modal/messages.js
> feat(shared-link-permission-menu): add edit option

- i18n/en-US.properties
- src/features/unified-share-modal/SharedLinkSection.js
- src/features/unified-share-modal/__tests__/SharedLinkSection.test.js
- src/features/unified-share-modal/messages.js
> feat(shared-link-section): add warning copy

- src/components/date-picker/_pikaday.scss
Fixes opacity for disabled arrows in DatePicker for IE11 & Edge.
IE11 & Edge Before:
- Next & previous arrows are disabled from clicking, but visibly appear enabled. (Screenshot is of IE11; Edge is identical)
IE11 & Edge After:
- Next & previous disabled arrows now match opacity of other browsers. (Screenshot is of IE11; Edge is identical)
Verified that there is no change for:
> fix(datepicker): Fix opacity for disabled arrows in IE11 and Edge

- i18n/en-US.properties
- src/components/label-pill/LabelPill.scss
- src/components/label-pill/LabelPill.stories.tsx
- src/components/label-pill/LabelPill.tsx
- src/features/unified-share-modal/SharedLinkPermissionMenu.js
- src/features/unified-share-modal/SharedLinkPermissionMenu.scss
- src/features/unified-share-modal/SharedLinkSection.js
- src/features/unified-share-modal/UnifiedShareForm.js
- src/features/unified-share-modal/UnifiedShareModal.js
- src/features/unified-share-modal/__tests__/SharedLinkPermissionMenu.test.js
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkPermissionMenu.test.js.snap
- src/features/unified-share-modal/flowTypes.js
- src/features/unified-share-modal/messages.js
> feat(shared-link-permission-menu): add ftux for shared link permission menu

- src/styles/common/_buttons.scss
Buttons didn't receive proper focus behaviour, and looked
In order to highlight correctly I used the hover behavior so the focus outline is noticeable
> fix(buttons): highlighting button properly on focus

- i18n/en-US.properties
- src/features/unified-share-modal/SharedLinkSection.js
- src/features/unified-share-modal/UnifiedShareForm.js
- src/features/unified-share-modal/UnifiedShareModal.js
- src/features/unified-share-modal/__tests__/SharedLinkSection.test.js
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkSection.test.js.snap
- src/features/unified-share-modal/flowTypes.js
- src/features/unified-share-modal/messages.js
> feat(shared-link-section): add tooltip ftux

- src/components/select-field/BaseSelectField.js
- src/components/select-field/__tests__/BaseSelectField.test.js
- src/components/select-field/__tests__/__snapshots__/BaseSelectField.test.js.snap
Select Buttons used to have a combobox role 
But according to WebAIM in order to be compliant with accessibility, the right role for the buttons is Listbox. So we updated the role accordingly :D
> fix(metadata): added correct role for select button

- src/elements/content-sidebar/versions/VersionsGroup.js
Currently, the time stamp heading is marked up with a H1 tag, which is semantically wrong (since there's one already)
This has been fixed and now its marked up with the H4 tag.
> fix(headings): fixed headings hierarchy on version history

- src/elements/content-sidebar/versions/VersionsItemButton.scss
Currently, the version history uses #767676 for the modified date text, which has no contrast issues on white background, but the selected state, has a light blue BG (#F5FAFD) and the contrast ratio is not enough.
So, for the selected class, the text is now #222 and the contrast ratio is now fixed.
Before:
After:
> fix(versions): improved contrast on highlighted version button

- src/elements/content-sidebar/versions/VersionsGroup.scss
> fix(versionhistory): change minimum contrast color

- src/features/metadata-instance-editor/Instance.js
- src/features/metadata-instance-editor/__tests__/Instance.test.js
- src/features/metadata-instance-editor/__tests__/__snapshots__/Instance.test.js.snap
The edit button should have an attribute aria-label instead an attribute area-describedby.
And the value of aria-label should be the same as the Tooltip which is wrapping the button.
> fix(metadata): add ariaLabel to button

- src/elements/common/logger/Logger.js
- src/elements/common/logger/__tests__/Logger.test.js
- src/elements/common/logger/__tests__/__snapshots__/Logger.test.js.snap
- src/elements/common/logger/constants.js
- src/elements/content-sidebar/ActivitySidebar.js
- src/elements/content-sidebar/__tests__/ActivitySidebar.test.js
Introduces instrumentation to measure the time taken to load the data needed for a sidebar in the `ContentSidebar`. In this case, the PR is applying this instrumentation to the `ActivitySidebar` to measure the time taken to load the initial feed items from component mount time to `Feed` api returning successfully.
Subsequent data fetch times are not logged as a metric.
> feat(contentsidebar): Add instrumentation for data load time

- src/components/date-picker/DatePicker.stories.tsx
- src/components/date-picker/DatePicker.tsx
- src/components/date-picker/__tests__/DatePicker.test.tsx
- src/elements/content-sidebar/activity-feed/task-form/TaskForm.js
- Optional prop `isKeyboardInputAllowed` allows keyboard inputs to fall back to the default pikaday behavior, which means users can use keyboard arrow keys to navigate through the calendar popup.
- Adds isKeyboardInputAllowed prop to TaskForm for accessibility purposes
- Tested all DatePicker storybooks with & without isKeyboardInputAllowed to check for regressions
- Tested TaskForm change in:
> feat(datepicker): Option to enable pikaday's default keyboard input

- src/components/collapsible/Collapsible.tsx
- src/components/collapsible/__tests__/__snapshots__/Collapsible.test.tsx.snap
Hi guys! 
One of the current issues we have is that some collapsible buttons doesn't give enough information to the users while they are being expanded or not.
Added the aria-expanded attribute so screen readers can inform the users while the buttons are open or not
> fix(metadata): added aria-expanded to collapsible buttons

- src/features/unified-share-modal/SharedLinkSection.js
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkSection.test.js.snap
> fix(shared-link-section): fix reposition esl ftux tooltip

- src/elements/content-sidebar/activity-feed/version/Version.scss
- src/features/metadata-instance-editor/Instance.js
- src/features/metadata-instance-editor/__tests__/__snapshots__/Instance.test.js.snap
In order to improve accessibility, the Edit metadata button required some tweaking to inform the SR users that is in use
The aria-pressed attribute helps telling users the button they are interacting with
> fix(metadata): added aria-pressed to edit metadata button

- src/features/content-explorer/content-explorer/ContentExplorer.js
- src/features/content-explorer/content-explorer/__tests__/ContentExplorer.test.js
Adds guard clause to handleItemNameClick if item is disabled. Similar to the other click handlers above (handleItemDoubleClick and handleItemClick).
It seems to me the the existence of this guard clause in handleItemDoubleClick implies that we should not be able to enter a folder if it is disabled. https://github.com/box/box-ui-elements/blob/master/src/features/content-explorer/content-explorer/ContentExplorer.js#L296-L304
Also open to separating this into a separate prop to disable navigation on click.
> fix(content-explorer): disable item name click if item disabled

- src/elements/content-sharing/SharingNotification.js
- src/features/unified-share-modal/flowTypes.js
- src/features/unified-share-modal/stories/UnifiedShareModal.stories.js
- src/features/unified-share-modal/utils/__mocks__/USMMocks.js
- src/features/unified-share-modal/utils/__tests__/convertData.test.js
- src/features/unified-share-modal/utils/convertData.js
Filter out users and groups who has already collaborated on the file when sending requests.
> fix(unified-share-modal): filter out collaborated users and groups

- src/components/notification/Notification.js
- src/components/notification/Notification.scss
- src/components/notification/__tests__/Notification.test.js
Alerts color contrast has been improved as the general look, proper image preview is below:
> fix(alerts): alerts color contrast

- src/components/date-picker/AccessiblePikaday.ts
- src/components/date-picker/DatePicker.scss
- src/components/date-picker/DatePicker.tsx
- Keeps the calendar closed while user is typing, to account for controlled use cases
- Only the calendar icon button will open & close the calendar popout
- Also fixes input width which led to overlapped icons
Before
After
> fix(datepicker): Toggle calendar with button only in accessible mode

- src/components/tooltip/Tooltip.tsx
- src/components/tooltip/__tests__/__snapshots__/Tooltip.test.tsx.snap
These changes should get us more aligned with the recommended approach of having the tooltip persist when the user is hovered over it. Sample of a desired path forward: https://dequeuniversity.com/library/aria/tooltip
https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus
> fix(tooltips): support hover state for WCAG 1.4.13

- src/elements/content-sidebar/activity-feed/common/delete-confirmation/DeleteConfirmation.scss
Bug fix for incorrect vertical stacking of the delete and cancel buttons on the confirmation modal that pops up when the user tries to delete a comment. Now the buttons are aligned horizontally.
**Example of Fix on Chrome:**
**Example of Fix on IE11:**
Fix on IE11
> fix(activity-sidebar): delete and cancel button misalignment

- src/components/date-picker/AccessiblePikaday.ts
- src/components/date-picker/DatePicker.tsx
- src/elements/content-sidebar/activity-feed/task-form/TaskForm.js
- The handleBlur method works in IE11 but at the moment will never be called in IE11
- Prevents Chrome from opening native datepicker on spacebar
- Validates month and day ranges for the fallback pattern in text inputs
> fix(datepicker): Updates from PR comments

- src/components/date-picker/DatePicker.tsx
The `toISOString()` method converts the date to UTC (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString).
This adds a local timezone offset to the ISO string so that the date section is properly associated with the local time.
This was tested in Chrome, Firefox, and Safari and using system settings to mock different timezones.
> fix(datepicker): Add local timezone offset to display date

- src/components/date-picker/DatePicker.tsx
When `dateFormat` is `DateFormat.UTC_TIME_DATE_FORMAT`, the date value is converted from being relative to UTC to relative to local time.
The input element is not updated to reflect the converted date, so the date value on initial rendering is wrong.
This change updates the form state after conversion which re-renders the input value with the correct date.
Before (initial render)
After (initial render)
> fix(datepicker): Update input value after date is converted

- src/components/image-tooltip/ImageTooltip.tsx
I noticed ImageTooltip component did not pass className property.
Instead of provided value component render 'className' string. 
Change has been tested and providing expected result.
> fix: Fix className property passed to ImageTooltip component

- i18n/en-US.properties
- src/features/unified-share-modal/UnifiedShareForm.js
- src/features/unified-share-modal/__tests__/UnifiedShareForm.test.js
- src/features/unified-share-modal/messages.js
> fix: fix collaborator access message copy for international translations

- i18n/en-US.properties
- src/components/date-picker/DatePicker.tsx
When a date is entered via keyboard and `isAccessible` is enabled with a min and/or max date, the user is potentially blocked from entering valid inputs.
For example, if the min date is set to 01/01/2020 and the user attempts to enter 01/01/2022, the user will be blocked from entering the year because DatePicker will calculate 01/01/0002 as an invalid year and will immediately reset the input to the min date.
The following changes occur when entering invalid input:
- The date input does not reset to the min/max date
- An alert icon appears on input change with an invalid date
- A tooltip error shows on input blur with an invalid date
**Before (Typing 2022)**
**After (Typing 2022)**
**After (Tooltip on Blur Event)**
> fix(datepicker): Add error styling for invalid date inputs

- src/icons/google-docs/IconGoogle.js.flow
- src/icons/google-docs/IconGoogle.tsx
- src/icons/google-docs/__tests__/IconGoogle.test.tsx
- src/icons/microsoft-office/IconOffice.js.flow
- src/icons/microsoft-office/IconOffice.tsx
- src/icons/microsoft-office/__tests__/IconOffice.test.tsx
Add Google and Microsoft Office generic icons:
> feat(icons): add Google and Microsoft Office icons

- i18n/en-US.properties
- src/features/classification/constants.js
- src/features/classification/flowTypes.js
- src/features/classification/security-controls/SecurityControls.js
- src/features/classification/security-controls/__tests__/utils.test.js
- src/features/classification/security-controls/messages.js
- src/features/classification/security-controls/utils.js
> feat(classification): add watermarking to security controls)

- src/components/date-picker/AccessiblePikaday.ts
- src/components/date-picker/DatePicker.tsx
This sets the focus to the date input when the calendar widget closes except when focus is already on a tabbable/focusable element.
> fix(datepicker): Focus input field when calendar closes

- src/elements/content-sidebar/Sidebar.js
I create this PR because we need to add the parameter `data-testid` to the sidebar in order to access to this property for testing purposes.
> fix(sidebar): Add data-testid to preview sidebar

- src/components/sidebar-toggle-button/__tests__/__snapshots__/SidebarToggleButton.test.js.snap
- src/components/tooltip/Tooltip.tsx
- src/components/tooltip/__tests__/Tooltip.test.tsx
- src/components/tooltip/__tests__/__snapshots__/Tooltip.test.tsx.snap
- src/features/pagination/__tests__/__snapshots__/MarkerBasedPagination.test.js.snap
- src/features/pagination/__tests__/__snapshots__/OffsetBasedPagination.test.js.snap
To meet [WCAG 1.4.13](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html) requirement, Tooltip needs to be dismissed by pressing "Escape" key when hovered or focused.
- Handle "Escape" key at `document` level to handle hovering over either the wrapped component or the tooltip
- Capture event and stop propagation of the Escape key event to prevent dismissing other floating components (e.g. Modal, Menu, etc.) from closing  (Note that the requirement describes it should dismiss **additional content**)
> A [mechanism](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html#dfn-mechanism) is available to dismiss the **additional content** without moving pointer hover or keyboard focus, ...
Preview
Modal
- We have use cases where the tooltip is forced …
> fix(tooltip): dismiss tooltip on ESC

- src/features/unified-share-modal/__tests__/EmailForm.test.js
- src/utils/validators.js
IE 11.379.17763.0
Safari 15.2 (16612.3.6.1.8, 16612)
Firefox 96.0.3
Chrome 97.0.4692.99
(pills overlapping text input in the pill selector input may be a tangentially-related ui bug)
> fix(usm): supplement email validator with addtl valid tlds

- src/components/tab-view/Tabs.scss
> fix(tab-view): focus outline

- src/components/search-form/SearchForm.scss
> fix(search): focus outline

- src/features/content-explorer/item-list/ItemList.js
- src/features/content-explorer/item-list/ItemListName.js
- src/features/content-explorer/item-list/__tests__/ItemListName.test.js
Without the id of the item being passed into the callback function you have no idea which row this is suppose to be rendered for.
> fix(content-explorer): Pass id into custom name renderer

- src/features/unified-share-modal/utils/__tests__/mergeContacts.test.js
- src/features/unified-share-modal/utils/mergeContacts.js
* Add lowercase normalization to email when merging new contacts with existing contacts
* Add test for different case email
* Test when an entry does not match and does not contain an id
**Before**
**After**
> fix(usm): Email addresses should not be marked as external due to case

- src/components/avatar/UnknownUserAvatar.tsx
- src/icons/avatars/UnknownUserAvatar.tsx
* Fixes Unknown user avatar scale to use proper viewbox for path element so path content fills svg container.
Before:
After:
> fix(avatar): fix scale of unknown user avtar svg

- src/icons/general/IconSearch.js.flow
- src/icons/general/IconSearch.tsx
- src/icons/general/IconSearchJuicy.js.flow
- src/icons/general/IconSearchJuicy.tsx
- src/icons/general/README.md
- src/icons/general/__tests__/IconSearchJuicy.test.tsx
Juicier version of IconSearch [found in Zeplin mockups](https://app.zeplin.io/project/614cb647d7f89ab694666261/screen/6228da594da800bd75b6f3f1) for header on mobile screen sizes. 
Unit tests are happy:
In action:
> feat(icon-search-juicy): create IconSearchJuicy

- src/components/flyout/Flyout.scss
- src/components/flyout/OverlayHeader.scss
- src/components/flyout/_variables.scss
- src/features/header-flyout/HeaderFlyout.js
- src/features/header-flyout/__tests__/__snapshots__/HeaderFlyout.test.js.snap
- src/features/header-flyout/styles/HeaderFlyout.scss
- src/features/header-flyout/styles/_variables.scss
Modified HeaderFlyout which implements Flyout to have responsive behaviors. Minimal changes to this component was made in order to limit the risk of changing HeaderFlyout and time spent on refactoring. HeaderFlyout is currently only used in two projects. Majority of the changes is in CSS
Consumers of HeaderFlyout can opt in to activate responsive behaviors by passing in the prop isResponsive=true
> feat(header-flyout): add responsive footer behavior and fix a few bugs

- src/components/radar/RadarAnimation.js.flow
- src/components/radar/RadarAnimation.tsx
- src/components/radar/__tests__/RadarAnimation.test.tsx
- src/components/radar/__tests__/__snapshots__/RadarAnimation.test.tsx.snap
Added `tetherElementClassName` prop to `RadarAnimation` component so that it's possible to add a custom class name to the tether element component, the same way it is now implemented in `Tooltip` component.
> feat(radar-animation): add tetherElementClassName prop

- src/features/unified-share-modal/UnifiedShareForm.js
- src/features/unified-share-modal/__tests__/UnifiedShareForm.test.js
- src/features/unified-share-modal/flowTypes.js
remove treatment code updates we don't plan to release (remove visuals related to `showNewUpgradeText`; keep winning visuals related to `showUpgradeInlineNotice`)
upgrading user will see:
> feat(modal): default ugrade inline notice to top of share modal

- i18n/en-US.properties
- src/features/classification/constants.js
- src/features/classification/flowTypes.js
- src/features/classification/security-controls/__tests__/utils.test.js
- src/features/classification/security-controls/messages.js
- src/features/classification/security-controls/utils.js
Updates the `SecurityControls` copies and logic in order to be able to display Sign request restrictions. This update follows the existing pattern in which the short version of the summary is displayed as a single sentence that lists all restrictions. Changes are backwards compatible.
**Sidebar Classification:**
**Security Controls Summary Modal:**
> feat(security-controls): Add restriction summary copies for Sign

- src/icons/iwork/IWorkDesktopIcon.md
- src/icons/iwork/IWorkIcon.md
- src/icons/iwork/IWorkIcon.tsx
- src/icons/iwork/__tests__/IWorkIcon.test.tsx
Updated `IWorkIcon` component to use new iWork icons. Following this PR: https://github.com/box/box-ui-elements/pull/2433
Reordered icons in README for consistent ordering (also aligns with ordering of `IconIWorkTrio`).
---
> feat(icons): Update IWorkIcon to latests assets

- src/components/modal/Modal.scss
- src/components/modal/ModalDialog.js
This is a continuation of this PR: https://github.com/box/box-ui-elements/pull/2910/files
The original author is unable to continue working on the PR, so I've taken over further development. This PR incorporates the author's prior commits.
- Adjusted styles to remove `z-index` and `position: fixed`. 
- Adjusted header and footer margins
- Now internal content can be properly scrolled
Shows margin, padding, content and then shows scrolling action.
> fix(modal): Adjust modal header elements and enable scrolling action

- src/components/menu/MenuSeparator.tsx
- src/components/menu/__tests__/MenuSeparator.test.tsx
Add `className` to `MenuSeparator` component to allow styling.
> fix(menu-separator): add className prop to MenuSeparator

- src/features/content-explorer/content-explorer-modal/ContentExplorerModal.js
- src/features/content-explorer/content-explorer-modal/__tests__/__snapshots__/ContentExplorerModal.test.js.snap
- src/features/content-explorer/content-explorer/ContentExplorer.js
- src/features/content-explorer/content-explorer/ContentExplorer.scss
- src/features/content-explorer/content-explorer/ContentExplorerActionButtons.js
- src/features/content-explorer/content-explorer/__tests__/__snapshots__/ContentExplorer.test.js.snap
- src/features/content-explorer/item-list/ItemList.js
- src/features/content-explorer/item-list/ItemList.scss
Reverts box/box-ui-elements#2932
Seems to result in a bug when there are many folders. If an item is selected, and the user scrolls down past the initial selection and makes another selection, the file explorer "jumps" back to the top. Selection remains unaffected.
> revert(content-explorer) Revert "feat(content-explorer): Add responsive behavior"

- src/elements/content-sidebar/additional-tabs/AdditionalTab.js
- src/elements/content-sidebar/additional-tabs/__tests__/__snapshots__/AdditionalTab.test.js.snap
Updated more apps icon on Preview sidebar to App Center icon
> fix(preview): update more apps icon in Preview sidebar/drawer

- src/components/media-query/types.js
BREAKING CHANGE: the previous type was boolean. This could break type
checkers
> fix(mediaquery): change type of size to string

- src/features/unified-share-modal/UnifiedShareModal.js
BREAKING CHANGE: onRemoveAllRestrictedExternalCollabs and restrictedExternalCollabEmails props have been removed
Now that EUA has been updated we no longer need to support the old props.
> feat(usm): BREAKING CHANGE Clean up USM props used for compatibility

- src/api/ThreadedComments.js
- src/api/__tests__/ThreadedComments.test.js
- src/common/types/threadedComments.js
- src/constants.js
Create src/api/ThreadedComments.js  to implement Threaded Replies requirements
- Include new api v2 url in the implementation getUrl function
- Include logic to support all required actions
- Creating Comment / reply
- Getting Comments for fileId
- Updating Comment (status and message)
- Deleting Comment
- Getting replies to Comment
> feat(threaded-replies): add ThrededComments API to support threaded replies

- src/api/Annotations.js
- src/api/Feed.js
- src/api/__tests__/Annotations.test.js
- src/api/__tests__/Feed.test.js
- src/common/types/annotations.js
Modify Annotations (src/api/Annotations.js) to implement Threaded Replies requirements
- modify getAnnotations function
New param: `shouldFetchReplies?: boolean`
if true add url param `fields=replies` 
- modify getAnnotation function
New param: `shouldFetchReplies?: boolean`
if true add url param `fields=replies` 
- modify updateAnnotation function
New param status?: OPEN|RESOLVED|DELETED
Include status field in PUT request
- create getAnnotationReplies function
Returns an array of replies for a given annotation id.
 
- create createAnnotationReply function
Creates a reply for an annotation
Request body:
```
{ message: “reply message” }
```
> feat(replies): Update Annotations API to support threaded replies

- src/icon/fill/UserSettings16.js.flow
- src/icon/fill/UserSettings16.stories.tsx
- src/icon/fill/UserSettings16.tsx
This PR is a result of me running `yarn build:assets -r git@git.dev.box.net/Box/design-assets` then ignoring every change apart of the icon I'm interested in and committing.
> feat(icons): add user settings icon

- src/features/shared-link-settings-modal/SharedLinkSettingsModal.js
- src/features/shared-link-settings-modal/__tests__/SharedLinkSettingsModal.test.js
- src/features/shared-link-settings-modal/__tests__/__snapshots__/SharedLinkSettingsModal.test.js.snap
Fixes an issue where the Shared Link Settings modal would render all classification labels in the default color (yellow).
This is due to the fact that the color information stored in the label was not properly being passed to the Classification component as we do in other places.
> fix(classification): Classification colors in Shared Link Settings Modal

- src/common/types/annotations.js
- src/common/types/feed.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActiveState.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityThread.js
- src/elements/content-sidebar/activity-feed/activity-feed/__tests__/ActiveState.test.js
- src/elements/content-sidebar/activity-feed/activity-feed/__tests__/ActivityThread.test.js
- src/elements/content-sidebar/activity-feed/activity-feed/__tests__/__snapshots__/ActiveState.test.js.snap
create base of ActivityThread component to support threads for Comments and Annotation. 
The role of this component is to group an activity (Comment or Annotation) with it’s replies
Props:
- replies?: Comment[]
- repliesTotal: number
- onReplyCreate?: Function
- onGetReplies?: Function
UI should be wrapped with ActivityCard component so that the entire thread is treated as a card
UI will render the main item based on it’s type using Comment or AnnotationActivity
> feat(threaded-replies): create base of ActivityThread component

- src/api/Feed.js
- src/api/__tests__/Feed.test.js
- src/elements/content-sidebar/ActivitySidebar.js
- src/elements/content-sidebar/__tests__/ActivitySidebar.test.js
- src/elements/content-sidebar/__tests__/__snapshots__/ActivitySidebar.test.js.snap
- src/elements/content-sidebar/activity-feed/activity-feed/ActiveState.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.js
- Updated logic to fetch Annotations with replies when `hasReplies` flag is true
- Added logic to change Annotation's status
-- propagated status change handler down to `AnnotationActivity` (it's use will be implemented in future PR)
> feat(content-sidebar): updated annotations logic for threaded replies

- src/elements/content-uploader/OverallUploadsProgressBar.js
We would like to reuse OverallUploadsProgressBar element for BoxSign, but we need to show a different message while dragging files. 
In the PR I made it possible to pass a custom message as a prop.
Please, take a look and let me know if any improvements in my code needed.
> feat(progress-bar): extended with ability to accept custom message

- i18n/en-US.properties
- src/features/unified-share-modal/ContactRestrictionNotice.js
- src/features/unified-share-modal/EmailForm.js
- src/features/unified-share-modal/UnifiedShareForm.js
- src/features/unified-share-modal/UnifiedShareModal.js
- src/features/unified-share-modal/__tests__/ContactRestrictionNotice.test.js
- src/features/unified-share-modal/__tests__/EmailForm.test.js
- src/features/unified-share-modal/__tests__/UnifiedShareForm.test.js
- src/features/unified-share-modal/__tests__/__snapshots__/UnifiedShareForm.test.js.snap
- src/features/unified-share-modal/__tests__/__snapshots__/UnifiedShareModal.test.js.snap
- src/features/unified-share-modal/flowTypes.js
- src/features/unified-share-modal/messages.js
- src/features/unified-share-modal/utils/__tests__/hasRestrictedContacts.test.js
- src/features/unified-share-modal/utils/__tests__/isRestrictedContact.test.js
- src/features/unified-share-modal/utils/hasRestrictedContacts.js
- src/features/unified-share-modal/utils/isRestrictedContact.js
Unified Share Modal will now also support displaying restrictions for groups in the same way that we do for individual contacts. Group restrictions are currently only possible for Information Barrier.
> feat(usm): Add support for group restrictions

- i18n/en-US.properties
- src/features/content-insights/ContentAnalyticsErrorState.scss
- src/features/content-insights/ContentAnalyticsErrorState.tsx
- src/features/content-insights/ContentInsightsSummary.tsx
- src/features/content-insights/__tests__/ContentInsightsSummary.test.tsx
- src/features/content-insights/messages.ts
- src/features/content-insights/types.ts
Adds error state for permission errors
Updated error states:
> feat(content-insights): Add permission error state for 403 errors

- src/features/content-insights/ContentAnalyticsErrorState.tsx
- src/features/content-insights/__tests__/ContentAnalyticsErrorState.test.tsx
- [ x ] Unit tests
Makes the error prop optional since we are only using the error prop to check if it's a permission error
> fix(content-insights): Allow undefined error ContentAnalyticsErrorState

- src/components/infinite-scroll/InfiniteScroll.md
- src/components/infinite-scroll/InfiniteScroll.tsx
One of the props for `infinite-scroll` is called `scrollContainerNode`, but is sometimes referred to as `scrollContainerRef`. Fixed for consistency.
> fix(infinite-scroll): fix documentation and prop name mismatch

- i18n/en-US.properties
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityThread.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityThreadReplies.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityThreadReplyForm.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityThreadReplyForm.scss
- src/elements/content-sidebar/activity-feed/activity-feed/__tests__/ActivityThread.test.js
- src/elements/content-sidebar/activity-feed/activity-feed/__tests__/ActivityThreadRepliesForm.test.js
- src/elements/content-sidebar/activity-feed/activity-feed/messages.js
- src/elements/content-sidebar/activity-feed/comment-form/CommentForm.js
- src/elements/content-sidebar/activity-feed/comment-form/__tests__/CommentForm.test.js
New component `ActivityThreadReplyForm`
* shows Reply button
* handles showing/hiding `CommentForm`
Changes in `ActivityThread`
* renders `ActivityThreadReplyForm`
Changes in `CommentForm.js`
* adds new optional prop `placeholder`
From figma (don't mind the background it's part of different feature, and the black blocks on right are part of arrows showing the flow)
As it's implemented
> feat(annotation-thread): handle create reply

- i18n/en-US.properties
- src/features/classification/security-controls/SecurityControlsItem.scss
- src/features/classification/security-controls/__tests__/__snapshots__/utils.test.js.snap
- src/features/classification/security-controls/__tests__/utils.test.js
- src/features/classification/security-controls/messages.js
- src/features/classification/security-controls/utils.js
> feat(classification): update security controls watermarking copy

- src/api/ThreadedComments.js
- src/api/__tests__/ThreadedComments.test.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActiveState.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityThread.js
- src/elements/content-sidebar/activity-feed/annotation-thread/AnnotationThreadContent.js
- Fixed handling reply edit logic to include `hasMention` attribute in the handler ultimately passed to `Comment` component
- Fixed double `file_id` url param being created in GET requests in `ThreadedComments` API
> fix(content-sidebar): ThreadedComments api; handling reply edit logic

- src/api/Feed.js
- src/api/__tests__/Feed.test.js
- src/elements/content-sidebar/__tests__/withSidebarAnnotations.test.js
- src/elements/content-sidebar/withSidebarAnnotations.js
- Added `modifyFeedItemRepliesCountBy` method for changing replies count
- Used `modifyFeedItemRepliesCountBy` in the create and delete reply actions
- Refactored `withSidebarAnnotations` to also use modifyFeedItemRepliesCountBy
- Updated `updateAnnotation` and `updateThreadedComment` methods to not update the feed item with `replies` and `total_reply_count` as their values are not included in the server response
> fix(content-sidebar): reply operations interactions

- src/features/content-explorer/content-explorer-modal-container/ContentExplorerModalContainer.js
`contentExplorerModalContainer` does not pass some of the props such as `itemRowRenderer` to contentExplorerModal. To make sure it passes all props, Im adding `...rest` for passing props and refactoring accordingly.
> fix(content-explorer): Pass all props from modalContainer to Modal

- src/elements/content-sidebar/activity-feed/activity-feed/ActivityThread.scss
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityThreadReplies.scss
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityThreadReplyForm.scss
- Round up the gray vertical line for replies in thread
- Make the “hide replies” and “show replies” button to be bold
- Make the “Reply” button to be bolded, and be $bdl-gray-62 (#767676)
- Decrease the space between replies
- Decrease space above "See more replies" button to 16px
> fix(threaded-replies): fix styling for replies

- src/components/checkbox/Checkbox.tsx
- src/components/checkbox/__tests__/Checkbox.test.tsx
- Add `shouldStopPropagationOnClick` to `Checkbox` component to allow for `stopPropagation` to be called in an `onClick` event. This allows outside `onClick` events to not be called when the checkbox is clicked
> feat(checkbox): allow stopPropagation on onClick events

- src/components/menu/MenuHeader.scss
Apply new `bdl-lineClamp` mixin to menu header title.
More options menu in full screen
> fix(menu): fix long title in menu header

- src/components/date-picker/DatePicker.tsx
- src/components/date-picker/__tests__/DatePicker.test.tsx
- src/components/label/InfoIconWithTooltip.tsx
- src/components/label/__tests__/__snapshots__/InfoIconWithTooltip.test.tsx.snap
**Background**
Alert16 and Info16 were renamed in the design-assets repo and pulled into BUIE in this PR: https://github.com/box/box-ui-elements/pull/3064 as AlertBadge16 and InfoBadge16
This fixes components that use the "old" version of the icons.
**Before**
**After**
> fix(assets): Use correct icons after icons were renamed

- src/features/collapsible-sidebar/CollapsibleSidebar.scss
- src/styles/_sizes.media.scss
- 1220 
- Hamburger menu (correctly doesn't work)
- Left nav overlaps content (should push right content over)
- 1221+
- page layout shifts into largest size layout (sidebar auto expands and right content shifts to the right)
- 1219 
- Hamburger menu
- Left nav should overlap content
- 1220+
- page layout should shift into largest size. (sidebar auto expands and right content shifts to the right)
- No hamburger menu
> feat(left-nav): Update medium width in _sizes.media.scss

- scripts/asset-import/cli.js
- scripts/asset-import/src/defaultConfig.js
- scripts/asset-import/src/import.js
This PR updates assets-import script.
It will take assets from `_Deprecated` directory instead of the root directory
> chore(scripts): Adjust design assets import script

- src/api/Feed.js
- src/api/ThreadedComments.js
- src/api/__tests__/Feed.test.js
- src/api/__tests__/ThreadedComments.test.js
- src/common/types/feed.js
- src/constants.js
- src/elements/content-sidebar/ActivitySidebar.js
- src/elements/content-sidebar/__tests__/ActivitySidebar.test.js
- src/elements/content-sidebar/__tests__/__snapshots__/ActivitySidebar.test.js.snap
- src/elements/content-sidebar/activity-feed/activity-feed/ActiveState.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.js
- src/elements/content-sidebar/activity-feed/activity-feed/__tests__/ActivityFeed.test.js
Added support for handling links with active item that is a reply. This is to support mentioning users directly in a reply. The link that user will receive in notification email will have only type and id of the feed item. This change covers that scenario by doing additional request for that replie's details (in order to get id of its parent). Logic can be seen in the diagram:
**Please note that this is a temporary solution done based on time constraints presented by Product. Final solution would be to change the link in notification email to also include `parentId`, thus making this additional request mentioned above not needed.**
> feat(content-sidebar): added support for active comment reply

- src/features/content-explorer/content-explorer-modal-container/ContentExplorerModalContainer.js
- src/features/content-explorer/content-explorer-modal/ContentExplorerModal.js
- src/features/content-explorer/content-explorer/ContentExplorer.js
- src/features/content-explorer/item-list/ItemList.js
- src/features/content-explorer/item-list/__tests__/ItemList.test.js
What I'm trying to achieve here? We would like to use the current ContentExplorerModalContainer in admin console but we need to add extra column, namely access level column. The most generic way to do it without breaking changes is to allow developer to pass any extra column they wish - those would appear after the folder name column - I chose this arbitrary but I think it makes sense - you would most probably like to keep the folder name and icon first and the select checkbox last so any additional columns should probably go in between. We could and try to make the column order configurable but I think it wouldn't be very useful and it would complicate the code. 
Of course this is not the greatest solution but it's non breaking and it allows us to use ContentExplorerModalContainer as is …
> feat: add additionalColumns prop to ContentExplorerModalContainer

- examples/src/ContentExplorerModalContainerExamples.js
- examples/src/ContentExplorerMultiSelectModalContainerExamples.js
- src/features/content-explorer/content-explorer/ContentExplorer.js
- src/features/metadata-instance-editor/TemplateDropdown.scss
the styleguidist examples included extra props not specified in the [prop types list](https://github.com/box/box-ui-elements/blob/master/src/features/content-explorer/content-explorer-modal-container/ContentExplorerModalContainer.js#L10) for `ContentExplorerModalContainer` that were passed to `ItemList` causing overflow issues
**Before**
**After**
> fix(content-explorer): Remove props from styleguidist examples

- src/features/content-explorer/content-explorer-modal-container/ContentExplorerModalContainer.js
- src/features/content-explorer/content-explorer-modal/ContentExplorerModal.js
- src/features/content-explorer/content-explorer/ContentExplorer.js
- src/features/content-explorer/item-list/ItemList.js
- src/features/content-explorer/item-list/__tests__/ItemList.test.js
What are we trying to do here?
We're trying to show the custom header for the table. 
Because by default it won't be visible because table header height is 0 I am also introducing tableHeaderHeight prop in order to make the header visible. 
I am also adding `headerRowRenderer` that we can pass through to the Table component that will allow to create a custom table headers.
If this is not clear enough we could introduce another prop `disableHeader` that would control the header visibility (you'd still need the height though). 
This is a non breaking change.
> feat: Add option to display header in ContentExplorerModalContainer

- src/elements/content-sidebar/activity-feed/annotations/AnnotationActivity.js
- src/elements/content-sidebar/activity-feed/annotations/__tests__/AnnotationActivity.test.js
- src/elements/content-sidebar/activity-feed/comment/Comment.js
- src/elements/content-sidebar/activity-feed/comment/__tests__/Comment.test.js
- Added missing logic to `AnnotationActivity` to pass `isEdited` prop value to `ActivityMessage` in order to display `edited` indicator.
- Added logic to hide the `edited` indicator for comments/annotations that are resolved. This is a temporary solution approved by Product to not display comment/annotation as edited when it was only resolved (resolving changes `modified_at` property). More time consuming BE changes are required for a final fix.
> feat(content-sidebar): hide "edited" for resolved comment/annotation

- src/features/content-explorer/content-explorer/ContentExplorer.js
I'm sorry but it's driving me crazy
> fix: remove warning when passing initialSelectedItems to ContentExplorer

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
- CONTRIBUTING.md
Added PR template to highlight that people should use the ready-to-merge label instead of clicking the merge button.  Adding the label, adds their PR to the merge train for safe merging.
> chore(template): Use ready to merge label instead of merge button

- src/elements/content-uploader/ItemAction.js
- src/elements/content-uploader/__tests__/ItemAction.test.js
- src/elements/content-uploader/__tests__/__snapshots__/ItemAction.test.js.snap
**After**
* aria-label added, matching hover text
* aria-describedby removed
> fix(item-action): add aria-label to plainbutton

- src/elements/common/sub-header/SortButton.js
- src/elements/common/sub-header/__tests__/Sort.test.js
- src/elements/common/sub-header/__tests__/SortButton.test.js
- src/elements/common/sub-header/__tests__/SubHeaderRight.test.js
> fix(sub-header): add accessibility label to SortButton

- src/components/select-button/SelectButton.js
- src/components/select-button/__tests__/SelectButton.test.js
- src/components/select-field/BaseSelectField.js
- src/components/select-field/__tests__/BaseSelectField.test.js
> feat(tooltip): support error tooltip position

- src/elements/content-sidebar/activity-feed/annotation-thread/AnnotationThread.js
- src/elements/content-sidebar/activity-feed/annotation-thread/AnnotationThreadContent.js
- src/elements/content-sidebar/activity-feed/annotation-thread/AnnotationThreadCreate.js
- src/elements/content-sidebar/activity-feed/annotation-thread/__mocks__/useAnnotationThread.js
- src/elements/content-sidebar/activity-feed/annotation-thread/__tests__/AnnotationThread.test.js
- src/elements/content-sidebar/activity-feed/annotation-thread/__tests__/AnnotationThreadCreate.test.js
- src/elements/content-sidebar/activity-feed/annotation-thread/__tests__/useAnnotationAPI.test.js
- src/elements/content-sidebar/activity-feed/annotation-thread/__tests__/useAnnotationThread.test.js
- src/elements/content-sidebar/activity-feed/annotation-thread/types.js
- src/elements/content-sidebar/activity-feed/annotation-thread/useAnnotationAPI.js
- src/elements/content-sidebar/activity-feed/annotation-thread/useAnnotationThread.js
- Addressed code review findings from https://github.com/box/box-ui-elements/pull/3184
- Moved all logic for creating annotation to `useAnnotationThread` and `useAnnotationAPI` hooks
> feat(annotation-thread): annotation thread related hooks refactoring

- src/components/checkbox/Checkbox.tsx
- src/components/checkbox/__tests__/Checkbox.test.tsx
> feat(checkbox): prop to add class to input

- src/elements/content-sidebar/activity-feed/annotation-thread/AnnotationThread.scss
- src/elements/content-sidebar/activity-feed/annotation-thread/__mocks__/useAnnotationThread.js
- src/elements/content-sidebar/activity-feed/annotation-thread/__tests__/AnnotationThreadCreate.test.js
- src/elements/content-sidebar/activity-feed/annotation-thread/__tests__/useAnnotationThread.test.js
- src/elements/content-sidebar/activity-feed/annotation-thread/useAnnotationThread.js
- Addressed code review findings from https://github.com/box/box-ui-elements/pull/3192
- Added handling of Annotation related events 
- Removed `ActivityThread` css hover effect inside `AnnotationThread`
> feat(annotation-thread): annotation thread events handling

- src/elements/common/_variables.scss
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityThread.scss
- src/elements/content-sidebar/activity-feed/annotation-thread/AnnotationThread.scss
- src/elements/content-sidebar/activity-feed/annotation-thread/__tests__/useAnnotationThread.test.js
- src/elements/content-sidebar/activity-feed/annotation-thread/__tests__/useRepliesAPI.test.js
- src/elements/content-sidebar/activity-feed/annotation-thread/errors.js
- src/elements/content-sidebar/activity-feed/annotation-thread/useAnnotationThread.js
- src/elements/content-sidebar/activity-feed/annotation-thread/useRepliesAPI.js
- Refactored `useRepliesAPI` to correspond to the approach taken in `useAnnotationAPI`
- Added handling for replies related events
- Fixed css styling issue of annotation menu button in `AnnotationThread`
- Fixed other bugs
> feat(annotation-thread): annotation thread replies events handling

- package.json
- yarn.lock
bump @box/react-virtualized, removing duplicate a11y labels on react-virtualized table rows.
> fix(react-virtualized): remove duplicate a11y label

- src/components/tooltip/CloseButton.tsx
- src/components/tooltip/Tooltip.tsx
- src/components/tooltip/__tests__/CloseButton.test.tsx
- src/components/tooltip/__tests__/__snapshots__/Tooltip.test.tsx.snap
Adding the aria-label directly to the tooltip requires updating at least 20 tests, and 150+ snapshots. Trevor recommended the idea of a separate component for the close button for the tooltip, which seems to work! The existing BUIE close button won't work, due to a mismatched icon size, as well as no support for localization without a wrapper.
> fix(usm): add aria-label to tooltip close button

- src/components/grid-view/GridViewSlider.scss
Remove styles that hide focus outline. Not sure why it was hidden in the first place, it doesn't show up with mouse interaction.
Initially introduced here: https://github.com/box/box-ui-elements/commit/ef4a7ee68ca1b2e2d0eb3410a05c1e66fc5dceb6
Before:
https://user-images.githubusercontent.com/24941488/212198025-651b4076-73f3-4000-be5d-c4f9a0baa50f.mov
After:
https://user-images.githubusercontent.com/24941488/212197943-ccb3473d-8f81-426e-9cfb-a094eab9619e.mov
> fix(grid-view): unhide focus outline for grid view slider

- i18n/en-US.properties
- src/features/unified-share-modal/SharedLinkSection.js
- src/features/unified-share-modal/__tests__/SharedLinkSection.test.js
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkSection.test.js.snap
- src/features/unified-share-modal/messages.js
Requested changes:
* add aria-label="expires" to the span containing the clock icon.
> fix(usm): add aria label

- i18n/en-US.properties
- src/elements/content-sidebar/SidebarNav.js
- src/elements/content-sidebar/SidebarNavSign.scss
- src/elements/content-sidebar/SidebarNavSign.tsx
- src/elements/content-sidebar/SidebarNavSignButton.tsx
- src/elements/content-sidebar/__tests__/SidebarNavSign.test.tsx
- src/elements/content-sidebar/messages.js
- Moved `SidebarNavSign` logic to a new component `SidebarNavSignButton` that renders the sign button in the SideBar.
- Extended `SidebarNavSign`, it now renders a dropdown with 2 options ("**Request signature**" which navigates to `/sign/new/{fileId}` and **Sign Myself** which navigates to `/sign/new/me/{fileId}`) instead of just the Sign button, based on new feature flag "isSignRemoveInterstitialEnabled".
- Extended `SidebarNavSign` and `SidebarNavSignButton` tests
> feat(preview): add new sign dropdown under ff

- src/components/checkbox/Checkbox.js.flow
- src/components/checkbox/Checkbox.scss
- src/components/checkbox/Checkbox.tsx
- src/components/checkbox/__tests__/Checkbox.test.tsx
These changes allow more control over focus styles by moving focus styles to a separate class and by declaring `onFocus` prop. These changes are needed in order to move focus styles to a click-target wrapper around the checkbox while maintaining the checkbox input as the actual focus. Here is an example usage:
> feat(checkbox): make focus behavior configurable

- package.json
- src/components/grid-view/__tests__/__snapshots__/GridView.test.js.snap
- src/features/virtualized-table/__tests__/__snapshots__/BaseVirtualizedTable.test.js.snap
- src/features/virtualized-table/__tests__/__snapshots__/VirtualizedTable.test.js.snap
- yarn.lock
Removes the default role "row" for Grid_innerScrollContainer when used inside of Table. The innerScrollContainer contains a group of rows and is not a row itself.
The solution follows the approach we're using for the main webapp.
> fix(react-virtualized): Remove role for Table_Grid_innerScrollContainer

- src/components/toggle/Toggle.js
- src/features/unified-share-modal/SharedLinkSection.js
- src/features/unified-share-modal/UnifiedShareModal.scss
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkSection.test.js.snap
Description:
The tooltip for the "Create shared link" is not presented to a screen reader. That is because it is associated to the `<div with tabindex="0>`, but since `<div>` does not support aria-describedby, the tooltip will not be read reliably by screen reader users.
Element Source
```
<div class="share-toggle-container tooltip-target tooltip-abutted tooltip-abutted-top tooltip-element-attached-bottom tooltip-element-attached-left tooltip-target-attached-top tooltip-target-attached-left" tabindex="0">
...
<input class="toggle-simple-input" name="toggle" type="checkbox">
```
Recommendation:
Move aria-describedby to the switch <input> and ensure that it is read reliably by screen readers.
> fix(shared-link-section): accessibility tooltip

- src/components/table/__tests__/makeSelectable.test.js
- src/components/table/makeSelectable.js
- select the first row when using shift arrow navigation and neither the source or the target is selected
- small refactor to the function
> fix(makeselectable): shift and arrow selects first row

- src/elements/common/_variables.scss
- src/features/unified-share-modal/UnifiedShareModal.scss
The placeholder text color of inputs/textareas does not meet a 4.5:1 color contrast ratio. The issue affects all inputs but the design team recommended only updating the specific usages in question since it would be a global change. The other usages would be fixed with the migration to the UI toolkit.
Design and accessibility team recommended using #767676 - $bdl-gray-62
**Before - Content Explorer**
**After - Content Explorer**
**Before - USM**
**After - USM**
> fix: Improve color contrast for placeholder text

- src/styles/_inputs.scss
Confirmed with the designer of design-system that box-shadows for input should be the following:
and there is no value change for the different interaction states.
**Before**
**After**
> fix: Update box-shadow for inputs

- src/elements/common/_variables.scss
- src/elements/common/base.scss
- src/features/unified-share-modal/UnifiedShareModal.scss
- src/styles/common/_forms.scss
Updating the border-color of text fields to meet a 3:1 contrast ratio with the input background. Design's recommendation is to only update the ones in question (i.e. the inputs in the elements) and to update the other components to use UI Toolkit.
**Before**
**After**
> fix: Improve color contrast for input borders

- src/elements/content-picker/Footer.js
- src/elements/content-picker/__tests__/Footer.test.js
Add `disabled` attribute to picker choose button when no items are selected.
> fix(content-picker): add disabled

- src/elements/content-uploader/Footer.js
- src/elements/content-uploader/__tests__/Footer.test.js
Similar fix to this: https://github.com/box/box-ui-elements/pull/3243/files
Essentially: The `isDisabled` prop does not set the `disabled` property, which means that it is still focusable by the keyboard.
Potential idea to have `isDisabled` set the `disabled` property as well, but because it might cause unintended consequences in parent apps we won't do so here.
https://www.w3.org/WAI/ARIA/apg/patterns/button/
> fix(content-uploader): make disabled buttons unfocusable

- src/elements/content-sharing/ContentSharing.js
stories for this element was not working based on the paragraph in the story because it was not regenerating a new API object when the knobs changed.  After further investigation, the API object should always be provided if the props are not provided to the API constructor.  Error handling happens in the functions
> fix(content-sharing): removed api condition when constructing api

- src/components/flyout/Flyout.scss
- src/components/flyout/Overlay.js
- src/components/flyout/__tests__/Overlay.test.js
This fixes an issue with the responsive overlay CSS being applied other .overlay elements that are within the **Flyout** **Overlay**. One example is when we have a **SelectorDropdown** within a **Flyout**. **SelectorDropdown** defines its own `.overlay` element and the responsive behaviors defined for **FlyoutOverlay** is spilling over to other unintended elements.
The chosen solution to increase the specificity was to add `.flyout-overlay` class name and restrict the CSS to the direct child descendent
`.flyout-overlay > .overlay`
Another accepted approach might have been to rename the **Flyout** and **Overlay** components to match SUIT naming but that comes with inherent risks as there are other CSS classes that override `.overlay`.
Observed Bug
Fixed
> fix(flyout): increase flyout overlay css specificity

- src/features/content-explorer/content-explorer/ContentExplorerFolderTreeBreadcrumbs.js
- src/features/content-explorer/content-explorer/ContentExplorerHeaderActions.js
- src/features/content-explorer/content-explorer/__tests__/ContentExplorerFolderTreeBreadcrumbs.test.js
> fix(content-explorer): hide instead of disable breadcrumbs

- i18n/en-US.properties
- src/features/content-explorer/content-explorer/ContentExplorer.js
- src/features/content-explorer/content-explorer/ContentExplorerActionButtons.js
- src/features/content-explorer/content-explorer/__tests__/ContentExplorerActionButtons.test.js
- src/features/content-explorer/content-explorer/__tests__/__snapshots__/ContentExplorer.test.js.snap
- src/features/content-explorer/messages.js
For the Include Subfolders toggle feature, we want the modal to also have a new footer for the text in the bottom left of the modal.
> fix(content-explorer): status message for include subfolders

- src/components/flyout/Flyout.js
- src/components/flyout/__tests__/Flyout.test.js
- src/features/metadata-instance-editor/TemplateDropdown.js
- src/features/metadata-instance-editor/__tests__/__snapshots__/TemplateDropdown.test.js.snap
The metadata template dropdown uses the Flyout component which flips the overlay upward if it exceeds the bottom of the viewport, making the dropdown look truncated.
To fix this issue, I added a new prop `contrainToWindowWithPin` to Flyout. When set to true, it pins the overlay to edges on small screens and makes good use of available space.
The main use case is in the Embed Widget 2.0 with the smallest recommended dimensions of 330px x 400px. Anything < 400px in height is out of our consideration.
> fix(metadata): fix template dropdown truncation issue

- src/features/content-explorer/content-explorer/ContentExplorer.scss
> fix(content-explorer): change color of folder tree breadcrumbs text

- src/components/text-input-with-copy-button/TextInputWithCopyButton.js
- src/components/text-input-with-copy-button/TextInputWithCopyButton.scss
Possible usages (how it looks like with additional buttons and without):
don't pay a lot of attention on content and paddings in these 2 new buttons, you should provide yours to these Nodes, that's just an examples.
how we will use it in Relay:
_I have also just realised that this "copy" button has different paddings_ :thinking_face:
@tjuanitas am I right that it should be possible simply by passing `className` to `buttonProps`?
> feat(input-with-copy): add node for settings button

- src/styles/constants/_colors.scss
- src/styles/variables.js
- src/styles/variables.json
- src/styles/variables.ts
`bdl-gray-62` is replaced with `bdl-gray-65` in our design system but we cannot remove `bdl-gray-62` yet because the SASS and JS variables are used many parent apps
> refactor(colors): Replace bdl-gray-62 with bdl-gray-65

- src/elements/common/breadcrumbs/InlineBreadcrumbs.scss
- src/elements/common/item/ItemDetails.scss
- src/elements/content-explorer/ItemList.js
- src/elements/content-explorer/ItemList.scss
**Changes**
- Improve color contrast for the item details text when the row is hovered
- This is barely noticeable in screenshots
- Remove extra padding before "All Files" when only one breadcrumb item
**Before**
**After**
> fix(content-explorer): Fix color contrast issue for item details

- src/elements/content-explorer/ContentExplorer.js
- src/elements/content-explorer/ItemList.scss
> fix(content-explorer): Update Share button border on selected row

- i18n/en-US.properties
- scripts/styleguide.config.js
- src/features/unified-share-modal/UnifiedShareForm.js
- src/features/unified-share-modal/messages.js
- Remove usage of the deprecated FormattedCompMessage component because we are dropping support for it in the translation automation
- Later, this usage should be replaced with a rich text FormattedMessage component (react-intl v3+) in order to get the proper string to translate
> refactor: Remove usage of the deprecated FormattedCompMessage component

- i18n/en-US.properties
- src/features/unified-share-modal/SharedLinkSection.js
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkSection.test.js.snap
- src/features/unified-share-modal/flowTypes.js
- src/features/unified-share-modal/messages.js
The `aria-label` is unnecessary and mismatched with the text. Recommendation is to remove and add `aria-haspopup`.
The "Link Settings" button is the element in question.
> fix(usm): Remove aria-label and add aria-haspopup

- src/features/shared-link-settings-modal/SharedLinkSettingsModal.scss
- src/features/shared-link-settings-modal/VanityNameSection.js
- src/features/unified-share-modal/UnifiedShareModal.scss
Gray 62 has issues where it barely meets the 4.5:1 color contrast ratio when used with a white background. If the component then changes background colors for different interaction states (hover, focus, etc), the contrast ratio no longer passes.
This is resolved by replacing usages of Gray 62 with Gray 65. Gray 62 is deprecated in our current design system.
**Before**
**After**
^ the "Manage security [...]" text is slightly darker
> fix: Replace bdl-gray-62 for USM and Shared Link components

- src/features/collapsible-sidebar/CollapsibleSidebar.js
- src/features/collapsible-sidebar/__tests__/CollapsibleSidebar.test.js
- src/features/collapsible-sidebar/__tests__/__snapshots__/CollapsibleSidebar.test.js.snap
Adds a`wrapperClassName` prop to apply CSS to the `CollapsibleSidebar-wrapper` element.
> feat(collapsible-sidebar): add wrapperClassName prop

- src/components/table/__tests__/makeSelectable.test.js
- src/components/table/makeSelectable.js
The library we use for hotkeys (mousetrap) prevents hotkeys on `input type=range` but not on elements with `role=slider`. This solves the scenario of using arrow hotkeys on the slider without focusing on the item list elements
> fix(makeselectable): Prevent arrow hotkeys on slider

- src/components/select-field/SelectField.scss
Currently, the margin for the dropdown menu of `SelectFieldDropdown` is only applied when the dropdown is placed beneath the select field. The margin should be consistent between the top and bottom placements of the dropdown menu.
**Before**
**After**
> fix(select-field): Add bottom margin when dropdown has top placement

- src/features/collaborator-avatars/CollaboratorListItem.js
- src/features/collaborator-avatars/CollaboratorListItem.scss
- src/features/collaborator-avatars/__tests__/__snapshots__/CollaboratorListItem.test.js.snap
Recommendation from WebAIM is to order the persons name before the icon in the DOM. I will follow up with PM to confirm this is the approach we want to do.
Solution: move the `info` div before the `CollaboratorAvatarItem` component so that it appears first in the DOM and use `flex-direction: row-reverse` to fix the order in the UI.
> fix(usm): Order person before icon in collaborator list DOM

- src/elements/common/_variables.scss
- src/elements/common/breadcrumbs/Breadcrumb.scss
- src/elements/common/breadcrumbs/BreadcrumbDropdown.scss
- src/elements/common/share-access-select/ShareAccessSelect.scss
- src/elements/common/sub-header/AddButton.js
- src/elements/common/sub-header/SortButton.js
- src/elements/common/sub-header/ViewModeChangeButton.js
- src/elements/content-explorer/ItemList.scss
- src/elements/content-picker/ItemList.scss
- src/elements/content-preview/preview-header/PreviewHeader.scss
- src/elements/content-sidebar/AddTaskMenu.scss
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityThreadReplyForm.scss
- src/elements/content-sidebar/activity-feed/annotations/AnnotationActivityLink.scss
- src/elements/content-sidebar/activity-feed/comment-form/CommentForm.scss
- src/elements/content-sidebar/activity-feed/comment/CreateReply.scss
- src/elements/content-sidebar/activity-feed/common/activity-message/ActivityMessage.scss
- src/elements/content-sidebar/activity-feed/task-new/AssigneeDetails.scss
- src/elements/content-sidebar/skills/timeline/Timeline.scss
- src/elements/content-sidebar/skills/transcript/Transcript.scss
- src/elements/content-sidebar/versions/VersionsGroup.scss
- src/elements/content-sidebar/versions/VersionsItem.scss
- src/features/content-insights/_mixins.scss
- src/features/metadata-based-view/IconWithTooltip.js
- src/features/metadata-based-view/MetadataBasedItemList.scss
- src/features/metadata-based-view/__tests__/__snapshots__/IconWithTooltip.test.js.snap
- src/features/metadata-instance-editor/CascadePolicy.scss
Similar to this PR: https://github.com/box/box-ui-elements/pull/3309, replacing usages of `$bdl-gray-62` with `$bdl-gray-65` except this is for files that are owned by Preview and UI Elements.
> refactor: Use bdl-gray-65 for /elements

- src/elements/content-explorer/ItemList.scss
Buttons with focus state should have `$bdl-gray` border. Due to specificity, the default `button:focus` border on this button was not being shown: https://github.com/box/box-ui-elements/blob/master/src/styles/common/_buttons.scss#L98
i.e. the border for buttons that are focused should be black but the border for this button is still blue because of the extra specificity added in this PR: https://github.com/box/box-ui-elements/pull/3278
**Before**
**After**
> fix(content-explorer): focus border on selected item row buttons

- src/features/unified-share-modal/SharedLinkAccessDescription.js
- src/features/unified-share-modal/SharedLinkAccessLabel.js
- src/features/unified-share-modal/SharedLinkAccessMenu.js
- src/features/unified-share-modal/__tests__/SharedLinkAccessDescription.test.js
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkAccessDescription.test.js.snap
the `item` prop was added for a Canvas use case in this PR: https://github.com/box/box-ui-elements/pull/3318
it was assumed that the component files in this features folder were only used by USM. however, there is a usage in the main webapp where only the `SharedLinkAccessLabel` component is imported and used in the sidebar when a folder is opened in the All Files page. When trying to bump BUIE in EUA, it is causing a type error because `item` is currently required.
This is setting `item` to optional instead of making a change in EUA to pass the `item` prop. The reasoning behind setting as optional instead of updating the component in EUA is so when Canvas is released, the changes in the above PR can be reverted without requiring another change in EUA.
> fix(usm): make item prop optional

- src/features/content-explorer/content-explorer/ContentExplorer.js
- src/features/content-explorer/content-explorer/__tests__/ContentExplorer.test.js
Select All checkbox was automatically getting checked in an empty folder. This was because of logic with .every where an empty item list will return true still as there is no item unchecked. 
This new change makes it so that in an empty folder, the Select All checkbox is permanently unchecked, and it cannot be checked. This is because with no items, it is impossible to have any items checked.
Before:
After:
> fix(content-explorer): select all checkbox in empty folder

- src/components/pill-selector-dropdown/PillSelector.js
- src/components/pill-selector-dropdown/PillSelectorDropdown.js
- src/features/unified-share-modal/ContactsField.js
- src/features/unified-share-modal/__tests__/__snapshots__/ContactsField.test.js.snap
The `showAvatars` prop from `PillSelector` was not being passed to the `RoundPill` component so the avatars were always being shown. The prop was added in this PR: https://github.com/box/box-ui-elements/pull/2171 and the description says the avatars can be hidden.
**Intended Implementation**
https://user-images.githubusercontent.com/1657938/83594159-5d823f00-a513-11ea-9b78-e80fee8bd0b4.png
**Before**
**After**
> fix(pill-selector-dropdown): pass showAvatars prop to RoundPill

- src/elements/common/sub-header/ViewModeChangeButton.scss
If a developer is using the CDN links and multiple elements, then there can be conflicting styles based on the order of the stylesheets. e.g. order of `<link>` tags in https://codepen.io/box-platform/pen/rRZxYq
This is happening with the `ViewModeChangeButton` in ContentExplorer because it has the same specificity weight as the base BUIE button. The base button styles included in the other elements' stylesheets (like Sidebar, Preview, etc) are applied after the Explorer specific styles which means if they have the same specificity weight, then styles imported last take precedent.
**Before**
**After**
> fix(content-explorer): increase grid button style specificity

- src/components/pill-selector-dropdown/PillSelector.js
- src/components/pill-selector-dropdown/PillSelectorDropdown.js
similar to components like `TextArea`, `TextInput`, `DatePicker`, etc.
**Before**
**After**
> feat(pill-selector-dropdown): allow setting error tooltip position

- CODEOWNERS
Only allow box-ui-elements group to approve changes to style constants
Later matches take precedence: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file
> chore(styles): update codeowners

- src/features/unified-share-modal/UnifiedShareForm.js
- src/features/unified-share-modal/__tests__/UnifiedShareForm.test.js
- src/features/unified-share-modal/flowTypes.js
BEFORE
A rejected promise occurs when `options.map` is called and `options` is undefined. The error does NOT result in a jest failure in node 14, but DOES result in a failure in node 18
```bash
nvm use 18.15
BABEL_ENV=test NODE_ENV=test yarn jest -c scripts/jest/jest.config.js src/features/unified-share-modal/__tests__/UnifiedShareForm.test.js -t "justification is allowed"
...
RUNS  src/features/unified-share-modal/__tests__/UnifiedShareForm.test.js
/.../box-ui-elements/src/features/unified-share-modal/UnifiedShareForm.js:119
justificationReasons: options.map(function (_ref2) {
^
TypeError: Cannot read properties of undefined (reading 'map')
at map (/.../box-ui-elements/src/features/unified-share-modal/UnifiedShareForm.js:120:51)
Node.js v18.15.0
error Command failed with exit code 1.
``` …
> fix(share-form): map called on undefined object

- src/features/content-explorer/content-explorer/__tests__/ContentExplorer.test.js
The contentExplorer.test.js file fails for following specific two tests(specific line highlighted)
https://github.com/box/box-ui-elements/blob/5f53847832935efae7146fa363c5f36bb8521440/src/features/content-explorer/content-explorer/__tests__/ContentExplorer.test.js#L751
https://github.com/box/box-ui-elements/blob/5f53847832935efae7146fa363c5f36bb8521440/src/features/content-explorer/content-explorer/__tests__/ContentExplorer.test.js#L767
Reasons why the error is showing `Cannot convert undefined or null to object` on https://github.com/box/box-ui-elements/blob/5f53847832935efae7146fa363c5f36bb8521440/src/features/content-explorer/content-explorer/ContentExplorer.js#L513 is because
https://github.com/box/box-ui-elements/blob/5f53847832935efae7146fa363c5f36bb8521440/src/features/content-explo …
> fix(content-explorer): map called on undefined object

- src/elements/content-preview/__tests__/ContentPreview.test.js
When bumping node to lts/hydrogen aka 18.16.0. the following error appear saying that `global.performance` is read only, after changing how we are mocking the object, it passes on 14 and 18
> chore(preview): Fix ContentPreview unit test mock for global.performance

- scripts/cut_release.sh
> chore(ci): add more descriptive log for buie release script

- scripts/cut_release.sh
> fix(ci): remove whitespace from release script var 

- scripts/cut_release.sh
> chore(ci): remove symbol from variable in release script

- scripts/cut_release.sh
> chore(ci): change regex for registry check in release script

- package.json
- scripts/cut_release.sh
> chore(ci): openssl-legacy-provider yarn test

- scripts/cut_release.sh
> chore(ci): unset OPENSSL_FORCE_FIPS_MODE

- package.json
> chore(ci): remove openssl flag from yarn test

- src/elements/content-preview/ContentPreview.scss
Note: This is the first part of the fix that needs to be merged and bumped before https://github.com/box/box-content-preview/pull/1483
- Update `left` of the left navigation arrow to **191px** to reflect the new thumbnail sidebar width
- Set `left` of the left navigation arrow to **0** when view size is below 768px (as the thumbnail sidebar will be hidden)
> fix(preview): update thumbnail sidebar width

- src/styles/_reset.scss
Removing CSS hack to target IE7 and below because that's superrrr outdated
https://www.geeksforgeeks.org/what-is-the-use-of-star-preceded-property-in-css/
> fix(css): remove IE7 CSS hack to fix Parcel support

- src/api/Feed.js
- src/api/FileActivities.js
- src/api/__tests__/Feed.test.js
- src/api/__tests__/FileActivities.test.js
This filters the call to file_activities depending on the parameters passed into the feed. Specifically for annotations, we previously threw an error if the specific file doesn't have the ability to add annotations. No call to file_activities would occur because of this. So now we just check if there's the proper permissions, if not, we filter annotations out.
> feat(uaa-integration): Filter activity types for UAA

- src/api/Folder.js
- src/api/WebLink.js
- src/constants.js
- src/elements/content-explorer/Content.js
- src/elements/content-explorer/ContentExplorer.js
- src/elements/content-explorer/PreviewDialog.js
- src/elements/content-explorer/ShareDialog.js
- src/elements/content-explorer/__tests__/ContentExplorer.test.js
- src/elements/content-picker/ContentPicker.js
- test/fixtures/content-picker/create-sharedlink.json
Check if the item has the `can_share` permission before trying to create a shared link with default access level. There's a bug for roles that do not have permission to generate shared links such as Previewer.
> fix(content-picker): check share permission for default shared links

- src/api/Metadata.js
- test/explorer-no-react.html
- test/explorer-picker-uploader.html
- test/explorer.html
- test/openwith.html
- test/pickers-no-react.html
- test/pickers.html
- test/popups.html
- test/preview-react-with-sidebar.html
- test/preview-react.html
- test/preview.html
- test/pseudo.html
- test/sharing-no-react.html
- test/sharing.html
- test/sidebar-additional-tabs.html
- test/sidebar.html
- test/uploader-no-react.html
- test/uploader-window-view.html
- test/uploader.html
I made a mistake by adding `dist` to the relative paths for the test pages in this PR: https://github.com/box/box-ui-elements/pull/3350
These files are intended to be tested with the `yarn start:dev` command and adding `dist` to the paths will cause issues because the sources will not be found.
<sup>i.e. everything breaks :(</sup>
> fix: update source paths for test pages

- src/components/modal/ModalDialog.js
- src/components/modal/__tests__/ModalDialog.test.js
It's possible to escape a modal with Accessibility Tools and a screen reader by using Control + Option + Arrow Keys.
This PR adds `aria-modal="true"` prop to ModalDialog div.
> fix(modal-dialog): add aria-modal to ModalDialog

- src/elements/content-uploader/OverallUploadsProgressBar.js
- src/elements/content-uploader/__tests__/OverallUploadsProgressBar.test.js
- src/elements/content-uploader/__tests__/__snapshots__/OverallUploadsProgressBar.test.js.snap
This PR fixes the issue of `OverallUploadsProgressBar` being accessible for screen readers when it's visually hidden
> fix: hide uploads manager progress bar for screen-readers if not visible

- src/components/flyout/Flyout.js
- src/components/flyout/__tests__/Flyout.test.js
~This PR extends `Flyout` component with `overlayRole` prop in order to pass a custom role for popup content. It includes updates for both overlay `role` attribute as well as `aria-haspopup` attribute for button container.~
This PR fixes `Flyout` container component attribute `aria-haspopup` to `dialog` to match the role of the overlay component.
> fix(flyout): set default role for Flyout to 'dialog'

- src/elements/content-sidebar/activity-feed/activity-feed/ActivityThreadReplies.js
* Fix bug with modifying a reply to a comment by mapping the single param to the multiple params used in props above
Notes
* See below for help tracing props
* `Comment.js and BaseComment.js` <- `ActivityThreadReplies.js` <- `ActivityThread.js`
* The props is continued to passed but ActivityThread shows the definition for the onEdit function params expected in components above it.
Issue
* The issue was introduced in this commit: https://github.com/box/box-ui-elements/commit/4f65525e0b502b809332717e537ca075f7a40321
* Before: https://cloud.box.com/s/pmgbtcg04fqjnvf38yok5dmk3wp3z6b2
* After: https://cloud.box.com/s/bwakotinhvlveplrosnpztpjzdz74ju1
> fix(modify-reply): Map object to params

- src/api/Feed.js
- src/common/types/feed.js
The UAA response gives a app activity event that is different than the v2 app activity API that we are currently using. We must parse the response and add the needed fields that our UI components need to render app activity events properly.
> feat(uaa-integration): Parse App Activity item

- src/api/Feed.js
- src/api/__tests__/Feed.test.js
- src/common/types/core.js
- src/constants.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActiveState.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.js
- src/elements/content-sidebar/activity-feed/activity-feed/__tests__/ActivityFeed.test.js
- src/elements/content-sidebar/activity-feed/version/CollapsedVersion.js
- src/elements/content-sidebar/activity-feed/version/Version.js
The UAA response gives a Versions activity event that is different than the v2 Versions API that we are currently using. We must parse the response and add the needed fields that our UI components need to render Version events. 
One big difference with this change is that the latest version events do not have `promotion` context, unlike the v2 API. So if the user has promoted a version and that version is the most recent version, they can only see that version was promoted by clicking the info button and looking at the version history. The team has had discussions around this and is okay with this tradeoff, we will look into adding the promotion context into the UAA response in the future.
UAA:
Multiple version events
Multiple upload collaborators
Version events with comments between
new …
> feat(uaa-integration): Parse Versions Response from UAA

- examples/Wrapper.js
I need a quick change to re-run the release pipeline.
This is removing a `core-js` import which says is used for IE11. I can't figure out where `Wrapper.js` is actually being used. I don't see references in `/examples/src` or in any of the elements. but I tested styleguidist in Chrome, Firefox, and Safari and everything seemed to work 🤷
> fix: remove core-js from examples wrapper

- src/api/Feed.js
When comment permission is false, we don't want to block the file_activities call, so we exclude `comments` from the parameters.
> feat(uaa-integration): Handle no comment permission

- src/elements/content-sidebar/versions/VersionsItem.scss
- src/styles/common/_buttons.scss
- src/styles/constants/_buttons.scss
Change focus indicator of actions button in version panel because the original one is difficult to be seen
Before:
After:
> fix(preview): Change focus indicator for actions in version panel

- i18n/en-US.properties
- src/features/content-answers/ContentAnswers.tsx
- src/features/content-answers/ContentAnswersModal.scss
- src/features/content-answers/ContentAnswersModal.tsx
- src/features/content-answers/ContentAnswersModalContent.scss
- src/features/content-answers/ContentAnswersModalContent.tsx
- src/features/content-answers/ContentAnswersModalFooter.scss
- src/features/content-answers/ContentAnswersModalFooter.tsx
- src/features/content-answers/ContentAnswersOpenButton.scss
- src/features/content-answers/__tests__/ContentAnswersModal.test.tsx
- src/features/content-answers/__tests__/ContentAnswersModalFooter.test.tsx
- src/features/content-answers/constants.ts
- src/features/content-answers/messages.ts
**Initial Modal**
**Modal with question input**
**Modal with input exceeds limitation**
> feat(content-answers): add contentAnswers Modal header and footer

- src/elements/content-sidebar/activity-feed/comment-form/CommentForm.js
- src/elements/content-sidebar/activity-feed/comment-form/__tests__/CommentForm.test.js
- src/elements/content-sidebar/activity-feed/comment/BaseComment.js
- src/elements/content-sidebar/activity-feed/comment/CreateReply.js
- src/elements/content-sidebar/activity-feed/comment/__tests__/BaseComment.test.js
- src/elements/content-sidebar/activity-feed/comment/__tests__/CreateReply.test.js
- Used draft.js functionality in `EditorState` to force focus on the comment form when it is open from either initiating a new reply or modifying and existing comment/reply
- Added `shouldFocusOnOpen` prop to `CommentForm` which allows callers to opt in to this behavior
*Note regarding tests* -- While it would be better to simulate click events and check browser focus of the textbox element, the `EditorState.moveFocusToEnd` uses a lot of window functions which don't exist in our current version of jsdom. I tried upgrading jsdom which solved the issue but focusing on the text box still wasn't working correctly. Given that this function is part of draft.js, I opted to mock it and check that was called.
> feat(preview): Focus on comment form for replies and modifying

- src/elements/content-sidebar/activity-feed/activity-feed/ActiveState.js
- src/elements/content-sidebar/activity-feed/activity-feed/__tests__/ActiveState.test.js
- Editing replies of an annotation should hit the comment edit endpoint to successfully work. Therefore, `onCommentEdit` must be passed to the Annotations BaseComment component so that it can ultimately be passed down to the Replies component and correctly called on a reply edit
- There is a known bug where the page must be refreshed to view a reply edit. This has been ticketed for a fix
> feat(annotations): editing an annotation reply

- src/elements/common/_variables.scss
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.scss
The activity feed with comments list doesn't scale with zoom correctly. At 400% zoom, the top header and the comment form cover the whole screen making the comment history not visible and it's not possible to scroll it into a view.
This PR adds a min-height property to the comments container so it does not get squished to zero height. The min-height is the same as the comment form.
Before:
After:
> fix(activity-feed-zoom): add a min-height prop to the items container

- src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityItem.scss
- src/elements/content-sidebar/activity-feed/activity-feed/stories/ActivityFeed.stories.js
- src/elements/content-sidebar/activity-feed/comment/BaseComment.js
- src/elements/content-sidebar/activity-feed/comment/BaseComment.scss
- src/elements/content-sidebar/activity-feed/comment/Replies.scss
- src/elements/content-sidebar/activity-feed/comment/components/BaseCommentInfo.js
- src/elements/content-sidebar/activity-feed/comment/components/BaseCommentInfo.scss
- src/elements/content-sidebar/activity-feed/comment/components/BaseCommentMenu.js
- src/elements/content-sidebar/activity-feed/comment/components/BaseCommentMenu.scss
- src/elements/content-sidebar/activity-feed/comment/components/BaseCommentMenuWrapper.js
- src/elements/content-sidebar/activity-feed/comment/components/__tests__/BaseCommentInfo.test.js
- src/elements/content-sidebar/activity-feed/comment/components/__tests__/BaseCommentMenu.test.js
- src/elements/content-sidebar/activity-feed/comment/components/stories/BaseCommentInfo.stories.js
- src/elements/content-sidebar/activity-feed/comment/components/stories/BaseCommentMenu.stories.js
- src/elements/content-sidebar/activity-feed/comment/components/stories/common.js
- src/elements/content-sidebar/activity-feed/comment/stories/common.js
- src/elements/content-sidebar/activity-feed/common/delete-confirmation/DeleteConfirmation.scss
The purpose of this task is to bring `BaseComment` into alignment with the layout for TR comments in [designs](https://www.figma.com/file/EyW24R6Bg9IkiQ33urle5l/Preview-Threaded-Replies-and-Annotations?node-id=1169%3A189350&mode=dev). The nesting of wrappers to apply the new layout prompted a request to break `BaseComment` down into its constituent components. That is the content of this PR.
Please note that bringing activity item styles into full alignment with the designs is beyond the scope of this PR. I did only what I subjectively considered to be the minimum to accommodate the new layout. (See [this document](https://cloud.box.com/s/04xkqx19dfkj5v4v069waqwh7locfzt3) for an attempt at cataloguing all incoming UI diffs).
legacy (on dev pod)
new layout (on dev pod)
If helpful, some …
> feat(activityitems): new layout

- src/components/text-input-with-copy-button/TextInputWithCopyButton.js
Currently textInputWithCopyButton allows the user to use ctrl c to copy the text input even when button is disabled. This change adds a disableCopy prop that will completely disable the ability to copy when set to true.
> fix: disable copy in textInputWithCopyButton when button is disabled

- .mergify.yml
> chore(mergify): file condition

- .mergify.yml
> chore(mergify): file condition regex

- src/elements/content-sidebar/ActivitySidebar.js
- src/elements/content-sidebar/__tests__/ActivitySidebar.test.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActiveState.js
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.js
- src/elements/content-sidebar/activity-feed/activity-feed/__tests__/ActiveState.test.js
- src/elements/content-sidebar/activity-feed/annotation-thread/AnnotationThreadContent.js
- src/elements/content-sidebar/activity-feed/annotation-thread/__tests__/useAnnotationThread.test.js
- src/elements/content-sidebar/activity-feed/annotation-thread/useAnnotationThread.js
- src/elements/content-sidebar/activity-feed/annotations/AnnotationActivity.js
- src/elements/content-sidebar/activity-feed/comment/BaseComment.js
- src/elements/content-sidebar/activity-feed/comment/__tests__/BaseComment.test.js
- src/elements/content-sidebar/activity-feed/comment/components/BaseCommentMenuWrapper.js
- src/elements/content-sidebar/activity-feed/comment/types.js
- Allows users to resolve/unresolve annotations when they have correct permissions
- Adds two new types for `onStatusChange` events (`OnCommentStatusChange` and `OnCommentStatusChange`)
- Refactored default properties in `OnCommentStatusChange` to be automatically appended in from the parent component instead of conditionally added in the child
- Updating status of comments was refactored but functionally unchanged
- Annotations are currently returning `can_resolve = false` regardless of comment owner on resolution. A separate ticket is tracking this bug
> feat(threaded-replies): added resolve/unresolve for annotations

- src/elements/content-preview/ContentPreview.js
- src/elements/content-preview/__tests__/ContentPreview.test.js
> feat(aci): add ACI config to features prop

- src/components/pill-selector-dropdown/PillSelector.js
- src/components/pill-selector-dropdown/PillSelector.scss
- src/components/pill-selector-dropdown/__tests__/PillSelector.test.js
This PR adds two new props to the `PillSelector` component. The two props are needed for the `PillSelectorDropdown` component. For now, they can be supplied to `PillSelector` through the `inputProps` prop.
Allows disabling the `textarea` element without disabling the whole `PillSelector`. Usecase: our application needs to be able to set a maximum number of pills so that the user cannot add more than this number but can add less. The plan is to use this prop to disable the input once the maximum number of pills is reached. The user cannot then add new pills, but can still remove existing pills. Once the number of pills goes below the maximum, we enable the input again.
Gives the `textarea` its own separate line when the user focuses the component to input text. The new line disappears when …
> feat(pill-selector): added more options for text input

- scripts/jest/jest.config.js
> chore(jest): updated code coverage ignore paths

- src/elements/content-explorer/MoreOptions.js
- src/utils/Browser.js
- src/utils/__tests__/Browser.test.js
Implementation of `canDownload` taken from box-content-preview for consistent downloading support:
https://github.com/box/box-content-preview/blob/master/src/lib/Browser.js
**Before**
**After**
> fix(content-explorer): detect if device supports downloading

- src/features/content-explorer/content-explorer/ContentExplorer.scss
- src/features/content-explorer/content-explorer/ContentExplorerBreadcrumbs.js
> fix(content-explorer): fix text ellipsis in breadcrumbs

- src/elements/content-uploader/ItemName.scss
- src/elements/content-uploader/ProgressBar.scss
> fix(content-uploader): add text ellipsis and adjust spacing

- src/elements/content-sidebar/ContentSidebar.scss
When the sidebar is opened on medium sized screens, annotations on the file will render above the sidebar.
Updating the `z-index` value of `.bcs.bcs-is-open` will layer the sidebar above the annotations. See [BaseAnnotator.scss](https://github.com/box/box-annotations/blob/master/src/common/BaseAnnotator.scss) for `z-index` values.
---
Closed sidebar
Opened sidebar
---
> fix(content-sidebar): increase z-index to stack above annotations

- src/features/collaborator-avatars/CollaboratorList.scss
- src/features/unified-share-modal/UnifiedShareModal.scss
I compared my refactored changes against current production on different screen sizes and did not identify issues:
---
**Small Screens**
---
**Small - Medium Screens**
---
I also confirmed these changes on Safari and saw no difference between production.
> feat(usm): enable responsive behavior

- src/elements/content-picker/Footer.scss
- src/features/pagination/Pagination.scss
We got customer feedback that they'd like to see the pagination count on the footer on mobile devices for Content Explorer and Content Picker. We explained that the pagination count is intentionally hidden on small devices because of the lack space. We came to an agreement to show the pagination count on only Explorer since there is space at 300px.
**Before - Content Explorer**
**After - Content Explorer**
**Unchanged - Content Picker**
> fix(content-explorer): show pagination count for small devices

- src/elements/content-preview/ContentPreview.scss
- src/elements/content-sidebar/ContentSidebar.scss
- src/elements/content-sidebar/SidebarContent.scss
- src/elements/content-sidebar/SidebarNav.scss
- src/elements/content-sidebar/SidebarNavButton.scss
- src/elements/content-sidebar/SidebarNavSignButton.scss
- src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.scss
The main objective of this change was to remove the `is-responsive-web` class scope that wrapped the media queries enabling the responsive behavior.
In multiple cases, removing the `is-responsive-web` class lowered the specificity of the rules which no longer applied the appropriate responsive styles. In these cases, I reorganized the blocks to match the nesting and structure of the base (non-responsive) styles. If two selectors have the same specificity level, then the ones declared later are applied on the component which explains most of the restructure.
> feat(content-sidebar): enable responsiveness for Preview and Sidebar

- src/features/content-explorer/content-explorer-modal-container/ContentExplorerModalContainer.js
- src/features/content-explorer/content-explorer-modal-container/__tests__/ContentExplorerModalContainer.test.js
- src/features/content-explorer/content-explorer-modal/ContentExplorerModal.js
- src/features/content-explorer/content-explorer-modal/__tests__/__snapshots__/ContentExplorerModal.test.js.snap
- src/features/content-explorer/new-folder-modal/NewFolderModal.js
Extended `ContentExplorerModalContainer` and `ContentExplorerModal` components to accept optional `shouldNotUsePortal` to that it's possible to render the modal within the parent, not only in the Portal.
> feat(content-explorer): allow not using Portal when rendering modal

- .circleci/config.yml
Moved flow to its own job
Switch jobs to node images for non cypress jobs
> chore(ci): moved flow to its own job

- CODEOWNERS
Add @box/design-system as code owners for `src/styles` directory.
> chore(codeowners): add design system as owner for styles

- src/utils/__tests__/relativeTime.test.js
It has been reported that the `relativeTime.test.js` test, created during the react-intl upgrade, has been failing inconsistently over the past couple of weeks when running the release pipeline.
I cannot reproduce this error locally; the tests always pass for me. I believe it may be related to Date.now() not being mocked for tests. I've mocked Date.now() within my tests to ensure consistent behavior. I think this should resolve the reported issue.
> fix(react-intl): mock date in relative time unit tests

- i18n/en-US.properties
- src/common/constants.js
- src/common/types/core.js
- src/features/unified-share-modal/SharedLinkAccessDescription.js
- src/features/unified-share-modal/__tests__/SharedLinkAccessDescription.test.js
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkAccessDescription.test.js.snap
- src/features/unified-share-modal/messages.js
Adding new access label for `item type = hubs`.
> feat(usm): Add access level label for hubs

- package.json
localhost was refusing connection, when set to 127.0.0.1 it was able to connect
> chore(circleci): update wait-on command to use ipv4 explicitly

- src/common/constants.js
- src/common/types/core.js
- src/features/unified-share-modal/SharedLinkAccessDescription.js
- src/features/unified-share-modal/__tests__/SharedLinkAccessDescription.test.js
Fix a typo in item type hubs. It should be `hubs` since it will be used as part of the collaborator page.
> fix(usm): fix item type hubs

- .circleci/config.yml
- scripts/chromatic.sh
https://www.chromatic.com/docs/circleci/#squashrebase-merge-and-the-main-branch
> chore(chromatic): Updated cirleci to auto accept on master

- .circleci/config.yml
> chore(circleci): Updated caching

- src/elements/common/fonts.scss
The fonts files itself haven't changed
Changing it to have parity with internal Box changes
> fix(fonts): update common fonts version

- .npmignore
added [chromatic.config.json](https://github.com/box/box-ui-elements/blob/master/chromatic.config.json) to .npmignore so that it is not published to npm
> fix(npm): add chromatic config to npmignore

- src/features/content-answers/Answer.scss
- src/features/content-answers/ContentAnswersGridCard.scss
- src/features/content-answers/ContentAnswersModal.scss
- src/features/content-answers/ContentAnswersModal.tsx
- src/features/content-answers/ContentAnswersModalContent.scss
- src/features/content-answers/ContentAnswersModalError.scss
- src/features/content-answers/ContentAnswersModalFooter.scss
- src/features/content-answers/ContentAnswersModalFooterActions.scss
- src/features/content-answers/ContentAnswersOpenButton.scss
- src/features/content-answers/InlineError.scss
- src/features/content-answers/LoadingElement.scss
- src/features/content-answers/LoadingElement.tsx
- src/features/content-answers/Question.scss
- src/features/content-answers/WelcomeMessage.scss
When running a custom app, the UI for Content Answers is not appearing as expected. There are a couple reasons for this:
1. Storybook and our internal apps (EUA, AC) have styles applied to the `body` element which gives us a false assumption of base styles during development. When the component is then used in a customer app, we are missing these base styles. To resolve this, we need to add the `be-modal` class to the outer modal component and the `be` class to the inner content so that the correct styles are applied.
2. Depending on how the customer imports our CSS stylesheets, component styles may be incorrectly applied if they have the same level of specificity as the lower level components. For example, the styles for `bdl-ContentAnswersOpenButton` has the same specificity as the base …
> fix(content-answers): scope styles to content answers modal

- src/features/unified-share-modal/UnifiedShareForm.js
- src/features/unified-share-modal/UnifiedShareModal.scss
- src/features/unified-share-modal/__tests__/UnifiedShareForm.test.js
- src/features/unified-share-modal/flowTypes.js
Example of new Business plan blueprint Inline Notice (purple) being passed into Unified Share Modal:
Example of new Freemium plan blueprint Inline Notice (blue) being passed into Unified Share Modal:
> feat(usm): add inline notice as component

- src/features/unified-share-modal/UnifiedShareForm.js
- src/features/unified-share-modal/__tests__/UnifiedShareForm.test.js
While our upsell inline notice is showing, we do not want redundant upgrade text to show (highlighted below).
> fix(usm): hide link description when upsell shows

- src/elements/README.md
Updated the README to be more clear on how to apply the localization. There was some confusion on only providing language or the message and that both were not require when they are. Included examples
> chore(i18n): Update README to be more clear on IntlProvider usage

- src/elements/content-sidebar/additional-tabs/AdditionalTab.scss
To bring it in line with current App Center styles
Before:
After:
> fix(content-sidebar): update to sidebar icon styles

- package.json
- yarn.lock
BREAKING CHANGE: upgrade peer dependency for react-virtualized to support react 18
> fix: upgrade react-virtualized peer dependency

- .prettierrc.js
- package.json
- scripts/jest/jest.config.js
- scripts/webpack.config.js
- src/test-utils/testing-library.js.flow
- src/test-utils/testing-library.tsx
- yarn.lock
> feat(blueprint): Added blueprint

- scripts/webpack.config.js
> chore(webpack): removed lodash alias and added new mjs rule

- src/components/toggle/Toggle.js
- src/features/unified-share-modal/ContactsField.js
- src/features/unified-share-modal/InviteePermissionsMenu.js
- src/features/unified-share-modal/SharedLinkSection.js
- src/features/unified-share-modal/__tests__/__snapshots__/ContactsField.test.js.snap
- src/features/unified-share-modal/__tests__/__snapshots__/InviteePermissionsMenu.test.js.snap
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkSection.test.js.snap
Added `data-target-id` attribute to various elements of `unified-share-modal`. It will be used for targeting purposes.
> feat(unified-share-modal): added targeting attribute

- src/api/Metadata.js
- src/api/__tests__/Metadata.test.js
- src/common/types/metadata.js
This change extends `getMetadata` method in `Metadata API` in order to meet Metadata Sidebar Redesign needs as it will require less complex typing. 
Currently **MetadataSidebar** fetches `editors` which are objects containing:
* **`template` object** - it holds data on which template was used to create metadata instance for current file and current user and most importantly it holds `fields` array. This array consists of `field` objects which hold details on field displayName, field type etc. but do not hold field value for current file and current user - this is job for `instance` object.
* `instance` object - as explained above is simple object with instance details like id and key-value pairs which reflect template fields keys.
For now in order to get field details AND value for …
> feat(api): Extend getMetadata in Metadata API

- src/api/Metadata.js
- src/api/__tests__/Metadata.test.js
- src/elements/content-sidebar/MetadataInstanceEditor.tsx
- src/elements/content-sidebar/MetadataSidebarRedesign.tsx
- src/elements/content-sidebar/__tests__/MetadataInstanceEditor.test.tsx
- src/elements/content-sidebar/__tests__/MetadataSidebarRedesign.test.tsx
- src/elements/content-sidebar/hooks/useSidebarMetadataFetcher.ts
- src/elements/content-sidebar/stories/MetadataSidebarRedesign.stories.tsx
- src/elements/content-sidebar/stories/tests/MetadataSidebarRedesign-visual.stories.tsx
**Description**
The `MetadataInstanceEditor` lets users edit metadata templates for a file. It uses the `MetadataInstanceForm` from `@box/metadata-editor` to handle the form. Only one template can be edited at a time, selected via the `AddMetadataTemplateDropdown`. If users try to switch templates while editing, a modal will pop up to save or discard any unsaved changes.
**Screenshots**
> feat(metadata-sidebar): Metadata Instance Editor

- i18n/en-US.properties
- src/features/unified-share-modal/SharedLinkAccessDescription.js
- src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkAccessDescription.test.js.snap
- src/features/unified-share-modal/messages.js
fix public shared link text for hubs
> fix(hubs): fix shared link text

- src/components/notification/Notification.scss
- src/components/notification/NotificationsWrapper.js
**Issue:**
When `Notification` component rendered inside the `NotificationsWrapper`, it blocks the UI on the entire width of the page under the toast. The issue is reproducible on [live demo](https://opensource.box.com/box-ui-elements/#/Components/NotificationsWrapper): when a notification toast appears, button 'Open isolated' on the right becomes unclickable, and text on the left - unselectable. 
**Reason:**
After [this commit](https://github.com/box/box-ui-elements/commit/21af3552ca25231fe0bfbc47d9db1f6f2ec6c440), `NotificationsWrapper` wraps all children elements in `FocusTrap`, which basically wraps children in a `<div>` element. This `<div>` doesn't have any style, so it defaults to `height: auto`, ignoring `height: 0` set on `NotificationsWrapper` …
> fix(notification): unblock UI beneath Notification

- src/features/metadata-instance-editor/CascadePolicy.js
Fix "learn more" link in metadata instance editor for info about cascade policies
> fix(metadata-instance-editor): Fix support link

- src/api/Metadata.js
- src/api/__tests__/Metadata.test.js
- src/elements/content-sidebar/MetadataSidebarRedesign.tsx
- src/elements/content-sidebar/__tests__/MetadataSidebarRedesign.test.tsx
- src/elements/content-sidebar/__tests__/useSidebarMetadataFetcher.test.tsx
- src/elements/content-sidebar/hooks/useSidebarMetadataFetcher.ts
Add Metadata Instance update handler for Metadata Sidebar Redesigned
> feat(metadata-sidebar): handle update metadata instance

- src/elements/content-sidebar/MetadataInstanceEditor.tsx
- src/elements/content-sidebar/MetadataSidebarRedesign.tsx
- src/elements/content-sidebar/__tests__/MetadataInstanceEditor.test.tsx
- src/elements/content-sidebar/stories/tests/MetadataSidebarRedesign-visual.stories.tsx
- fix and refactor cancelling logic for `MetadataInstanceEditor`
- add new additional props for `MetadataInstanceEditor`: `setIsUnsavedChangesModalOpen` and `onUnsavedChangesModalCancel` for handling the `UnsavedChangesModal` directly from BUIE
- fix issues with templates in `AddMetadataTemplateDropdown` still being disabled after cancelling editing a new template
- handle adding a new template when another one is still in edit mode with `UnsavedChangesModal`, add `handleCancelUnsavedChanges` in `MetadataSidebarRedesign` ('Cancel' action in `UnsavedChangesModal`) for checking if there are pending editors to switch to immediately after cancelling the previous one
Temporary conversion between `MetadataTemplateInstance` and `MetadataTemplate` was added, which will be handled properly in the …
> fix(metadata-sidebar): handle onCancel action for editing templates

- src/elements/content-sidebar/MetadataSidebarRedesign.tsx
- src/elements/content-sidebar/__tests__/MetadataSidebarRedesign.test.tsx
- src/elements/content-sidebar/stories/tests/MetadataSidebarRedesign-visual.stories.tsx
- src/test-utils/testing-library.tsx
Fix from where we read if Metadata Sidebar should have AI capabilities turned on.
> fix(metadata-sidebar): Fix metadata sidebar ai capabilities

- src/elements/content-sidebar/MetadataSidebarRedesign.scss
**Description**
Changes in styles for `MetadataSidebarRedsign` to align with the design:
- bottom property removed
- padding changed to 16px
- background-color removed 
**Screenshots**
> feat(metadata-sidebar): tab content styles change

- package.json
- yarn.lock
this resolves deprecation warnings by pinning the version of sass. the package was previously pinned as well to `1.34.1` but had been upgraded during the react 18 support changes.
it is too risky at the moment to resolve the sass deprecation warnings since it involves reordering of style blocks which are used in many internal apps.
> chore: resolve sass deprecation warnings

- src/api/Intelligence.js
- src/elements/common/annotator-context/index.ts
- src/elements/content-preview/ContentPreview.js
- src/elements/content-sidebar/ActivitySidebar.js
Vite apps that install box-ui-elements hit the following errors:
```
No matching export in "node_modules/@box/box-ai-content-answers/esm/index.js" for import "QuestionType"
No matching export in "node_modules/box-ui-elements/es/elements/common/annotator-context/index.js" for import "WithAnnotatorContextProps"
No matching export in "node_modules/box-ui-elements/es/elements/common/annotator-context/index.js" for import "WithAnnotationsProps"
```
two issues:
- `type` is needed in the import statement so that during the `es` build step, these lines are properly removed
- `WithAnnotationsProps` and `WithAnnotatorContextProps` were not exported in the `index.ts` when ContentPreview is trying to import from that file
> fix: resolve missing exports for esbuild

- src/test-utils/testing-library.tsx
BREAKING CHANGE: blueprint-web and blueprint-web-assets peer dependencies
this PR should be labeled as a breaking change: https://github.com/box/box-ui-elements/pull/3585
> feat: noop for BREAKING CHANGE blueprint peer dependency

- src/api/Metadata.js
- src/api/__tests__/Metadata.test.js
- src/api/__tests__/utils.test.js
- src/api/utils.js
* Added support for creating metadata instances with taxonomy field values
* Added support for updating taxonomy field values on existing instances
* Added support for showing taxonomy field values on page load
Demos:
> feat(taxonomy): added view/create/updated taxonomy field support

- i18n/en-US.properties
- src/features/classification/Classification.js
- src/features/classification/__tests__/__snapshots__/Classification.test.js.snap
- src/features/classification/security-controls/SecurityControls.js
- src/features/classification/security-controls/__tests__/SecurityControls.test.js
- src/features/classification/security-controls/__tests__/utils.test.js
- src/features/classification/security-controls/integrationRestrictionsMessageMap.js
- src/features/classification/security-controls/messages.js
- src/features/classification/security-controls/utils.js
Replaced 'application' references in Classification modal with 'integration', based on optional flag variable (by default set to false, so I won't break existing code and will display 'application' as usual). When flag is passed as 'True' then 'Integrations' will be displayed, otherwise 'Applications'. Also, unit tests are added for related changes.
> fix(classification): Apps to Integrations name change

- .prettierignore
- flow-typed/npm/react-intl_v2.x.x.js
- src/elements/content-explorer/PreviewDialog.js.flow
- src/elements/content-explorer/PreviewDialog.tsx
- src/elements/content-explorer/__tests__/PreviewDialog.test.tsx
- src/elements/content-explorer/stories/PreviewDialog.stories.tsx
- src/elements/content-explorer/stories/tests/PreviewDialog-visual.stories.tsx
> chore(content-explorer): Migrate previewDialog

- src/elements/content-sidebar/ContentSidebar.js
- src/elements/content-sidebar/Sidebar.js
- src/elements/content-sidebar/__tests__/Sidebar.test.js
Added `onOpenChange` prop to ContentSidebar. The reason for that is that we need to handle sidebar being collapsed or expanded.
> feat(content-sidebar): Added open state change handler prop

- src/elements/common/modal.scss
- src/elements/content-explorer/RenameDialog.js.flow
- src/elements/content-explorer/RenameDialog.tsx
- src/elements/content-explorer/__tests__/RenameDialog.test.tsx
- src/elements/content-explorer/__tests__/ShareDialog.test.tsx
- src/elements/content-explorer/stories/RenameDialog.stories.tsx
- src/elements/content-explorer/stories/tests/RenameDialog-visual.stories.tsx
> chore(content-explorer): Migrate renameDialog

- src/elements/content-sidebar/SidebarFileProperties.js
- src/elements/content-sidebar/__tests__/SidebarFileProperties.test.js
It has turned out that we store archive date in milliseconds, so multiplication by 1000 was not necessary.
> fix(content-sidebar): fix archive date formatting

- src/elements/content-sidebar/ContentSidebar.js
- src/elements/content-sidebar/Sidebar.js
- src/elements/content-sidebar/SidebarPanels.js
- src/elements/content-sidebar/__mocks__/SidebarUtils.js
- src/elements/content-sidebar/__tests__/Sidebar.test.js
- src/elements/content-sidebar/__tests__/SidebarPanels.test.js
- src/elements/content-sidebar/stories/ContentSidebar.stories.js
- src/elements/content-sidebar/stories/__mocks__/ContentSidebarMocks.ts
Added functionality to `content-sidebar` to preserve (using `LocalStore`) the selected panel, so that it's active next time Sidebar is open. This is controlled with new `panelSelectionPreservation` feature.
> feat(content-sidebar): Added panel selection preservation

- .circleci/config.yml
Reduce build times by 35% by fixing the caching issue in circleci
> chore(circleci): update caching

- src/elements/content-sidebar/MetadataSidebarRedesign.tsx
- src/elements/content-sidebar/__tests__/MetadataSidebarRedesign.test.tsx
Adjust logic to show empty state if only added metadata instance is hidden.
> feat(metadata-editor): show empty state if there's no visible instances

- package.json
- src/elements/content-sidebar/__tests__/useSidebarMetadataFetcher.test.tsx
- src/elements/content-sidebar/hooks/useSidebarMetadataFetcher.ts
- yarn.lock
Adjust extractSuggestions function to use metadata_template instead of fields
> feat(metadata-sidebar): adjust extractSuggestions to use metadata_template

- i18n.config.js
- i18n/en-US.properties
- package.json
- scripts/jest/jest.config.js
- src/elements/content-sidebar/BoxAISidebar.scss
- src/elements/content-sidebar/BoxAISidebar.tsx
- src/elements/content-sidebar/__tests__/BoxAISidebar.test.tsx
- src/elements/content-sidebar/messages.js
- src/elements/content-sidebar/stories/__mocks__/BoxAISidebarMocks.ts
- src/elements/content-sidebar/stories/tests/BoxAISidebar-visual.stories.tsx
- yarn.lock
Added `box-ai-agent-selector` shared component to Box AI sidebar header.
Important thing to mention - since [this](https://github.com/box/box-ui-elements/pull/3758) PR is in review at the moment, the width for the sidebar was adjusted locally.
One remark to make - the styles of this shared component will need to be changed in order to 
1. Place more text in `SELECTED_AGENT` area. Styles of the inner element need to be changed, specifically some margin needs to be adjusted.
2. In order to show AI models in a dropdown list, we need to adjust list `max-width`, so it can fit in sidebar and not cover too much content. Here you can see how wide this dropdown is with some agents in it:
Showcasing dropdown list width, that needs to be adjusted in a shared component:
> feat(boxai-sidebar): Add Agent selector and clear button to sidebar

- src/elements/content-uploader/ContentUploader.tsx
The issue here is that we are relying on react state to maintain a queue that is updated through multiple async calls to determine what files to upload and when an upload is finished. With the upgrade to React 18, this state is stale during these async calls. Changing this state to a ref fixes the issue
> fix(content-uploader): fix upload add queue race condition

- src/elements/content-uploader/ContentUploader.tsx
- src/elements/content-uploader/__tests__/ContentUploader.test.js
> fix(content-uploader): use refs for items and itemIds

- src/elements/content-sidebar/BoxAISidebar.scss
**Description**
This PR implements two updates to the header of the "Box AI" tab to improve its display.
Medium screen
> fix(boxai-sidebar): header width and white-space adjustment

- src/elements/content-uploader/ContentUploader.tsx
- src/elements/content-uploader/__tests__/ContentUploader.test.js
> fix(content-uploader): fix bug in assigning new item ids

- src/common/types/api.js
- src/constants.js
- src/elements/content-sidebar/MetadataSidebarRedesign.tsx
- src/elements/content-sidebar/__tests__/MetadataSidebarRedesign.test.tsx
- src/elements/content-sidebar/__tests__/useSidebarMetadataFetcher.test.tsx
- src/elements/content-sidebar/hooks/useSidebarMetadataFetcher.ts
- src/elements/content-sidebar/stories/MetadataSidebarRedesign.stories.tsx
- src/elements/content-sidebar/stories/__mocks__/MetadataSidebarRedesignedMocks.ts
- src/elements/content-sidebar/stories/tests/MetadataSidebarRedesign-visual.stories.tsx
We want to call `onSuccess` when following events are performed successfully:
- template instance is updated
- template instance is deleted
* add `onSuccess` prop to `useSidebarMetadataFetcher`
* call `onSuccess` in `useSidebarMetadataFetcher` as success callback in:
* `handleDeleteMetadataInstance`
* `handleUpdateMetadataInstance`
* add adequate success code to constants
* define `ElementsSuccess` type to be later used in consumer app
* add `onSuccess` prop to `MetadataSidebarRedesign` and pass it to `useSidebarMetadataFetcher`
* update `MetadataSidebarRedesignProps` to extend `SuccessContextProps` (needs to be defined and reused in `useSidebarMetadataFetcher` for `onSuccess` prop type)
> feat(metadata-sidebar): handle success events

- src/elements/content-sidebar/BoxAISidebar.scss
Fixed the styling of Box AI Sidebar when zoomed in >= 175%. Previously a horizontal scroll was appearing at the bottom.
Before:
After:
Mobile view looks the same as before:
> fix(content-sidebar): box ai sidebar zoom fix

- src/elements/content-sidebar/BoxAISidebar.tsx
- src/elements/content-sidebar/BoxAISidebarContent.tsx
Passed  isStopResponseEnabled prop to BoxAiContentAnswers, so the AI in sidebar has the same stop response experience as modal.
https://github.com/user-attachments/assets/758341d4-bcbb-4d60-b15d-d46e9660c4df
> feat(boxai-sidebar): Pass isStopResponseEnabled prop to BoxAiContentAnswers

- src/elements/content-sidebar/BoxAISidebar.tsx
- src/elements/content-sidebar/SidebarPanels.js
Fixes the issue with Avatar image not showing when asking a question in AI Sidebar.
Before 
After
> fix(boxai-sidebar): Fix typo in avatarURL name

- .mergify.yml
> chore(mergify): add devin cla bypass

- .mergify.yml
> chore(mergify): fix devin typo

- src/elements/common/nav-button/NavButton.js
- src/elements/common/nav-button/__tests__/NavButton.test.js
- src/elements/content-sidebar/SidebarNav.js
- src/elements/content-sidebar/SidebarNavButton.js
- src/elements/content-sidebar/SidebarPanels.js
- src/elements/content-sidebar/__tests__/SidebarNav.test.js
- src/elements/content-sidebar/__tests__/SidebarPanels.test.js
- src/elements/content-sidebar/stories/BoxAISidebar.stories.tsx
Added option to display disabled tab nav item (button) without the corresponding sidebar.
This is used for Box AI Sidebar when the file is not compatible with AI features or there are permissions issues. In that case we want to not render Box AI Sidebar, however we still want to display the tab nav button with a proper tooltip.
This is controlled with `boxai.sidebar` feature.
> feat(content-sidebar): Option to render Box AI nav button disabled

- src/elements/content-sidebar/BoxAISidebar.tsx
- src/elements/content-sidebar/__tests__/BoxAISidebar.test.tsx
Using the up and down arrow keys for keyboard navigation while focused on suggested questions also changes the document page. 
Steps to Reproduce:
1. Focus on the suggested questions section.
2. Use the up or down arrow keys for navigation.
3. The page unexpectedly changes as well.
To prevent this behavior callback with `stopPropagation()` was provided
https://github.com/user-attachments/assets/85498897-9340-41e2-b2e8-8a3e3b41f7af
> fix(boxai-sidebar): Arrow Key Navigation on Suggested Questions

- src/utils/__tests__/uploads.test.js
- src/utils/uploads.js
I've updated `getFileLastModifiedAsISONoMSIfPossible()` to not accept negative timestamp values. Due to an [issue](https://issues.chromium.org/issues/393149335) in Chromium for Android, the `file.lastModified` and `file.lastModifiedAt` values are not being read properly from the file's metadata. `lastModified` is instead being read as `-11644473600`.
The existing logic does not handle this, and will attempt to create a date for any non-zero timestamp value. The downstream affect is that the [PlainUpload](https://github.com/box/box-ui-elements/blob/master/src/api/uploads/PlainUpload.js#L81) API will send `content_modified_at` as a negative timestamp. This is not allowed by the API, and results in a 400 response
```
{
"type": "error",
"status": 400,
"code": "bad_request",
"context_info": { …
```
> fix: remove negative timestamps from uploads

- src/elements/content-sidebar/BoxAISidebarContent.tsx
- src/elements/content-sidebar/__tests__/BoxAISidebar.test.tsx
- src/elements/content-sidebar/context/BoxAISidebarContext.ts
Added `recordAction` call to track Box AI Sidebar load event.
> feat(content-sidebar): Added recordAction call on Box AI Sidebar load

- src/elements/content-sidebar/BoxAISidebar.scss
- src/elements/content-sidebar/BoxAISidebar.tsx
- src/elements/content-sidebar/BoxAISidebarContent.tsx
- src/elements/content-sidebar/SidebarContent.scss
- src/elements/content-sidebar/SidebarNav.js
- src/elements/content-sidebar/SidebarNav.scss
- src/elements/content-sidebar/__tests__/BoxAISidebar.test.tsx
Provided additional UI fixes to the sidebar:
- Header horizontal line should go all the way across - apply to all sidebar tabs
- Update sidebar icons to fill icons
- Change icon for expand button
- Change SidebarNav icon sizes
> feat(boxai-sidebar): Additional UI fixes

- package.json
- src/constants.js
- src/elements/content-sidebar/MetadataInstanceEditor.tsx
- src/elements/content-sidebar/MetadataSidebarRedesign.tsx
- src/elements/content-sidebar/__tests__/MetadataSidebarRedesign.test.tsx
- src/elements/content-sidebar/__tests__/useSidebarMetadataFetcher.test.tsx
- src/elements/content-sidebar/hooks/useSidebarMetadataFetcher.ts
- src/elements/content-sidebar/stories/tests/MetadataSidebarRedesign-visual.stories.tsx
- yarn.lock
Passes down the error code into MetadataInstanceEditor if there's an error extracting suggestions.
> feat(metadata-sidebar): Use error code prop in MetadataInstanceEditor

- src/elements/content-sidebar/BoxAISidebarContent.tsx
Pass missing isFeedbackEnabled prop to IntelligenceModal component, so both chats have the same options
with this change
> fix(boxai-sidebar): Pass missing isFeedbackEnabled prop

- package.json
- src/elements/common/content-answers/ContentAnswersModal.tsx
- src/elements/common/content-answers/__tests__/ContentAnswers.test.tsx
- src/elements/common/content-answers/__tests__/ContentAnswersModal.test.tsx
- src/elements/content-preview/stories/tests/ContentPreview-visual.stories.js
- src/elements/content-sidebar/BoxAISidebarContent.tsx
- src/elements/content-sidebar/__tests__/BoxAISidebar.test.tsx
- src/elements/content-sidebar/stories/tests/BoxAISidebar-visual.stories.tsx
- yarn.lock
Update packages to their latest version.
Some fixes needs to be done at test level since Box AI went into a redesign that changed the style and copy of the text
> feat(box-ai): Update Shared packages versions

- src/elements/content-sidebar/BoxAISidebarContent.tsx
This change fixes not working `Stop response` button in Box AI Sidebar Modal.
> fix(content-sidebar): fix box ai modal stop response

- package.json
- src/elements/content-sidebar/MetadataInstanceEditor.tsx
- src/elements/content-sidebar/MetadataSidebarRedesign.tsx
- src/elements/content-sidebar/__tests__/MetadataInstanceEditor.test.tsx
- src/elements/content-sidebar/__tests__/isFileLargerThan.test.ts
- src/elements/content-sidebar/__tests__/isFileLargerThan.test.tsx
- src/elements/content-sidebar/utils/isFileLargerThan.ts
- yarn.lock
Check if file is bigger that 1MB and pass `isLargeFile`to `MetadataInstanceForm` so that Large File Warning Inline Notice can be displayed.
> feat(metadata-sidebar): Pass isLargeFile to MetadataInstanceForm

- src/elements/content-sidebar/SidebarPanels.js
- src/elements/content-sidebar/__tests__/SidebarPanels.test.js
This change makes the Box AI Sidebar to not be the default one anymore.
The Box AI tab button will still be the top one though.
> feat(content-sidebar): change Box AI to not be the default panel

- src/features/content-explorer/content-explorer-modal-container/ContentExplorerModalContainer.js
- src/features/content-explorer/content-explorer-modal-container/__tests__/ContentExplorerModalContainer.test.js
- src/features/content-explorer/content-explorer-modal/ContentExplorerModal.js
- src/features/content-explorer/content-explorer-modal/__tests__/ContentExplorerModal.test.js
- src/features/content-explorer/content-explorer/ContentExplorer.js
- src/features/content-explorer/content-explorer/__tests__/ContentExplorer.test.js
This PR adds `noItemsRenderer` prop to `ContentExplorerModalContainer`. When this prop is passed, it will be used instead of the default value. `noItemsRenderer` will only be rendered when `items` array is empty. This will be useful for specifying custom empty states.
This implements an idea suggested in https://github.com/box/box-ui-elements/pull/3241.
Here is an example:
To recreate this example, add the following line of code to `examples/src/ContentExplorerMultiSelectModalContainerExamples.js`:
```
noItemsRenderer={() => <p>This is a no items renderer</p>}
```
> feat(content-explorer-modal-container): add noItemsRenderer prop

- src/elements/content-sidebar/MetadataInstanceEditor.tsx
- src/elements/content-sidebar/MetadataSidebarRedesign.tsx
- src/elements/content-sidebar/__tests__/MetadataInstanceEditor.test.tsx
- src/elements/content-sidebar/stories/MetadataSidebarRedesign.stories.tsx
- src/elements/content-sidebar/stories/tests/MetadataSidebarRedesign-visual.stories.tsx
Get `isMetadataMultilevelTaxonomyFieldEnabled` value and pass it to `MetadataEditor` in order to control feature enablement. Feature flag is 100% off.
> feat(metadata-sidebar): Control Multilevel Taxonomy

- src/elements/common/item/ItemOptions.tsx
- src/elements/common/item/__tests__/ItemOptions.test.tsx
The extensibility feature for the row items ("More Options" button) in Content Explorer and Content Picker does not properly handle an empty state. e.g. if a developer passes in custom actions and utilizes the `type` or `filter` properties which results in an item with zero custom actions, it will still try to render the button with no dropdown menu items
This change will check if the filtered item actions list is empty and then return null so that the trigger button is not rendered.
> fix(item-options): render correctly when item actions are filtered

- src/elements/common/item-grid/ItemGrid.tsx
- src/elements/common/item-list/ItemList.tsx
- src/elements/common/item/ItemOptions.tsx
- src/elements/common/item/__tests__/ItemOptions.test.tsx
- src/elements/common/sub-header/Add.tsx
- src/elements/common/sub-header/Sort.tsx
- src/elements/common/theming/ThemingStyles.tsx
- src/elements/common/theming/types.ts
- src/elements/common/theming/useCustomTheming.ts
- src/elements/content-explorer/Content.tsx
- src/elements/content-explorer/ContentExplorer.tsx
- src/elements/content-explorer/__tests__/Content.test.tsx
- src/elements/content-explorer/stories/tests/ContentExplorer-visual.stories.js
Fixed table rendering by adding an empty cell when there is no ActionCell for the list view. Issue was noticeable when updating the background color of the table.
Added a `portalElement` which is passed down to the floating components to be used as a container for mounting. This prevents components like DropdownMenu from portal-ing outside of ContentExplorer. This allows for easier styling of the floating components.
Added a selector functionality to the theming. this allows elements to be individually themed without conflicting with other elements. This is not enabled in any of the elements yet.
> fix(content-explorer): improve theming feature

- src/elements/content-sidebar/__tests__/metadataTaxonomyFetcher.test.ts
- src/elements/content-sidebar/fetchers/metadataTaxonomyFetcher.ts
Due to API response change all resource attributes are now following lower_snake_case naming e.g. `display_name`. This affected `metadataTaxonomyNodeAncestorsFetcher` and we needed to accommodate that. We have to handle both `displayName` and `display_name` for now due release process.
**Before fix**
**After fix**
> fix(metadata-editor): Handle new taxonomy API

- src/elements/common/item/IconCell.tsx
- src/features/content-explorer/item-list/ItemListIcon.js
- src/features/content-explorer/item-list/__tests__/ItemListIcon.test.js
This PR adds default dimension to `ItemListIcon`. Without this, icons for `Archive` and `FolderArchive` would render with height and width set to `undefined`. While this did not matter on most browsers (e.g. Chrome), because there the size of the icon was read from `viewBox`, on Safari the icons would not be displayed.
To verify the change add the following to `ContentExplorerMultiSelectModalContainerExamples.js` (starting from line 55):
```
{
id: '7',
name: 'Top level archive',
type: 'folder',
archiveType: 'archive',
},
{
id: '8',
name: 'Folder in archive',
type: 'folder',
archiveType: 'folder_archive',
}
```
Before (browser is Safari):
After (browser is Safari):
> fix(content-explorer): Add default dimension to ItemListIcon

- package.json
- yarn.lock
resolve https://github.com/box/box-ui-elements/security/dependabot/259
> fix(ip): remove resolution

- src/constants.js
We need to add this header so that webp image reps will be generated by conversion. This is necessary for the doc first pages project for preview.
> feat(doc-first-pages): Add webp xrep header

- .storybook/typings.d.ts
- src/elements/content-explorer/Content.tsx
- src/elements/content-explorer/ContentExplorer.tsx
- src/elements/content-explorer/MetadataView.tsx
- src/elements/content-explorer/__tests__/Content.test.tsx
- src/elements/content-explorer/stories/tests/MetadataView-visual.stories.tsx
- src/elements/content-sidebar/stories/tests/ContentSidebar-visual.stories.tsx
Added `contentExplorer.metadataViewV2` feature flag 
Added VRTs for the new and the old metadata view
> feat(content-explorer): Add feature flag for MetadataViewList redesign

- src/elements/common/base.scss
Some Blueprint styles were not being applied because there are BUIE "base" styles that are taking priority. These base styles were used with the BUIE atomic components. But now that ContentExplorer is migrated to Blueprint, it should not use these base styles.
Compare the <ins>search bar</ins> in the below screenshots.
**Before**
**After**
> fix(content-explorer): remove base styles

- src/features/message-center/__tests__/MessageCenter.integration.test.js
- src/features/message-center/components/MessageCenter.js
In order to update header icon button to new design we need to get the content of the badge. This will be handled by buttonComponent that inside will be using Split flag to display the new buttons from Blueprint in EUA:
> feat(message-center): Pass badgeCount to ButtonComponent

- package.json
- yarn.lock
resolve https://github.com/box/box-ui-elements/security/dependabot/146 and https://github.com/box/box-ui-elements/security/dependabot/86
didnt see that the sass-lint used anywhere so decided to remove the dependency
> fix(sass-lint): Remove sass-lint

- .gitignore
- package.json
- scripts/cut_release.sh
Moved https://opensource.box.com/box-ui-elements/storybook -> https://opensource.box.com/box-ui-elements
> feat(opensource): update default route to use storybook

- .mergify.yml
> chore(mergify): update configuration
