src/components/ContentUploader/ContentUploader.js

Create new API instance once file is retried (needed because api.cancel() sets destroyed flag). Fixes #85.

Fix: Restart manual retries properly

---

build/publish.sh
build/release.sh

Have not seen an error in Preview yet from packages not being properly installed

Chore: Remove NPM install from release/publish scripts

---

README.md
build/locales.js
i18n/en-US.properties
package.json
src/components/ContentUploader/ContentUploader.js
src/components/ContentUploader/Footer.js
src/components/messages.js
src/constants.js
test/pseudo.html

Adds missing localizations
Adds test file for pseudo localization

Fix: Localization issue in ContentUploader

---

README.md
build/webpack.web.config.js
src/components/ContentPreview/ContentPreview.js
src/wrappers/ContentExplorer.js
src/wrappers/ContentPicker.js
src/wrappers/ContentPreview.js
src/wrappers/ContentTree.js
src/wrappers/ContentUploader.js
src/wrappers/ES6Wrapper.js
test/preview-react.html
test/preview.html

Fix: Multiple previews on the same page

---

src/util/LocalStore.js
src/util/__tests__/LocalStore-test.js

Local storage wrapper that falls back to an in memory store

New: LocalStore

---

src/components/ContentUploader/ContentUploader.js
src/components/ContentUploader/DroppableContent.js
src/components/ContentUploader/ItemList.js
src/components/Droppable/makeDroppable.js

Fixes: #117
Doesn't guarantee that other React 16 issues might not be there.

Fix: Remove refs from functional components

---

src/components/ContentExplorer/ContentExplorer.js
src/components/ContentPicker/ContentPicker.js
src/components/ContentUploader/ContentUploader.js
src/components/UploadDialog/UploadDialog.js

Fix: Default to 0 as the root folder for content uploader

---

src/components/ContentExplorer/PreviewDialog.js

Fix: Allow preview modal to close

---

src/api/uploads/MultiputPart.js
src/api/uploads/MultiputUpload.js
src/api/uploads/__tests__/MultiputUpload-test.js
src/flowTypes.js
src/util/Xhr.js
src/util/__tests__/Xhr-test.js
src/util/hex.js
src/util/webcrypto.js

- initial commit to port over MultiputUpload, MultiputPart

New: MultiputUpload part1

---

package.json
src/components/Breadcrumbs/BreadcrumbDropdown.js
src/components/Breadcrumbs/BreadcrumbDropdown.scss
src/components/Breadcrumbs/Breadcrumbs.js
src/components/Breadcrumbs/InlineBreadcrumbs.js
src/components/ContentExplorer/ContentExplorer.js
src/components/ContentExplorer/ItemList.js
src/components/ContentExplorer/moreOptionsCellRenderer.js
src/components/ContentPicker/ContentPicker.js
src/components/ContentPicker/ItemList.js
src/components/Item/ItemDetails.js
src/components/Item/nameCellRenderer.js
src/components/SubHeader/Add.js
src/components/SubHeader/Add.scss
src/components/SubHeader/Sort.js
src/components/SubHeader/Sort.scss
src/components/SubHeader/SubHeader.js
src/components/SubHeader/SubHeaderLeft.js
src/components/SubHeader/SubHeaderRight.js
src/components/_variables.scss
src/components/base.scss
test/explorer-no-react.html
yarn.lock

Remove global style overrides.
Tether drop down menus into the root element

Fix: Scope box-react-ui style overrides to box elements

---

src/api/PlainUpload.js
src/api/__tests__/PlainUpload-test.js
src/api/uploads/MultiputUpload.js
src/components/ContentUploader/ContentUploader.js

Update: support uploading new version

---

i18n/en-US.properties
package.json
src/components/ContentUploader/ContentUploader.js
src/components/ContentUploader/ItemList.js
src/components/ContentUploader/progressCellRenderer.js
src/components/messages.js
src/flowTypes.js
yarn.lock

New: error messages for failed upload items in ContentUploader

---

package.json
src/components/ContentSidebar/SidebarSkills.js
src/components/base.scss
src/constants.js
src/util/__tests__/fields-test.js
src/util/fields.js
test/preview.html
yarn.lock

Also include accessibility CSS from box-react-ui

Fix: Temporarily add back keyvalue cards from old metadata

---

build/build_locale.js
build/prod.js
build/webpack.config.js
package.json

Builds successfully within 11 minutes
https://jenkins.pod.box.net/job/Platform/job/UI%20Elements/job/Release/job/Build%20and%20Deploy%20Test/6/

Chore: accelerate prod build with worker-farm

---

src/components/ContentExplorer/ContentExplorer.js
src/components/ContentExplorer/PreviewDialog.js
src/components/ContentPreview/ContentPreview.js
src/components/ContentSidebar/ContentSidebar.js
src/components/ContentSidebar/DetailsSidebar.js
src/components/ContentSidebar/Sidebar.js
src/components/ContentSidebar/SidebarSkills.js
src/components/Keywords/Keyword.js
src/components/Keywords/Keywords.js
src/components/Timeline/Line.js
src/components/Timeline/Timeline.js
src/components/Timeline/Timelines.js
src/components/Transcript/Transcript.js
src/components/Transcript/TranscriptData.js
src/components/Transcript/TranscriptDialog.js
src/components/Transcript/__tests__/timeSliceUtils-test.js
src/components/Transcript/timeSliceUtils.js
src/constants.js
src/flowTypes.js
src/wrappers/ContentExplorer.js
src/wrappers/ContentPreview.js
src/wrappers/ContentSidebar.js
src/wrappers/ES6Wrapper.js
test/preview.html
test/sidebar.html

To track what skills are being clicked on.

New: Adding simple interaction events

---

src/api/File.js
src/api/Folder.js
src/api/Recents.js
src/api/Search.js
src/api/__tests__/File-test.js
src/api/__tests__/Folder-test.js
src/api/__tests__/Recents-test.js
src/api/__tests__/Search-test.js
src/components/ContentPreview/ContentPreview.js
src/components/ContentPreview/ContentPreview.scss
src/flowTypes.js
src/util/TokenService.js
src/util/Xhr.js
src/util/__tests__/TokenService-test.js
src/util/__tests__/fields-test.js
src/util/fields.js
test/preview.html

Fixing prefetching and caching issues.
Migrating token code to token service.
Adding method for checking valid box files.

Update: Preview sidebar api improvements

---

build/webpack.config.js
src/components/ContentSidebar/Sidebar.js
src/components/ContentSidebar/Skills/SidebarSkills.js
src/components/ContentSidebar/Skills/__tests__/skillUtils-test.js
src/components/ContentSidebar/Skills/skillUtils.js
src/flowTypes.js
test/preview.html

Also removes source map from production builds as the package size and build time was increasing too much.

Fix: Show skills even if one card is valid

---

src/components/ContentPreview/ContentPreview.js

Fix: Don't reference preview before its loaded

---

package.json
src/components/ContentPreview/ContentPreview.js
src/components/ContentSidebar/ContentSidebar.js
yarn.lock

Also fixes render method for sidebar
Updates box-react-ui

Fix: Do not lower case event.key

---

src/components/ContentUploader/progressCellRenderer.js

Fix: Remove upload progress bar when item is pending

---

src/constants.js

Chore: Updating preview version default

---

src/constants.js

This reverts commit 396438685307069372523cab767158f170d5d265.

Revert "Chore: Updating preview version default to v1.37.1 (#260)"

---

src/api/__tests__/APIFactory-test.js
src/api/__tests__/Users-test.js
src/components/ContentSidebar/__tests__/ContentSidebar-test.js

This PR adds tests relevant for https://github.com/box/box-ui-elements/pull/303

Chore: tests match new API additions. Tests for passing user obj

---

src/components/ContentExplorer/ContentExplorer.js
src/components/ContentExplorer/PreviewDialog.js
src/components/ContentPreview/ContentPreview.js

Fix: Properly forward onDownload from Content Explorer to Preview

---

i18n/en-US.properties
src/api/uploads/BaseUpload.js
src/api/uploads/MultiputPart.js
src/api/uploads/__tests__/MultiputPart-test.js
src/constants.js
src/util/Xhr.js
src/util/__tests__/Xhr-test.js
test/uploader.html

Resolves #204
Todo:
- Cleanup BaseUpload preflightErrorHandler

Chore: Refactor uploads to use axios

---

i18n/en-US.properties
src/components/messages.js

Fix: Typo in folder create error message

---

flow-typed/box-ui-elements.js
src/api/uploads/FolderUpload.js
src/api/uploads/FolderUploadNode.js
src/api/uploads/MultiputUpload.js
src/api/uploads/__tests__/FolderUpload-test.js
src/api/uploads/__tests__/FolderUploadNode-test.js
src/components/ContentUploader/ContentUploader.js
src/components/ContentUploader/DroppableContent.js
src/components/ContentUploader/OverallUploadsProgressBar.js
src/components/ContentUploader/UploadsManager.js
src/components/ContentUploader/__tests__/OverallUploadsProgressBar-test.js
src/components/ContentUploader/__tests__/__snapshots__/OverallUploadsProgressBar-test.js.snap
src/components/Droppable/makeDroppable.js
src/util/__tests__/uploads-test.js
src/util/uploads.js
test/uploader-window-view.html

New: drag and drop folder upload

---

i18n/en-US.properties
src/components/ContentSidebar/ActivityFeed/activity-feed/ActiveState.js
src/components/ContentSidebar/ActivityFeed/activity-feed/ActivityFeed.js
src/components/ContentSidebar/ActivityFeed/activity-feed/ActivityFeed.scss
src/components/ContentSidebar/ActivityFeed/activity-feed/__tests__/__snapshots__/ActivityFeed-test.js.snap
src/components/ContentSidebar/ActivityFeed/comment/Comment.scss
src/components/ContentSidebar/ActivitySidebar.js
src/components/ContentSidebar/ContentSidebar.js
src/components/ContentSidebar/Sidebar.js
src/components/messages.js
src/util/error.js

- Display error when feed items fail to load

Chore: Ignore failed feed items when an AF fetch call fails

---

src/api/uploads/BaseUpload.js
src/api/uploads/MultiputUpload.js
src/api/uploads/PlainUpload.js
src/api/uploads/__tests__/PlainUpload-test.js
src/components/ContentSidebar/ActivityFeed/activity-feed/ActivityFeed.js

Computes SHA1 and add to plain file upload for consistency checks.

Update: Compute SHA1 and add to plain file upload

---

src/components/ContentExplorer/ItemList.scss
src/components/ContentPicker/ItemList.scss
src/components/ContentSidebar/ContentSidebar.js
src/components/ContentSidebar/Sidebar.js
src/components/ContentSidebar/SidebarUtils.js
src/components/ContentSidebar/Skills/Transcript/EditingTranscriptRow.scss
src/components/ContentSidebar/Skills/Transcript/Transcript.js
src/components/ContentSidebar/__tests__/ContentSidebar-test.js
src/components/ContentSidebar/__tests__/Sidebar-test.js
src/components/ContentSidebar/__tests__/SidebarUtils-test.js
src/components/ContentSidebar/__tests__/__snapshots__/Sidebar-test.js.snap
test/preview-ie11.html
test/preview.html

Minor CSS and style fixes.
Minor fixes to transcript copy.
Fixing test files with new props style.

Fix: Skills/Metadata navigating logic

---

src/components/ContentSidebar/ActivityFeed/activity-feed/ActivityFeed.scss
src/components/ContentSidebar/ActivityFeed/approval-comment-form/ApprovalCommentForm.scss

Prevents placeholder text fro overflowing the text editor for tasks

Chore: Prevent overflow of DraftEditor-root

---

src/components/ContentUploader/UploadState.js
src/components/ContentUploader/__tests__/__snapshots__/UploadState-test.js.snap

Update: use new svg for ContentUploader empty state

---

src/components/ContentSidebar/DetailsSidebar.js
src/components/ContentSidebar/__tests__/__snapshots__/DetailsSidebar-test.js.snap

New: Rearranging access stats

---

examples/src/ContentExplorer/ContentExplorerExample.js
examples/src/ContentExplorer/ContentExplorerExample.scss
examples/src/withConfig.js
i18n/en-US.properties
package.json
src/components/ContentPreview/ContentPreview.js
src/components/ContentSidebar/ContentSidebar.js
src/components/ContentSidebar/MetadataSidebar.js
src/components/ContentSidebar/MetadataSidebar.scss
src/components/ContentSidebar/SidebarContent.js
src/components/ContentSidebar/SidebarContent.scss
src/components/ContentSidebar/__tests__/ContentSidebar-test.js
src/components/ContentSidebar/__tests__/__snapshots__/MetadataSidebar-test.js.snap
src/components/ContentSidebar/__tests__/__snapshots__/SidebarContent-test.js.snap
src/components/makeResponsive.js
src/components/messages.js
test/sidebar.html
yarn.lock

Improves sidebar toggling behavior
Fixes examples page with new file/folder ids
Upgrades box-react-ui peer dependency

Breaking: Metadata UI design fixes

---

src/components/ContentPreview/ContentPreview.js
src/components/ContentPreview/ContentPreview.scss
src/components/ContentPreview/PreviewLoading.js
src/components/ContentPreview/PreviewLoading.scss
src/components/ContentPreview/__tests__/ContentPreview-test.js
src/components/ContentPreview/__tests__/PreviewLoading-test.js
src/components/ContentPreview/__tests__/__snapshots__/PreviewLoading-test.js.snap
src/components/ContentSidebar/Sidebar.js
src/components/messages.js
src/constants.js

- Adds a loading screen while we are waiting for the files call
- Shows the error messaging/ UI after failed files call
- Uses preview's retry logic to time files call retries

New: ContentPreview error/loading states

---

README.md
build/prepush.sh
i18n/en-US.properties
package.json
src/api/File.js
src/api/__tests__/File-test.js
src/components/ContentPreview/ContentPreview.js
src/components/ContentPreview/ReloadNotification.js
src/components/ContentPreview/ReloadNotification.scss
src/components/ContentPreview/__tests__/ContentPreview-test.js
src/components/ContentPreview/__tests__/ReloadNotification-test.js
src/components/ContentPreview/__tests__/__snapshots__/ReloadNotification-test.js.snap
src/components/ContentSidebar/ContentSidebar.js
src/components/ContentSidebar/__tests__/ContentSidebar-test.js
src/components/base.scss
src/components/messages.js
test/preview.html

* Also adds a prepush script to build the project and add locales to prevent any missing locales in commit
* Adds a couple of missing locales

Update: Add notification for when a new preview is available

---

src/components/ContentSidebar/Skills/Faces/Face.scss

Only improves it a bit. Doesn't work in IE.

Fix: Improve skill image aspect ratio and centering

---

package.json
src/components/ContentUploader/ContentUploader.js
src/components/ContentUploader/UploaderUtils.js
src/components/ContentUploader/__tests__/ContentUploader-test.js
src/util/uploads.js
src/wrappers/ContentUploader.js

Fix: uploader falls back to regular upload API if chunked unsupported

---

flow-typed/box-ui-elements.js
src/api/AppIntegrations.js
src/api/OpenWith.js
src/api/__tests__/AppIntegrations-test.js
src/api/__tests__/OpenWith-test.js
src/components/OpenWith/OpenWith.js
test/openwith.html

- Adds a temporary prop to supply app integration data.

Chore: Consuming open with and app integration API endpoints

---

src/components/ContentSidebar/Skills/Keywords/EditableKeywords.js
src/components/ContentSidebar/Skills/Keywords/__tests__/EditableKeywords-test.js
src/components/ContentSidebar/Skills/Keywords/__tests__/__snapshots__/EditableKeywords-test.js.snap

Fix: Add composition mode for skill keywords

---

package.json
yarn.lock

Breaking: Update box-react-ui

---

src/components/ContentPreview/ContentPreview.js
src/components/ContentPreview/__tests__/ContentPreview-test.js
yarn.lock

Fix: ContentPreview navigation issues

---

src/api/File.js
src/api/__tests__/File-test.js
src/api/uploads/MultiputUpload.js
src/components/ContentSidebar/ContentSidebar.js
src/components/ContentSidebar/DetailsSidebar.js
src/components/ContentSidebar/__tests__/ContentSidebar-test.js
src/components/ContentSidebar/__tests__/DetailsSidebar-test.js
src/components/ContentSidebar/__tests__/Sidebar-test.js
src/components/ContentSidebar/__tests__/__snapshots__/DetailsSidebar-test.js.snap
src/components/ContentSidebar/__tests__/__snapshots__/Sidebar-test.js.snap
src/constants.js
test/sidebar.html
yarn.lock

Move details sidebar code from content sidebar to within details sidebar

Chore: Encapsulate details sidebar related code

---

src/api/uploads/PlainUpload.js
src/api/uploads/__tests__/PlainUpload-test.js
src/components/ContentUploader/ContentUploader.js

Also gives a prop to determine overwritten or not.

Fix: ContentUploads overwrite failure issue

---

src/components/ContentSidebar/DetailsSidebar.js
src/components/ContentSidebar/DetailsSidebar.scss
src/components/ContentSidebar/__tests__/__snapshots__/DetailsSidebar-test.js.snap

Fix: moved saved versions to be within File Properties section

---

src/components/ContentSidebar/ActivityFeed/activity-feed/ActivityFeed.scss
src/components/ContentSidebar/ActivityFeed/comment/Comment.scss

Update: changed styling for feed item comments

---

src/api/Metadata.js
src/api/__tests__/Metadata-test.js
src/constants.js

for users that don't have enterprise templates

Fix: Fetching enterprise templates should fail gracefully

---

i18n/en-US.properties
src/components/ContentSidebar/Skills/Faces/Faces.js
src/components/ContentSidebar/Skills/Faces/Faces.scss
src/components/ContentSidebar/Skills/Faces/__tests__/__snapshots__/Faces-test.js.snap
src/components/ContentSidebar/Skills/Keywords/Keywords.js
src/components/ContentSidebar/Skills/Keywords/Keywords.scss
src/components/ContentSidebar/Skills/Keywords/__tests__/__snapshots__/Keywords-test.js.snap
src/components/ContentSidebar/Skills/Transcript/Transcript.js
src/components/ContentSidebar/Skills/Transcript/Transcript.scss
src/components/ContentSidebar/Skills/Transcript/__tests__/__snapshots__/Transcript-test.js.snap
src/components/_variables.scss
src/components/messages.js
test/preview-react.html

Also fixed the color when the button is active

Fix: Add Tooltip to Skill Cards buttons

---

src/api/uploads/__tests__/BaseMultiput-test.js
src/api/uploads/__tests__/MultiputPart-test.js
src/api/uploads/__tests__/MultiputUpload-test.js
src/components/ContentSidebar/ActivityFeed/approval-comment-form/__tests__/ApprovalCommentForm-test.js
src/util/__tests__/Browser-test.js
src/util/__tests__/LocalStore-test.js
src/util/__tests__/uploads-test.js

Removes withData from leche out of all tests,
will submit another PR to remove leche from package.json

refactor(tests): remove withData out of testing suites

---

flow-typed/box-ui-elements.js
src/api/Metadata.js
src/api/__tests__/Metadata-test.js

fix(sidebar): Do not show hidden template fields

---

src/api/__tests__/Metadata-test.js

This reverts commit 2862d3d111814aa8b798fd88627aa6b524fe6c64.

fix: Revert "fix: Change ID in test (#690)"

---

src/api/uploads/PlainUpload.js
src/api/uploads/__tests__/PlainUpload-test.js

fix(uploader): send content_modified_at with plain upload

---

src/api/box-edit/ActiveXChannel.js
src/api/box-edit/BoxEdit.js
src/api/box-edit/BrowserUtils.js
src/api/box-edit/Channel.js
src/api/box-edit/ComServerClient.js
src/api/box-edit/HTTPChannel.js
src/api/box-edit/SafariChannel.js
src/api/box-edit/__tests__/ActiveXChannel-test.js
src/api/box-edit/__tests__/BoxEdit-test.js
src/api/box-edit/__tests__/Channel-test.js
src/api/box-edit/__tests__/ComServerClient-test.js
src/api/box-edit/__tests__/HTTPChannel-test.js
src/api/box-edit/__tests__/SafariChannel-test.js
src/api/box-edit/constants.js
src/api/box-edit/cookies.js
src/api/box-edit/index.js
src/api/box-edit/promise.js

Still working on migrating tests

chore(box-edit): Adding box-edit lib

---

.flowconfig
flow/ReactMeasure.js.flow

Till we can use 
https://github.com/flow-typed/flow-typed/pull/2015/files

fix: stub out react measure flow typed for now

---

package.json
src/components/ContentSidebar/SkillsSidebar.js
src/components/ContentSidebar/__tests__/SkillsSidebar-test.js

Fixes an issue with skills topics card where the order of deletion had an incorrect sort. Also refactors a bit for better testability.

fix(skills): issue in deletion of topics in skills

---

src/components/ContentSidebar/ActivityFeed/approval-comment-form/ApprovalCommentForm.scss

fix(sidebar): Fix task assignee overflow

---

src/api/Metadata.js
src/api/__tests__/Metadata-test.js

hidden templates should not be addable

fix(metadata): filter out hidden templates

---

src/components/pill-selector-dropdown/PillSelector.js
src/components/pill-selector-dropdown/PillSelector.scss
src/components/pill-selector-dropdown/PillSelectorDropdown.js
src/components/pill-selector-dropdown/README.md
src/components/pill-selector-dropdown/SuggestedPill.js
src/components/pill-selector-dropdown/SuggestedPillsRow.js
src/components/pill-selector-dropdown/SuggestedPillsRow.scss
src/components/pill-selector-dropdown/__tests__/PillSelectorDropdown-test.js
src/components/pill-selector-dropdown/__tests__/SuggestedPill-test.js
src/components/pill-selector-dropdown/__tests__/SuggestedPillRow-test.js
src/components/pill-selector-dropdown/__tests__/__snapshots__/PillSelector-test.js.snap
src/components/pill-selector-dropdown/__tests__/__snapshots__/PillSelectorDropdown-test.js.snap
src/components/pill-selector-dropdown/__tests__/__snapshots__/SuggestedPill-test.js.snap
src/components/pill-selector-dropdown/__tests__/__snapshots__/SuggestedPillRow-test.js.snap
src/components/pill-selector-dropdown/flowTypes.js
src/constants.js

- Adds support for suggested pills in PillSelectorDropdown so that suggested items can be handled in input forms
- Includes refactor of use of propTypes to flow and sass updates to conform to stylelint rules

feat: add suggested pills to PillSelectorDropdown

---

flow-typed/box-ui-elements.js
src/elements/common/Tooltip.js
src/elements/content-sidebar/AdditionalTab.js
src/elements/content-sidebar/AdditionalTab.scss
src/elements/content-sidebar/AdditionalTabs.js
src/elements/content-sidebar/AdditionalTabs.scss
src/elements/content-sidebar/ContentSidebar.js
src/elements/content-sidebar/Sidebar.js
src/elements/content-sidebar/SidebarNav.js
src/elements/content-sidebar/__tests__/AdditionalTab-test.js
src/elements/content-sidebar/__tests__/AdditionalTabs-test.js
src/elements/content-sidebar/__tests__/SidebarNav-test.js
src/elements/content-sidebar/__tests__/__snapshots__/AdditionalTab-test.js.snap
src/elements/content-sidebar/__tests__/__snapshots__/AdditionalTabs-test.js.snap
src/elements/content-sidebar/__tests__/__snapshots__/SidebarNav-test.js.snap
test/sidebar-additional-tabs.html

feat(sidebar): Render additional provided tabs

---

src/components/pill-selector-dropdown/PillSelector.js
src/components/pill-selector-dropdown/PillSelectorDropdown.js
src/components/pill-selector-dropdown/README.md
src/components/pill-selector-dropdown/SuggestedPillsRow.js
src/components/pill-selector-dropdown/flowTypes.js

Adds a new prop for filtering suggested data by a particular key. From the suggested mentioned in this PR by @priyajeet https://github.com/box/box-ui-elements/pull/911

feat(pill-selector-dropdown): add prop for filtering suggested pills

---

i18n/en-US.properties
src/features/unified-share-modal/ContactsField.js
src/features/unified-share-modal/messages.js

"Suggested:" => "Add:"
Also updated description and id to make sure it gets picked up by Moji.

chore(usm): Update copy for suggested collabs

---

i18n/en-US.properties
src/components/breadcrumb/Breadcrumb.js
src/components/breadcrumb/__tests__/Breadcrumb-test.js
src/components/breadcrumb/messages.js

Instead hardcode the translated value of breadcrumb

refactor(breadcrumb): remove unnecessary label prop

---

README.md

docs: update readme with correct wording

---

i18n/en-US.properties
src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkAccessDescription-test.js.snap
src/features/unified-share-modal/messages.js

fix(usm): Update people with link description

---

src/api/Feed.js
src/api/TaskCollaborators.js
src/api/TasksNew.js
src/api/__tests__/Feed-test.js
src/api/__tests__/TaskCollaborators-test.js
src/api/__tests__/TasksNew-test.js
src/elements/content-sidebar/activity-feed/comment/Comment.scss
src/elements/content-sidebar/activity-feed/task-new/Task.scss
src/elements/content-sidebar/activity-feed/task-new/TaskStatus.js

- fix pending state:
- add styles to task card to match comment pending state
- add CSS transition
- fix update logic of task assignment by refetching task to get updated status
- improve error handling of initial task create using try/catch in async/await context

fix(tasks): improve task update/create callbacks

---

src/api/TaskCollaborators.js
src/api/TaskLinks.js
src/api/TasksNew.js
src/api/__tests__/TaskCollaborators-test.js
src/api/__tests__/TaskLinks-test.js
src/api/__tests__/TasksNew-test.js

The API has been updated to use the standard
application/json type for Accept and Content-Type

fix(tasks): remove temporary headers

---

src/features/shared-link-settings-modal/SharedLinkSettingsModal.js
src/features/shared-link-settings-modal/__tests__/SharedLinkSettingsModal-test.js

feat(shared-link-settings-modal): add hideVanityNameSection prop

---

flow-typed/box-ui-elements.js
i18n/en-US.properties
src/api/Feed.js
src/api/Versions.js
src/api/__tests__/Feed-test.js
src/api/__tests__/Versions-test.js
src/elements/content-sidebar/activity-feed/version/Version.js
src/elements/content-sidebar/versions/VersionsItem.js
src/elements/content-sidebar/versions/VersionsItem.scss
src/elements/content-sidebar/versions/VersionsList.js
src/elements/content-sidebar/versions/VersionsSidebarContainer.js
src/elements/content-sidebar/versions/__tests__/VersionsItem-test.js
src/elements/content-sidebar/versions/__tests__/VersionsList-test.js
src/elements/content-sidebar/versions/__tests__/VersionsSidebarContainer-test.js
src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsItem-test.js.snap
src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsList-test.js.snap
src/elements/content-sidebar/versions/messages.js
test/integration/content-sidebar/ContentSidebar.e2e.test.js

feat(versions): Add current version to version history

---

i18n/en-US.properties
src/elements/content-sidebar/versions/VersionsItem.js
src/elements/content-sidebar/versions/VersionsItem.scss
src/elements/content-sidebar/versions/VersionsItemBadge.js
src/elements/content-sidebar/versions/VersionsItemBadge.scss
src/elements/content-sidebar/versions/__tests__/VersionsItemBadge-test.js
src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsItem-test.js.snap
src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsItemBadge-test.js.snap
src/elements/content-sidebar/versions/messages.js

Quick fix for accessibility of version number information for screen readers.

fix(versions): Add accessible text to version history item badge

---

src/constants.js

Makes Thumbnails Sidebar available by default to platform customers

chore(preview): Upgrade Preview to 2.3.0

---

src/features/unified-share-modal/SharedLinkAccessMenu.js
src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkAccessMenu-test.js.snap

fix(unified-share-modal): fix shared link permissions menu dropdown

---

i18n/en-US.properties
src/components/dropdown-menu/DropdownMenu.js
src/components/menu/Menu.js
src/elements/content-sidebar/versions/VersionsItem.js
src/elements/content-sidebar/versions/VersionsItem.scss
src/elements/content-sidebar/versions/VersionsItemActions.js
src/elements/content-sidebar/versions/VersionsItemActions.scss
src/elements/content-sidebar/versions/VersionsItemBadge.js
src/elements/content-sidebar/versions/VersionsItemBadge.scss
src/elements/content-sidebar/versions/VersionsList.js
src/elements/content-sidebar/versions/VersionsSidebar.js
src/elements/content-sidebar/versions/VersionsSidebarContainer.js
src/elements/content-sidebar/versions/__tests__/VersionsItem-test.js
src/elements/content-sidebar/versions/__tests__/VersionsItemActions-test.js
src/elements/content-sidebar/versions/__tests__/VersionsItemBadge-test.js
src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsItem-test.js.snap
src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsItemActions-test.js.snap
src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsItemBadge-test.js.snap
src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsList-test.js.snap
src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsSidebar-test.js.snap
src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsSidebarContainer-test.js.snap
src/elements/content-sidebar/versions/messages.js

feat(versions): Add version history item actions dropdown

---

src/features/list-view/ListView.js

fix(list-view): Fixed scrollbars that were doubled up

---

src/features/unified-share-modal/InviteePermissionsMenu.js

fix(unified-share-modal): check mark for default perm level

---

release.config.js

I think that's quite enough, thank you.

build(release): Disable auto-comments on released pull requests

---

src/elements/content-uploader/ContentUploader.js
src/elements/content-uploader/__tests__/ContentUploader-test.js

Matches the pre-react behavior of uploader.

fix(uploader): increase chunked upload threshold to 100MB

---

i18n/en-US.properties
src/elements/common/messages.js
src/elements/content-sidebar/AddTaskButton.js
src/elements/content-sidebar/AddTaskMenu.js
src/elements/content-sidebar/AddTaskMenu.scss
src/elements/content-sidebar/__tests__/AddTaskMenu-test.js
src/elements/content-sidebar/__tests__/__snapshots__/AddTaskMenu-test.js.snap
test/integration/content-sidebar/TaskForm.e2e.test.js

feat(tasks): Add new task menu with approval task type

---

src/elements/content-sidebar/activity-feed/comment/Comment.js
src/elements/content-sidebar/activity-feed/comment/__tests__/Comment-test.js
src/elements/content-sidebar/activity-feed/task-new/Task.js
src/elements/content-sidebar/activity-feed/task-new/Task.scss
src/elements/content-sidebar/activity-feed/task-new/__tests__/Task-test.js
src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/Task-test.js.snap

feat(tasks): Add task type icon to task creator avatar

---

i18n/en-US.properties
src/elements/common/messages.js
src/elements/content-sidebar/AddTaskMenu.js
src/elements/content-sidebar/AddTaskMenu.scss
src/elements/content-sidebar/__tests__/__snapshots__/AddTaskMenu-test.js.snap

feat(tasks): Add general task to task dropdown

---

src/components/radio/RadioButton.scss
src/components/radio/RadioGroup.js

Also forces render of radio children when radio group value changes.

fix(radio): styling when disabled

---

src/elements/content-sidebar/SidebarRoute.js

fix(sidebar): Set correct default render prop and avoid lodash import

---

src/components/select-button/SelectButton.js
src/components/select-button/SelectButton.scss
src/components/select-button/__tests__/SelectButton-test.js
src/components/select-button/__tests__/__snapshots__/SelectButton-test.js.snap
src/components/select-field/BaseSelectField.js
src/components/select-field/MultiSelectField.md
src/components/select-field/SingleSelectField.md
src/components/select-field/__tests__/BaseSelectField-test.js
src/components/select-field/__tests__/__snapshots__/BaseSelectField-test.js.snap

feat(select): add invalid/error state

---

src/elements/content-sidebar/activity-feed/task-form/TaskForm.js

- remove onBlur that causes month/yr select to lose focus
- allow manual date entry as designed

fix(tasks): task due date input handling

---

examples/colors.md
examples/styles/ColorExamples.scss
src/components/avatar/AvatarInitials.js
src/components/avatar/__tests__/AvatarInitials-test.js
src/components/count-badge/CountBadge.scss
src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/Assignees-test.js.snap
src/styles/_variables.scss
src/styles/variables.js
src/styles/variables.json

**Affected Components:**
CountBadge
Avatar

fix(colors): deprecate "coral" color

---

flow-typed/box-ui-elements.js
i18n/en-US.properties
src/elements/common/messages.js
src/elements/content-sidebar/activity-feed/comment/Comment.js
src/elements/content-sidebar/activity-feed/comment/__tests__/__snapshots__/Comment-test.js.snap
src/elements/content-sidebar/activity-feed/task-new/Assignees.js
src/elements/content-sidebar/activity-feed/task-new/Task.scss

feat(tasks): show completion timestamp for task assignees

---

src/utils/__tests__/datetime-test.js
src/utils/datetime.js

- convert ISO8601 long format (with zone description) to RFC3339 (fixed zone description format)

feat(datetime): Add date converter from ISO8601 to RFC3339

---

src/elements/content-sidebar/activity-feed/task-new/Task.scss
src/elements/content-sidebar/activity-feed/task-new/TaskStatus.js

- Design updated for the task status to no longer include an icon

feat(tasks): Update task status to not use an icon

---

src/icons/two-toned/IconLightning.js
src/icons/two-toned/README.md
src/icons/two-toned/_IconLightning.mixins.scss
src/icons/two-toned/__tests__/IconLightning-test.js
src/icons/two-toned/__tests__/__snapshots__/IconLightning-test.js.snap
yarn.lock

feat(icons): new lightning icon

---

conf/styleguide.config.js
src/features/classification/Classification.js
src/features/classification/Classification.scss
src/features/classification/ClassificationBadge.js
src/features/classification/ClassificationProperty.js
src/features/classification/README.md
src/features/classification/__tests__/Classification-test.js
src/features/classification/__tests__/__snapshots__/Classification-test.js.snap
src/styles/_variables.scss
src/styles/variables.js
src/styles/variables.json

New design for classification. Does not delete older files just yet.

feat(classification): new badge and layout

---

src/icons/two-toned/IconWorkflow.js
src/icons/two-toned/README.md
src/icons/two-toned/_IconWorkflow.mixins.scss
src/icons/two-toned/__tests__/IconWorkflow-test.js
src/icons/two-toned/__tests__/__snapshots__/IconWorkflow-test.js.snap

feat(icons): add workflow icon

---

i18n/en-US.properties
src/elements/common/messages.js
src/elements/content-sidebar/SidebarNav.js
src/elements/content-sidebar/SidebarNavButton.js
src/elements/content-sidebar/__tests__/SidebarNav-test.js
src/elements/content-sidebar/__tests__/__snapshots__/SidebarNav-test.js.snap

Moved from `nav` element to `div` with a tablist role

fix(sidebar): More semantically accessible tabs

---

src/icons/collections/IconCollections.js
src/icons/collections/IconCollectionsAdd.js
src/icons/collections/IconCollectionsFilled.js
src/icons/collections/__tests__/__snapshots__/IconCollections-test.js.snap
src/icons/collections/__tests__/__snapshots__/IconCollectionsAdd-test.js.snap
src/icons/collections/__tests__/__snapshots__/IconCollectionsFilled-test.js.snap

Fixes classname for 3 near brand new icons so that they fit the SUIT naming convention.

fix(icons): give collections Icons SUIT classNames

---

src/elements/content-sidebar/ActivitySidebar.js
src/elements/content-sidebar/AddTaskButton.js
src/elements/content-sidebar/TaskModal.js
src/elements/content-sidebar/__tests__/TaskModal-test.js
src/elements/content-sidebar/__tests__/__snapshots__/TaskModal-test.js.snap
src/elements/content-sidebar/activity-feed/task-form/TaskForm.js

remove task modal from add task button component so that it can be used in other contexts

refactor(content-sidebar): make TaskModal separate component

---

src/elements/content-sidebar/DetailsSidebar.js
src/elements/content-sidebar/DetailsSidebar.scss
src/elements/content-sidebar/SidebarVersions.js
src/elements/content-sidebar/SidebarVersions.scss
src/elements/content-sidebar/__tests__/__snapshots__/DetailsSidebar-test.js.snap
src/elements/content-sidebar/__tests__/__snapshots__/SidebarVersions-test.js.snap
src/elements/content-sidebar/_mixins.scss
src/styles/variables.js
src/styles/variables.json

fix(sidebar): padding on item properties versions

---

i18n/en-US.properties
src/constants.js
src/elements/common/messages.js
src/elements/content-sidebar/ActivitySidebar.js
src/elements/content-sidebar/AddTaskButton.js
src/elements/content-sidebar/TaskModal.js
src/elements/content-sidebar/__tests__/TaskModal-test.js
src/elements/content-sidebar/__tests__/__snapshots__/TaskModal-test.js.snap
src/elements/content-sidebar/activity-feed/comment/Comment.js
src/elements/content-sidebar/activity-feed/comment/__tests__/Comment-test.js
src/elements/content-sidebar/activity-feed/task-form/TaskForm.js
src/elements/content-sidebar/activity-feed/task-new/Task.js
src/elements/content-sidebar/activity-feed/task-new/__tests__/Task-test.js
src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/Task-test.js.snap
src/elements/content-sidebar/activity-feed/task-new/index.js

- enable read-only form for task details, showing the field values
- use edit mode to determine which fields are read only and to control submit
- update text for edit mode options

 feat(task-new): Add support for edit modal

---

src/components/pill-selector-dropdown/PillSelectorDropdown.js
src/components/pill-selector-dropdown/__tests__/PillSelectorDropdown-test.js
src/components/pill-selector-dropdown/__tests__/__snapshots__/PillSelectorDropdownField-test.js.snap
src/features/invite-collaborators-modal/__tests__/__snapshots__/InviteCollaboratorsModal-test.js.snap
src/features/unified-share-modal/ContactsField.js
src/features/unified-share-modal/EmailForm.js
src/features/unified-share-modal/UnifiedShareModal.js
src/features/unified-share-modal/__tests__/UnifiedShareModal-test.js
src/features/unified-share-modal/__tests__/__snapshots__/ContactsField-test.js.snap
src/features/unified-share-modal/__tests__/__snapshots__/UnifiedShareModal-test.js.snap
src/features/unified-share-modal/utils/__tests__/mergeContacts-test.js
src/features/unified-share-modal/utils/mergeContacts.js

- On pill creation, show external collabs domain name

feat(unified-share-modal): Show external collabs indicator

---

.mergify.yml
.npmignore
CODEOWNERS
README.md

Huge shoutout to @ConradJChan for doing the research on this integration!

build(mergify): Add configuration for mergify integration

---

i18n/en-US.properties
src/api/Feed.js
src/elements/common/messages.js
src/elements/content-sidebar/ActivitySidebar.js
src/elements/content-sidebar/AddTaskButton.js
src/elements/content-sidebar/TaskModal.js
src/elements/content-sidebar/__tests__/TaskModal-test.js
src/elements/content-sidebar/__tests__/__snapshots__/TaskModal-test.js.snap
src/elements/content-sidebar/activity-feed/task-form/TaskForm.js
src/elements/content-sidebar/activity-feed/task-form/__tests__/TaskForm-test.js
src/elements/content-sidebar/activity-feed/task-new/Task.js
src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/Task-test.js.snap

- Ability to edit and update Task `message` and `dueDate`. 
- Error handling if edit fails

feat(tasks-new): Edit task message and due date in TaskForm

---

i18n/en-US.properties
src/api/APIFactory.js
src/elements/common/messages.js
src/elements/content-sidebar/activity-feed/task-new/AssigneeList.js
src/elements/content-sidebar/activity-feed/task-new/AssigneeList.scss
src/elements/content-sidebar/activity-feed/task-new/Task.js
src/elements/content-sidebar/activity-feed/task-new/__tests__/AssigneeList-test.js
src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/Task-test.js.snap

Replacing avatar group with the new assignee list.

feat(tasks-new): add assignee list

---

flow-typed/box-ui-elements.js
src/api/Feed.js
src/api/__tests__/Feed-test.js
src/elements/content-sidebar/ActivitySidebar.js
src/elements/content-sidebar/activity-feed/activity-feed/ActiveState.js
src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.js
src/elements/content-sidebar/activity-feed/task-form/TaskForm.js
src/elements/content-sidebar/activity-feed/task-form/__tests__/TaskForm-test.js
src/elements/content-sidebar/activity-feed/task-new/Task.js
src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/Task-test.js.snap

- use `TaskCollabAssignee` for Task forms and in components
- use consistent error code for errors updating tasks
- additional tests and checks for data structures

feat(task-new): add ability to edit task assignees

---

src/features/header-flyout/HeaderFlyout.js
src/features/header-flyout/__tests__/__snapshots__/HeaderFlyout-test.js.snap

This fixes : https://jira.inside-box.net/browse/COLLAB-644

fix(header-flyout): ConstrainToWindow to fix IE11 scroll bug

---

i18n/en-US.properties
src/elements/content-sidebar/TaskModal.js

Remove comment that's no longer needed, and re-build translations file

fix(tasks-new): update docs and strings

---

package.json
yarn.lock

The bump to 0.19 24 days ago contained breaking changes

fix(deps): downgrade axios peer dep

---

i18n/en-US.properties
src/elements/content-sidebar/versions/VersionsGroup.js
src/elements/content-sidebar/versions/VersionsGroup.scss
src/elements/content-sidebar/versions/VersionsList.js
src/elements/content-sidebar/versions/VersionsList.scss
src/elements/content-sidebar/versions/VersionsSidebar.js
src/elements/content-sidebar/versions/VersionsSidebar.scss
src/elements/content-sidebar/versions/__tests__/VersionsGroup-test.js
src/elements/content-sidebar/versions/__tests__/VersionsSidebar-test.js
src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsGroup-test.js.snap
src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsItemActions-test.js.snap
src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsList-test.js.snap
src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsSidebar-test.js.snap
src/elements/content-sidebar/versions/messages.js
src/utils/datetime.js

feat(versions): Add version group headers based on relative date

---

i18n/en-US.properties
src/constants.js
src/elements/common/flowTypes.js
src/elements/common/messages.js
src/elements/content-preview/ContentPreview.js
src/elements/content-preview/PreviewLoading.js
src/elements/content-preview/PreviewLoading.scss
src/elements/content-preview/__tests__/ContentPreview-test.js
src/elements/content-preview/__tests__/PreviewLoading-test.js
src/elements/content-preview/__tests__/__snapshots__/PreviewLoading-test.js.snap

feat(preview): better message when blocked by a policy

---

src/components/pill-selector-dropdown/Pill.js
src/components/pill-selector-dropdown/PillSelector.js
src/components/pill-selector-dropdown/__tests__/Pill-test.js
src/components/pill-selector-dropdown/__tests__/__snapshots__/Pill-test.js.snap
src/styles/common/_pills.scss

fix(pill-selector-dropdown): disable pills when PillSelector is disabled

---

examples/src/features.js
i18n/en-US.properties
src/constants.js
src/elements/common/flowTypes.js
src/elements/common/messages.js
src/elements/common/sub-header/SubHeader.js
src/elements/common/sub-header/SubHeaderRight.js
src/elements/common/sub-header/SubHeaderRight.scss
src/elements/common/sub-header/ViewModeChangeButton.js
src/elements/common/sub-header/ViewModeChangeButton.scss
src/elements/content-explorer/Content.js
src/elements/content-explorer/ContentExplorer.js
src/elements/content-explorer/__tests__/ContentExplorer-test.js
test/explorer.html
test/integration/content-explorer/ContentExplorer.int.test.js

Majority of the lines are due to the snapshot for the jest test.  In the future, I'll submit the code and tests for a PR in separate commits.

feat(content-explorer): Add toggle button for grid view

---

scripts/cut_release.sh

so that build reaches release step faster.
Adds GIT_BRANCH env variable for semantic release
Adds github token to the git repo url

build: remove lint and test step temporarily

---

scripts/styleguide.config.js

docs(styleguide): apply box theme

---

src/features/classification/AddClassificationBadge.js
src/features/classification/ClassifiedBadge.js
src/features/classification/__tests__/__snapshots__/AddClassificationBadge-test.js.snap
src/features/classification/__tests__/__snapshots__/ClassifiedBadge-test.js.snap
src/features/classification/_mixins.scss

The final design is still being discussed, so I'm restoring the icons on the classification badge for now.

fix(classification): Restoring classification badge icons

---

src/elements/content-uploader/ItemAction.js
src/elements/content-uploader/__tests__/__snapshots__/ItemAction-test.js.snap

Adding target for resin for canceling uploads.

 fix(uploads): resin for canceling uploads

---

src/styles/common/_buttons.scss

This reverts commit a6989a037f9517d488d2d05554001a5846fc5f7a.

fix(button): revert remove horizontal margin from buttons (#1362)

---

src/icons/general/IconSmallClose.js
src/icons/general/__tests__/__snapshots__/IconSmallClose-test.js.snap

This one involves a color change from design to a slightly lighter gray 
=> d3d3d3

refactor: swap SEESEE for bdlGray20

---

src/features/unified-share-modal/UnifiedShareModal.js
src/features/unified-share-modal/UnifiedShareModal.scss
src/features/unified-share-modal/UnifiedShareModalTitle.js
src/features/unified-share-modal/__tests__/UnifiedShareModal-test.js
src/features/unified-share-modal/__tests__/UnifiedShareModalTitle-test.js
src/features/unified-share-modal/__tests__/__snapshots__/UnifiedShareModal-test.js.snap
src/features/unified-share-modal/__tests__/__snapshots__/UnifiedShareModalTitle-test.js.snap

feat(unified-share-modal): show classification for the file

---

src/components/pill-selector-dropdown/PillSelectorDropdownField.js
src/components/pill-selector-dropdown/__tests__/PillSelectorDropdownField-test.js

Also fixes a few flow types and defaulting

fix(pill-selector): expose onInput to trap input

---

src/elements/common/header/Header.scss

Resolves https://github.com/box/box-ui-elements/issues/546.

fix(search): Remove rounded corners for ContentExplorer search

---

src/elements/content-explorer/ContentExplorer.js
src/elements/content-explorer/ShareDialog.scss
src/elements/content-explorer/__tests__/ContentExplorer-test.js
test/integration/content-explorer/ContentExplorer.int.test.js

fix(explorer): fetch shared link on demand

---

src/elements/common/async-load/AsyncError.js
src/elements/common/async-load/AsyncLoad.js
src/elements/common/async-load/__tests__/AsyncError-test.js
src/elements/common/async-load/__tests__/AsyncLoad-test.js
src/elements/common/async-load/__tests__/__snapshots__/AsyncError-test.js.snap
src/elements/common/async-load/__tests__/__snapshots__/AsyncLoad-test.js.snap

refactor(async): Update async load helper to forward refs

---

examples/src/features.js
flow-typed/box-ui-elements.js
src/api/Feed.js
src/common/types/tasks.js
src/components/checkbox/Checkbox.scss
src/constants.js
src/elements/content-sidebar/ActivitySidebar.js
src/elements/content-sidebar/__tests__/ActivitySidebar-test.js
src/elements/content-sidebar/__tests__/__snapshots__/ActivitySidebar-test.js.snap
src/elements/content-sidebar/activity-feed/task-form/TaskForm.js
src/elements/content-sidebar/activity-feed/task-form/TaskForm.scss
src/elements/content-sidebar/activity-feed/task-form/__tests__/TaskForm-test.js
src/elements/content-sidebar/activity-feed/task-new/Task.js
src/elements/content-sidebar/activity-feed/task-new/__tests__/Task-test.js
src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/Task-test.js.snap

feat(tasks): add any/all checkbox

---

src/elements/content-preview/ContentPreview.js
src/elements/content-sidebar/ActivitySidebar.js
src/elements/content-sidebar/ContentSidebar.js
src/elements/content-sidebar/DetailsSidebar.js
src/elements/content-sidebar/MetadataSidebar.js
src/elements/content-sidebar/README.md
src/elements/content-sidebar/Sidebar.js
src/elements/content-sidebar/SidebarPanels.js
src/elements/content-sidebar/SkillsSidebar.js
src/elements/content-sidebar/__tests__/ActivitySidebar-test.js
src/elements/content-sidebar/__tests__/ContentSidebar-test.js
src/elements/content-sidebar/__tests__/DetailsSidebar-test.js
src/elements/content-sidebar/__tests__/SkillsSidebar-test.js
src/elements/content-sidebar/versions/VersionsSidebarContainer.js
src/elements/content-sidebar/versions/__tests__/VersionsSidebarContainer-test.js
src/elements/wrappers/ContentSidebar.js

Provides mechanism to trigger a refresh of the ContentSidebar active panel

feat(sidebar): programmatic refresh

---

i18n/en-US.properties
src/elements/common/messages.js
src/elements/content-open-with/ContentOpenWith.scss
src/elements/content-open-with/OpenWithDropdownMenuItem.js
src/elements/content-open-with/__tests__/OpenWithDropdownMenuItem-test.js
src/elements/content-open-with/__tests__/__snapshots__/OpenWithDropdownMenuItem-test.js.snap

fix(open-with): better error messaging

---

package.json
scripts/styleguide.config.js
src/elements/content-preview/ContentPreview.js
src/elements/content-sidebar/ContentSidebar.js
src/elements/content-sidebar/Sidebar.js
src/elements/content-sidebar/__tests__/Sidebar-test.js
test/integration/content-preview/ContentPreview.e2e.test.js

I also added some browser-based tests for the auto-open feature to hopefully avoid similar issues in the future.

fix(sidebar): Fix sidebar not auto-opening for large viewports

---

src/features/classification/AddClassificationBadge.js
src/features/classification/ClassifiedBadge.js
src/features/classification/__tests__/__snapshots__/AddClassificationBadge-test.js.snap
src/features/classification/__tests__/__snapshots__/ClassifiedBadge-test.js.snap
src/icons/general/IconSecurityClassification.js
src/icons/general/IconSecurityClassification.md
src/icons/general/__tests__/IconSecurityClassification-test.js
src/icons/general/__tests__/__snapshots__/IconSecurityClassification-test.js.snap

feat(classification): change icon for classify/classification action

---

src/elements/content-uploader/ContentUploader.js
src/elements/content-uploader/__tests__/ContentUploader-test.js

fix(uploads): cancelling in-progress tasks does not start pending ones

---

i18n/en-US.properties
src/elements/content-sidebar/activity-feed/task-new/messages.js

Changed string for task completed rule icon according to design (now spans 2 lines for tooltip)

fix(task): string for task completed rule icon

---

src/common/types/core.js
src/components/inline-error/InlineError.js
src/components/inline-error/README.md
src/components/inline-error/__tests__/InlineError-test.js
src/components/inline-error/__tests__/__snapshots__/InlineError-test.js.snap
src/components/inline-notice/InlineNotice.js
src/components/inline-notice/README.md
src/components/inline-notice/__tests__/InlineNotice-test.js
src/styles/common/_inline-notifications.scss

fix(inlinenotice): update to box design standard

---

src/elements/content-sidebar/activity-feed/task-form/TaskForm.js
src/elements/content-sidebar/activity-feed/task-form/__tests__/TaskForm-test.js

- track assignee input state to show error when input has text but no dropdown pill matched
- make sure first pill option is selected automatically

fix(tasks): assignee input field interactions

---

src/elements/content-uploader/ContentUploader.js
src/features/metadata-instance-editor/Instance.js

Removed logic gate from newly implemented componentDidUpdate in contentUploader
Fix comparison in metadata instance

fix(uploads): Fix contentUploader and metadataInstance

---

src/components/breadcrumb/Breadcrumb.js

-Fix flow issue of missing import

fix(breadcrumb): add missing import

---

package.json

build: enable source maps for production

---

src/styles/common/_typography.scss
src/styles/constants/_typography.scss
src/styles/mixins/_typography.scss
src/styles/variables.js
src/styles/variables.json

Adding new mixins for upcoming font changes

style: global font size change to 14px

---

src/components/media/Media.scss
src/elements/content-sidebar/activity-feed/task-new/AssigneeDetails.js
src/elements/content-sidebar/activity-feed/task-new/AssigneeDetails.scss
src/elements/content-sidebar/activity-feed/task-new/Task.scss
src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/AssigneeDetails.test.js.snap

fix(feed): Task assignee names not truncating IE11

---

src/icons/general/IconFolderTree.js
src/icons/general/IconFolderTree.md
src/icons/general/__tests__/IconFolderTree.test.js

feat(icons): add IconFolderTree icon

---

package.json
yarn.lock

This upgrade includes a switch to Terser internally in webpack for dev

build(webpack): Upgrade webpack to 4.41.2

---

release.config.js

speculating that for some reason it still wants it

build: add back release branch in config

---

src/constants.js

Preview has been updated to use the new file icons.

feat(preview): Update default preview version to 2.26.1

---

src/elements/content-uploader/ContentUploader.js
src/elements/content-uploader/README.md

Partially reverting the revert. The regression was a false positive.

feat(content-uploader): batch onComplete and add onResume prop

---

src/elements/content-explorer/ItemList.js
src/elements/content-explorer/ItemList.scss
src/elements/content-picker/ItemList.js
src/elements/content-picker/ItemList.scss
src/elements/content-uploader/ItemList.js
src/elements/content-uploader/ItemList.scss

- that breaks module resolution in parceljs based apps

fix(css): Replace tilde imports

---

i18n/en-US.properties
src/components/badge/TrialBadge.js
src/components/badge/__tests__/TrialBadge.test.js
src/components/badge/__tests__/__snapshots__/TrialBadge.test.js.snap
src/components/badge/index.js
src/components/badge/messages.js

Adds a Trial Badge component in a similar vein as Beta Badge.

feat(badge): Add new Trial Badge component

---

.mergify.yml

ci(mergify): Add PR title check

---

package.json
yarn.lock

Basic Perf improvements locally
Jest 24
```
Cold: 126s
Warm: 96s
```
Jest 25
```
Cold: 104s
Warm: 66s
```

chore(jest): Upgrade jest to 25.1.0

---

src/components/nudge/Nudge.scss

fix(nudge): update css height property

---

src/components/index.ts
src/components/label-pill/LabelPill.scss
src/components/label-pill/LabelPill.stories.md
src/components/label-pill/LabelPill.stories.tsx
src/components/label-pill/LabelPill.tsx
src/components/label-pill/LabelPillIcon.tsx
src/components/label-pill/LabelPillText.tsx
src/components/label-pill/__tests__/LabelPill.test.tsx
src/components/label-pill/__tests__/__snapshots__/LabelPill.test.tsx.snap
src/components/label-pill/index.ts

feat(label-pill): add LabelPill component

---

src/components/text-input-with-copy-button/TextInputWithCopyButton.js
src/components/text-input-with-copy-button/__tests__/TextInputWithCopyButton.test.js

bug-fix: clicks on URL within USM should select all

fix(textinputwithcopybutton): clicks on URL within USM should select all

---

src/components/avatar/Avatar.scss
src/components/checkbox/Checkbox.scss
src/components/collapsible/Collapsible.scss
src/components/dropdown-menu/MenuToggle.scss
src/components/nav-sidebar/NavSidebar.scss
src/components/toggle/Toggle.scss
src/elements/content-sidebar/SidebarSection.scss
src/elements/content-sidebar/skills/faces/Face.scss
src/features/quick-search/QuickSearch.scss
src/features/virtualized-table/VirtualizedTable.scss
src/styles/_variables.scss
src/styles/common/_forms.scss
src/styles/common/_tables.scss
src/styles/constants/_animation.scss
src/styles/mixins/_animation.scss
src/styles/variables.js
src/styles/variables.json
src/styles/variables.ts

updated `transform` animations in this PR

refactor(style): add standard animation values with example usage

---

src/components/label-pill/LabelPill.scss
src/components/label-pill/LabelPill.stories.tsx
src/components/label-pill/LabelPill.tsx
src/components/label-pill/LabelPillIcon.tsx
src/components/label-pill/LabelPillText.tsx
src/components/label-pill/__tests__/__snapshots__/LabelPill.test.tsx.snap

- add size (large, regular) prop
- better support for react and css composition:
- custom classnames allowed for all subcomponents
- lower specificity for style overrides

feat(label-pill): size options and composition fixes

---

src/components/avatar/Avatar.js.flow
src/components/avatar/Avatar.scss
src/components/avatar/Avatar.stories.tsx
src/components/avatar/Avatar.tsx
src/components/avatar/__tests__/Avatar.stories.test.tsx
src/components/avatar/__tests__/Avatar.test.tsx

- add "small" size
- prevent flexbox parents from distorting shape of avatar

feat(avatar): size options and composition fixes

---

src/components/label-pill/LabelPill.scss
src/components/label-pill/LabelPillIcon.tsx
src/components/label-pill/__tests__/__snapshots__/LabelPill.test.tsx.snap

Updating LabelPill css and icon size

fix(label-pill): updating labelpill css and icon size

---

src/components/radio/RadioGroupField.js.flow
src/components/radio/RadioGroupField.tsx
src/components/radio/__tests__/__snapshots__/RadioGroupField.test.tsx.snap

User should be able to focus/select next radio buttons in group using arrows keys.

fix(formik): fix lost focus on radio buttons

---

.storybook/preview-body.html
src/elements/content-sidebar/stories/ContentSidebar.notes.md
src/elements/content-sidebar/stories/ContentSidebar.stories.js
src/elements/content-uploader/stories/ContentUploader.notes.md
src/elements/content-uploader/stories/ContentUploader.stories.js

* Migrate ContentSidebar to Storybook and also add style overrides
* Migrate ContentUploader to Storybook and also add style overrides
* Add style overrides for ContentPreview

docs(storybook): Migrate content sidebar and content uploader

---

src/features/classification/security-controls/SecurityControls.js
src/features/classification/security-controls/SecurityControls.scss
src/features/classification/security-controls/SecurityControlsItem.js
src/features/classification/security-controls/SecurityControlsItem.scss
src/features/classification/security-controls/SecurityControlsModal.js
src/features/classification/security-controls/__tests__/SecurityControls.test.js
src/features/classification/security-controls/__tests__/SecurityControlsItem.test.js
src/features/classification/security-controls/__tests__/__snapshots__/SecurityControls.test.js.snap
src/features/classification/security-controls/__tests__/__snapshots__/SecurityControlsItem.test.js.snap
src/features/classification/security-controls/__tests__/__snapshots__/SecurityControlsModal.test.js.snap

feat(classification): Remove shield icon from security controls

---

src/features/left-sidebar/LeftSidebarLinkCallout.js
src/features/left-sidebar/styles/LeftSidebarLinkCallout.scss

Make the `tether` props customizable for different navigation types.

refactor(left-nav): make tether position props

---

src/icon/line/ClassificationBadge16.js.flow
src/icon/line/ClassificationBadge16.stories.tsx
src/icon/line/ClassificationBadge16.tsx

Importing the classification badge icon from the assets repo.

feat(Classification): Adding classification badge icon

---

src/styles/__tests__/theme.test.js
src/styles/theme.js
src/utils/__tests__/__snapshots__/createTheme.test.js.snap
src/utils/createTheme.js
src/utils/createTheme.stories.js

- Adjusting the scroll shadow values to better match the left nav values.
- Expose theme's `colorRange` in a `_debug` object for design feedback.
- Improve `theme` storybook knobs for better testing.

fix(theme): Adjusting scroll shadow value. Improving theme storybook

---

i18n/en-US.properties
src/features/shared-link-settings-modal/AllowDownloadSection.js
src/features/shared-link-settings-modal/SharedLinkSettingsModal.js
src/features/shared-link-settings-modal/__tests__/AllowDownloadSection.test.js
src/features/shared-link-settings-modal/__tests__/__snapshots__/AllowDownloadSection.test.js.snap
src/features/shared-link-settings-modal/messages.js
src/features/unified-share-modal/SharedLinkAccessMenu.js
src/features/unified-share-modal/UnifiedShareModal.js
src/features/unified-share-modal/__tests__/SharedLinkAccessMenu.test.js
src/features/unified-share-modal/__tests__/UnifiedShareModal.test.js
src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkAccessMenu.test.js.snap
src/features/unified-share-modal/__tests__/__snapshots__/UnifiedShareModal.test.js.snap
src/features/unified-share-modal/messages.js

Introduce a new behavior where sharing is block due to a security
policy

feat(usm): Add support for sharing block message

---

src/utils/webcrypto.js

noop commit to fix release of d91f2a6
BREAKING CHANGE: add js-sha1 package peer dependency

fix(upload): fallback sha1 calculation for IE11 using new package

---

src/elements/common/annotator-context/__tests__/withAnnotations.test.tsx
src/elements/common/annotator-context/types.ts
src/elements/common/annotator-context/withAnnotations.tsx
src/elements/common/annotator-context/withAnnotatorContext.tsx
src/elements/content-preview/ContentPreview.js
src/elements/content-preview/__tests__/ContentPreview.test.js

feat(annotations): handle annotator events

---

i18n/en-US.properties
src/components/select-field/BaseSelectField.js
src/components/select-field/MultiSelectField.js
src/components/select-field/MultiSelectField.md
src/components/select-field/SelectField.js
src/components/select-field/SelectField.scss
src/components/select-field/SingleSelectField.js
src/components/select-field/SingleSelectField.md
src/components/select-field/__tests__/BaseSelectField.test.js
src/components/select-field/__tests__/MultiSelectField.test.js
src/components/select-field/__tests__/SingleSelectField.test.js
src/components/select-field/messages.js
src/features/query-bar/components/filter/Condition.js

**SingleSelectField**
**MultiSelectField**

feat: add clear option to BaseSelectField

---

.eslintrc.js
src/elements/common/annotator-context/__tests__/withAnnotations.test.tsx
src/elements/common/annotator-context/types.ts
src/elements/common/annotator-context/withAnnotations.tsx
src/elements/content-preview/ContentPreview.js
src/elements/content-preview/__tests__/ContentPreview.test.js

* Move event listener setup to withAnnotations
* Update ContentPreview to only listen for annotator event
* Update tests and types
* Add eslint rule for explicit-any on rest args only

feat(annotations): Move annotator event listener

---

src/components/select-field/MultiSelectField.js
src/components/select-field/SingleSelectField.js
src/components/select-field/__tests__/MultiSelectField.test.js
src/components/select-field/__tests__/SingleSelectField.test.js

-use cloneDeep to make sure that we aren't updating the passed in object

Fix duplicate clear options

---

src/elements/content-sidebar/Sidebar.js
src/elements/content-sidebar/__tests__/Sidebar.test.js

* route back to url prefix instead of '/'

fix(annotations): update url for prefix

---

package.json
src/elements/common/annotator-context/__tests__/withAnnotations.test.tsx
src/elements/common/annotator-context/withAnnotations.tsx
src/elements/content-preview/ContentPreview.js
src/elements/content-preview/__tests__/ContentPreview.test.js
src/elements/content-sidebar/ActivitySidebar.js
src/elements/content-sidebar/Sidebar.js
src/elements/content-sidebar/SidebarPanels.js
src/elements/content-sidebar/__tests__/Sidebar.test.js
yarn.lock

feat(annotations): Reflect deeplink annotations on hard load

---

src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.scss
src/elements/content-sidebar/activity-feed/annotations/AnnotationActivity.scss

* Fix annotation card vertical shifting on focus
* Make pending cards non-interactive

fix(annotations): fix styling for annotation cards

---

src/features/classification/Classification.js
src/features/classification/ClassifiedBadge.js
src/features/classification/README.md
src/features/classification/__tests__/__snapshots__/Classification.test.js.snap
src/features/classification/__tests__/__snapshots__/ClassifiedBadge.test.js.snap
src/features/classification/__tests__/utils.test.js
src/features/classification/classificationColorsMap.js
src/features/classification/index.js
src/features/classification/security-controls/SecurityControls.js
src/features/classification/security-controls/SecurityControlsModal.js
src/features/classification/security-controls/__tests__/__snapshots__/SecurityControlsModal.test.js.snap
src/features/classification/utils.js
src/features/security/SecurityBadge.js
src/features/security/SecurityBadge.scss
src/features/security/__tests__/__snapshots__/SecurityBadge.test.js.snap
src/features/security/_mixins.scss
src/features/unified-share-modal/UnifiedShareModalTitle.js
src/features/unified-share-modal/__tests__/UnifiedShareModalTitle.test.js
src/icons/general/IconSecurityClassification.tsx
src/icons/general/__tests__/__snapshots__/IconSecurityClassification.test.tsx.snap
src/styles/constants/_layout.scss
src/styles/variables.js
src/styles/variables.json
src/styles/variables.ts

Moves Classification labels to the new design with a single color and larger border radius.

feat(classification): New classification badge design

---

src/components/menu/SubmenuItem.tsx

Add callback function whenever submenu opens.

feat(menu): Add onOpen prop to SubmenuItem

---

src/api/Feed.js
src/api/__tests__/Feed.test.js
src/elements/common/annotator-context/__tests__/withAnnotations.test.tsx
src/elements/common/annotator-context/__tests__/withAnnotatorContext.test.tsx
src/elements/common/annotator-context/types.ts
src/elements/common/annotator-context/withAnnotations.tsx
src/elements/common/annotator-context/withAnnotatorContext.tsx
src/elements/content-sidebar/ActivitySidebar.js
src/elements/content-sidebar/__tests__/ActivitySidebar.test.js
src/elements/content-sidebar/__tests__/__snapshots__/ActivitySidebar.test.js.snap
src/elements/content-sidebar/activity-feed/activity-feed/ActiveState.js
src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.js
src/elements/content-sidebar/activity-feed/annotations/AnnotationActivity.js

* Add deleteAnnotation handler
* Add emitting function for annotation removal

feat(annotations): Add delete flow

---

src/features/unified-share-modal/ContactsField.js
src/features/unified-share-modal/__tests__/__snapshots__/ContactsField.test.js.snap

- use round pills in the modal form instead of the regular pills

feat(unified-share-modal): enable round pills

---

src/components/tab-view/TabViewPrimitive.js
src/components/tab-view/__tests__/TabViewPrimitive.test.js

fix(tab): tab content should not receive keyboard focus

---

src/components/radar/RadarAnimation.stories.tsx
src/components/radar/RadarAnimation.tsx
src/components/radar/__tests__/RadarAnimation.test.tsx

feat(radaranimation): add offset prop

---

src/api/Feed.js
src/api/__tests__/Feed.test.js
src/constants.js
src/elements/common/annotator-context/__tests__/withAnnotations.test.tsx
src/elements/common/annotator-context/withAnnotations.tsx
src/elements/content-preview/ContentPreview.js
src/elements/content-preview/__tests__/ContentPreview.test.js
src/elements/content-sidebar/ActivitySidebar.js
src/elements/content-sidebar/__tests__/ActivitySidebar.test.js

feat(annotations): Handle API fetch error

---

src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.scss
src/elements/content-sidebar/activity-feed/version/Version.scss

fix(activityfeed): 16px margin around version activity

---

src/components/search-form/SearchForm.js

Replacing old search and clear icons in SearchForm with new assets

fix(searchform): update icons with latest assests

---

.github/semantic.yml
.mergify.yml

Add new commitlint bot config.
Rules:
1. PR title must be semantic (required since we squash merge)
2. At least 1 commit has a semantic title

ci(commitlint): Add semantic-pull-request bot config

---

src/api/Base.js
src/api/uploads/BaseUpload.js
src/api/uploads/UploadsReachability.js
src/api/uploads/__tests__/BaseUpload.test.js
src/api/uploads/__tests__/UploadsReachability.test.js
src/elements/content-uploader/ContentUploader.js

Adds upload fallback logic to both PlainUploads and MultiputUploads

feat(uploads): add upload fallback logic 

---

src/elements/common/breadcrumbs/Breadcrumbs.js
src/elements/common/breadcrumbs/__tests__/Breadcrumbs.test.js

fix(explorer): All Files breadcrumb localization

---

src/components/flyout/Flyout.scss

feat(flyout): remove styles for flyout arrows

---

src/components/contact-datalist-item/ContactDatalistItem.js
src/components/contact-datalist-item/__tests__/ContactDatalistItem.test.js
src/components/pill-selector-dropdown/PillSelectorDropdown.js
src/components/pill-selector-dropdown/RoundPill.js
src/components/pill-selector-dropdown/__tests__/RoundPill.test.js
src/components/pill-selector-dropdown/__tests__/__snapshots__/RoundPill.test.js.snap

Introduces handling of promises in RoundPill and ContactDatalistItem for getting the avatar url string.

feat(pill-styling): support for pill styling updates in activity sidebar

---

src/icon/fill/Checkmark16.js.flow
src/icon/fill/Checkmark16.stories.tsx
src/icon/fill/Checkmark16.tsx
src/icon/fill/Megaphone20.js.flow
src/icon/fill/Megaphone20.stories.tsx
src/icon/fill/Megaphone20.tsx
src/icon/fill/Picture16.js.flow
src/icon/fill/Picture16.stories.tsx
src/icon/fill/Picture16.tsx

feat(assets): update assets to latest from design

---

src/icon/fill/Ribbon16.js.flow
src/icon/fill/Ribbon16.stories.tsx
src/icon/fill/Ribbon16.tsx

feat(assets): Add ribbon icon asset

---

i18n/en-US.properties
src/elements/common/messages.js

fix(uploads): update message for when package file uploads fail

---

src/common/types/core.js
src/constants.js
src/features/unified-share-modal/utils/__mocks__/USMMocks.js
src/features/unified-share-modal/utils/__tests__/convertData.test.js
src/features/unified-share-modal/utils/convertData.js

Sorting by name and filtering out inactive users so the invite collab autofill matches the webapp's behavior

fix(content-sharing): sort contacts and filter inactive users

---

src/elements/content-sharing/stories/ContentSharing.stories.js
src/features/unified-share-modal/EmailForm.js
src/features/unified-share-modal/UnifiedShareForm.js
src/features/unified-share-modal/__tests__/EmailForm.test.js
src/features/unified-share-modal/__tests__/UnifiedShareForm.test.js
src/features/unified-share-modal/__tests__/__snapshots__/EmailForm.test.js.snap
src/features/unified-share-modal/flowTypes.js

feat(content-sharing): Allow hiding message section of collab page

---

src/api/Feed.js
src/elements/content-sidebar/activity-feed/annotations/AnnotationActivityMenu.js
src/elements/content-sidebar/activity-feed/annotations/__tests__/AnnotationActivity.test.js
src/elements/content-sidebar/activity-feed/annotations/__tests__/AnnotationActivityMenu.test.js

fix(annotation): disable modify annotations

---

scripts/styleguide.setup.js

test(cypress): Change to new primary token

---

src/api/uploads/MultiputUpload.js

fixes https://github.com/box/box-ui-elements/issues/2322
According to https://w3c.github.io/FileAPI/#file-section and https://stackoverflow.com/a/14284215/12031375, the underlying File object and its props do not change when the underlying file changes on disk. 
> User agents should endeavor to have a File object’s snapshot state set to the state of the underlying storage on disk at the time the reference is taken. If the file is modified on disk following the time a reference has been taken, the File's snapshot state will differ from the state of the underlying storage.

fix(upload): Remove client side file change checks

---

i18n/en-US.properties
src/features/unified-share-modal/messages.js

Updating copy in order to cover both unclassified and classified content scenarios.

feat(usm): Update justification notice copy

---

i18n/en-US.properties
src/features/unified-share-modal/messages.js

Similar to #2452. Updating copy in order to cover both unclassified and classified content scenarios.

feat(usm): Updating collab restriction notice copy

---

src/elements/content-sidebar/activity-feed/common/activity-timestamp/ActivityTimestamp.js
src/elements/content-sidebar/activity-feed/common/activity-timestamp/__tests__/ActivityTimestamp.test.js
src/elements/content-sidebar/activity-feed/common/activity-timestamp/__tests__/__snapshots__/ActivityTimestamp.test.js.snap

Modify the `ActivityTimestamp` component to conditionally show the time only when the timestamp occurs in the last 12 months

feat(activityfeed): Only show time if within the last 12 months

---

src/constants.js
src/elements/content-preview/ContentPreview.js
src/elements/content-preview/ContentPreview.scss
src/elements/content-preview/PreviewError.js
src/elements/content-preview/PreviewError.scss
src/elements/content-preview/PreviewMask.scss
src/elements/content-preview/PreviewMask.tsx
src/elements/content-preview/__tests__/ContentPreview.test.js
src/elements/content-preview/__tests__/PreviewError.test.js
src/elements/content-preview/__tests__/PreviewMask.test.tsx
src/elements/content-preview/__tests__/__snapshots__/PreviewError.test.js.snap

This PR is a follow-up to https://github.com/box/box-ui-elements/pull/2498. It's ready for review, but will need to wait to be merged until Preview SDK v2.69.0 is fully deployed and promoted.

feat(preview): Add new loading experience to preview element

---

src/elements/content-sidebar/activity-feed/annotations/AnnotationActivity.js
src/elements/content-sidebar/activity-feed/annotations/AnnotationActivity.scss
src/elements/content-sidebar/activity-feed/annotations/AnnotationActivityLink.scss
src/elements/content-sidebar/activity-feed/annotations/AnnotationActivityLink.tsx
src/elements/content-sidebar/activity-feed/annotations/__tests__/AnnotationActivityLink.test.js
src/elements/content-sidebar/activity-feed/annotations/__tests__/__snapshots__/AnnotationActivityLink.test.js.snap

fix(annotations): Truncate annotation link when too long

---

src/elements/content-sidebar/activity-feed/annotations/AnnotationActivity.scss

fix(annotations): Move time and link separator

---

src/utils/__tests__/uploads.test.js
src/utils/uploads.js

Turning multiput uploads back on for mobile chrome ios use case.

fix(uploads): update multiput upload support for mobile chrome ios

---

src/elements/content-sidebar/activity-feed/version/CollapsedVersion.js
src/elements/content-sidebar/activity-feed/version/Version.js
src/elements/content-sidebar/activity-feed/version/__tests__/CollapsedVersion.test.js
src/elements/content-sidebar/activity-feed/version/__tests__/Version.test.js

feat(activityfeed): Update versions info icon

---

i18n/en-US.properties
src/features/content-explorer/content-explorer-modal-container/ContentExplorerModalContainer.js
src/features/content-explorer/content-explorer/ContentExplorer.js
src/features/content-explorer/content-explorer/ContentExplorer.scss
src/features/content-explorer/content-explorer/ContentExplorerSelectAll.js
src/features/content-explorer/content-explorer/__tests__/ContentExplorer.test.js
src/features/content-explorer/content-explorer/__tests__/ContentExplorerSelectAll.test.js
src/features/content-explorer/messages.js

fixes #2536
longer description here if necessary.

feat(selectall): add select all to content explorer

---

src/constants.js

[Changelog](https://github.com/box/box-content-preview/compare/v2.69.0...v2.72.0)

feat(preview): Update default version of Preview SDK

---

src/elements/content-sidebar/__tests__/__snapshots__/SidebarFileProperties.test.js.snap
src/features/item-details/ItemProperties.scss
src/features/item-details/RetentionPolicy.js
src/features/item-details/__tests__/__snapshots__/RetentionPolicy.test.js.snap

fix(item-details): add space before extend

---

i18n/en-US.properties
src/elements/common/feature-checking/hooks.js
src/elements/common/feature-checking/index.js
src/elements/common/interactionTargets.js
src/elements/content-sidebar/SidebarNav.js
src/elements/content-sidebar/SidebarNav.scss
src/elements/content-sidebar/SidebarNavButton.scss
src/elements/content-sidebar/SidebarNavSign.scss
src/elements/content-sidebar/SidebarNavSign.tsx
src/elements/content-sidebar/__tests__/SidebarNav.test.js
src/elements/content-sidebar/__tests__/SidebarNavSign.test.tsx
src/elements/content-sidebar/_mixins.scss
src/elements/content-sidebar/additional-tabs/AdditionalTab.scss
src/elements/content-sidebar/messages.js

feat(sign): Add button for Box Sign to ContentSidebar

---

i18n/en-US.properties
src/elements/content-sidebar/SidebarNav.js
src/elements/content-sidebar/SidebarNavSign.tsx
src/elements/content-sidebar/__tests__/SidebarNavSign.test.tsx
src/elements/content-sidebar/messages.js

feat(sign): Add ftux tooltip for Box Sign entry point

---

src/elements/content-sidebar/ContentSidebar.scss

Change background of right sidebar because contrast issue.

fix(contentsidebar): change background to white

---

src/components/count-badge/CountBadge.scss
src/styles/constants/_colors.scss
src/styles/variables.js
src/styles/variables.json
src/styles/variables.ts

since this color will only be used in this single instance, I didn't add a variable for it in the colors-palete 
now contrast is 4.5 which pass a11y AA standards

fix(countbadge): tweak contrast color

---

src/features/metadata-instance-editor/Footer.scss

Change color to box-blue according to design decision taken at the Jira Ticket
Before:
After:

fix(metadata): Tweak contrast color

---

src/features/shared-link-settings-modal/PasswordSection.js
src/features/shared-link-settings-modal/SharedLinkSettingsModal.js
src/features/shared-link-settings-modal/SharedLinkSettingsModal.scss
src/features/shared-link-settings-modal/__tests__/PasswordSection.test.js

* Add optional placeholder with icon if password information is passed into the component.
*  Add tests to cover new optional placeholder

feat(sharedlinksettingsmodal): Add optional password info placeholder

---

src/illustration/Files.stories.tsx
src/illustration/Files.tsx

feat(icon): add files icon

---

i18n/en-US.properties
src/elements/common/messages.js
src/elements/content-preview/PreviewMask.tsx
src/elements/content-preview/__tests__/__snapshots__/PreviewError.test.js.snap

Same as https://github.com/box/box-ui-elements/pull/2661, but excluding the changes to scripts

fix: show access-policy specific preview error screen

---

src/components/radio/RadioButton.scss

Improced color contrast on  the 2 Step Verification

fix(accountsettings): color contrast on radio btn

---

src/components/dropdown-menu/DropdownMenu.js
src/components/menu/Menu.tsx

allow the developer to pass properties instead of force the app to always use the same

fix: set listbox instead of standard menu properties

---

i18n/en-US.properties
src/elements/content-sidebar/SidebarNav.js
src/elements/content-sidebar/SidebarNavSign.tsx
src/elements/content-sidebar/__tests__/SidebarNavSign.test.tsx
src/elements/content-sidebar/messages.js

Disable Box Sign in Content Sidebar Nav based on props.

feat(contentsidebar): Disable SidebarNavSign w/ error message on hover

---

src/components/notification/Notification.js
src/components/notification/Notification.scss

Reverts box/box-ui-elements#2718
https://jira.inside-box.net/browse/A11Y-499

fix(alerts): Revert of notifications fix

---

src/components/modal/Modal.scss
src/components/modal/ModalDialog.js

fix(modal): new header weight and border radius

---

src/icon/line/GenericCopy16.js.flow
src/icon/line/GenericCopy16.stories.tsx
src/icon/line/GenericCopy16.tsx

* Adds Generic Copy Icon SVG from design assets import script

feat(copy icon): add generic copy icon

---

src/elements/common/modal.scss
src/elements/content-uploader/Footer.scss
src/features/content-explorer/content-explorer/ContentExplorer.scss

Similar to the ModalActions component, the modals within the Elements folder should set the button size to large for the footer row (action buttons).

fix: element modal action buttons get large size

---

CONTRIBUTING.md

BREAKING CHANGE: rename $bdl-border-radius-large-size to $bdl-border-radius-size-large
See https://github.com/box/box-ui-elements/pull/2749 to learn more

feat(theme): Add breaking change commit for dejablue redesign

---

CONTRIBUTING.md

BREAKING CHANGE: rename $bdl-border-radius-large-size to $bdl-border-radius-size-large
See https://github.com/box/box-ui-elements/pull/2749 to learn more

feat(theme): BREAKING CHANGE add noop for djb theme breaking changes

---

i18n/en-US.properties
src/components/flyout/Flyout.js
src/features/presence/Presence.js
src/features/presence/PresenceAvatar.js
src/features/presence/PresenceAvatarList.tsx
src/features/presence/PresenceCollaboratorsList.js
src/features/presence/__tests__/__snapshots__/Presence.test.js.snap
src/features/presence/messages.js

In the `Flyout` component, added the `role="button"` to the button child element. Added `aria-hidden="true"` to the `PresenceAvatar` used in the `PresenceAvatarList` so that it is ignored by screen readers.
TODO:

fix(presence): Make more accessible by adding appropriate roles

---

src/components/date-picker/AccessiblePikaday.ts
src/components/date-picker/DatePicker.scss
src/components/date-picker/DatePicker.tsx
src/elements/content-sidebar/activity-feed/task-form/TaskForm.js

Use BUIE scss variable for border-radius

fix(datepicker): Use scss variable for border-radius

---

src/features/unified-share-modal/UnifiedShareForm.js

fix: refactor collaborator access message

---

src/features/message-center/components/message-center-modal/MessageCenterModal.js

https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md
-> doc mentions "Row index to ensure visible (by forcefully scrolling if necessary)"

fix(message-center): doesnt load list until scroll

---

scripts/findReactIntlViolators.js
src/features/presence/PresenceCollaborator.js
src/features/presence/PresenceCollaborator.scss
src/features/presence/PresenceCollaboratorsList.js
src/features/presence/PresenceCollaboratorsList.scss
src/features/presence/__tests__/PresenceCollaborator.test.js
src/features/presence/__tests__/PresenceCollaboratorsList.test.js

Fix for simplifying the presence collaborators list into a reusable sub-component to be used in content analytics.

fix(presence-collaborators-list): simplify presence collaborators list

---

src/features/collapsible-sidebar/CollapsibleSidebar.js
src/features/collapsible-sidebar/CollapsibleSidebar.scss
src/features/collapsible-sidebar/__tests__/CollapsibleSidebar.test.js
src/features/collapsible-sidebar/__tests__/__snapshots__/CollapsibleSidebar.test.js.snap

Manual test on dev vm:
width 475px:
width 474px:
unit tests are green:

feat(collapsible-sidebar): make CollapsibleSidebar hide-able

---

CONTRIBUTING.md

BREAKING CHANGE: Add noop for axios upgrade https://github.com/box/box-ui-elements/pull/2839

fix(axios): BREAKING CHANGE Add noop for axios upgrade

---

src/features/quick-search/QuickSearch.js
src/features/quick-search/__tests__/QuickSearch.test.js

feat(quick-search): Add title prop to QuickSearch for SelectorDropdown

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
CONTRIBUTING.md

updated issue templates to direct box employees to contact maintaining team instead of creating an issue

chore(docs): updated issue template

---

src/features/header-flyout/HeaderFlyout.js
src/features/header-flyout/styles/HeaderFlyout.scss

* fixed an issue where some responsive behavior would come through even if it was disabled in props

fix(header-flyout): default resp behavior should be under resp class

---

src/features/presence/PresenceCollaborator.js
src/features/presence/__tests__/PresenceCollaborator.test.js

Add default browser tooltip on activity list item

feat(presence-collaborator): add default browser tooltip on list item

---

src/icon/fill/ArrowSort16.js.flow
src/icon/fill/ArrowSort16.stories.tsx
src/icon/fill/ArrowSort16.tsx

ran build:assets script to create icon from the design-assets repo

feat(assets): create ArrowSort16 icon

---

i18n/en-US.properties
src/elements/content-sidebar/versions/StaticVersionSidebar.js
src/elements/content-sidebar/versions/VersionsSidebar.js
src/elements/content-sidebar/versions/VersionsSidebar.scss
src/elements/content-sidebar/versions/VersionsSidebarContainer.js
src/elements/content-sidebar/versions/__tests__/VersionsSidebar.test.js
src/elements/content-sidebar/versions/__tests__/VersionsSidebarContainer.test.js
src/elements/content-sidebar/versions/__tests__/__snapshots__/VersionsSidebarContainer.test.js.snap
src/elements/content-sidebar/versions/messages.js

present the winning treatment preview sidebar for when upgrading is applicable

feat(preview): update freemium preview sidebar for upsell

---

src/features/shared-link-settings-modal/SharedLinkSettingsModal.js

* Update shared links support link

fix(sharedlinks): Update sharedLink support link

---

src/components/contact-datalist-item/ContactDatalistItem.stories.tsx

chore(storybook): add story for ContactDatalistItem

---

src/components/draggable-list/DraggableList.stories.tsx

chore(storybook): modify-draggable-list-story

---

src/features/content-insights/ContentInsightsSummary.tsx
src/features/content-insights/__tests__/ContentInsightsSummary.test.tsx

In relation to https://git.dev.box.net/Box/EndUserApp/pull/8776

feat(content-insights): Add error state to ContentInsightsSummary

---

src/elements/content-explorer/DeleteConfirmationDialog.js
src/elements/content-explorer/DeleteConfirmationDialog.scss
src/elements/content-explorer/stories/DeleteConfirmationDialog.stories.js
src/elements/content-explorer/stories/DeleteConfirmationDialog.stories.md

fix(content-explorer): Added overflow style to DeleteConfirmationDialog

---

src/elements/content-sidebar/SidebarContentInsights.scss
src/elements/content-sidebar/SidebarContentInsights.tsx
src/elements/content-sidebar/__tests__/SidebarContentInsights.test.tsx

feat(content-sidebar): Add error support for SidebarContentInsights

---

src/common/types/annotations.js
src/elements/content-sidebar/activity-feed/annotation-thread/AnnotationThread.js
src/elements/content-sidebar/activity-feed/annotation-thread/AnnotationThread.scss
src/elements/content-sidebar/activity-feed/annotation-thread/AnnotationThreadContent.js
src/elements/content-sidebar/activity-feed/annotation-thread/AnnotationThreadCreate.js
src/elements/content-sidebar/activity-feed/annotation-thread/AnnotationThreadCreate.scss
src/elements/content-sidebar/activity-feed/annotation-thread/__tests__/AnnotationThread.test.js
src/elements/content-sidebar/activity-feed/annotation-thread/__tests__/AnnotationThreadContent.test.js
src/elements/content-sidebar/activity-feed/annotation-thread/__tests__/AnnotationThreadCreate.test.js

New component AnnotationThreadCreate.js 
- render CommentForm component and handling new Annotation create
Changes in AnnotationThread.js
- render AnnotationThreadCreate if there is no annotationId passed in props

feat(annotattion-thread): create new annotation

---

src/components/table/__tests__/makeSelectable.test.js
src/components/table/makeSelectable.js

- Refactor hotkeys to split into shared, list view, and grid view
- Add functionality for shift keyboard navigation on grid view

feat(gridview): Make hot key config for grid view

---

src/icon/line/AlertBubble16.js.flow
src/icon/line/AlertBubble16.stories.tsx
src/icon/line/AlertBubble16.tsx
src/icon/line/AvatarXBadge16.js.flow
src/icon/line/AvatarXBadge16.stories.tsx
src/icon/line/AvatarXBadge16.tsx

**AlertBubble16**
**AvatarXBadge16**

feat(assets): update Automation Templates assets

---

src/components/table/makeSelectable.js

Pick correct hotkey config when gridColumnCount is 0

fix(hotkey): choose correct hotkey config

---

i18n/en-US.properties
src/elements/content-sidebar/activity-feed/comment/Comment.js
src/elements/content-sidebar/activity-feed/comment/__tests__/Comment.test.js
src/elements/content-sidebar/activity-feed/comment/__tests__/__snapshots__/Comment.test.js.snap
src/elements/content-sidebar/activity-feed/common/activity-message/ActivityMessage.js
src/elements/content-sidebar/activity-feed/common/activity-message/ActivityMessage.scss
src/elements/content-sidebar/activity-feed/common/activity-message/__tests__/ActivityMessage.test.js
src/elements/content-sidebar/activity-feed/common/activity-message/messages.js
src/elements/content-sidebar/activity-feed/task-new/__tests__/__snapshots__/Task.test.js.snap

feat(annotation-thread): Add "(edited)" label to edited comments

---

src/elements/common/annotator-context/__tests__/useAnnotatorEvents.test.tsx
src/elements/common/annotator-context/__tests__/withAnnotations.test.tsx
src/elements/common/annotator-context/__tests__/withAnnotatorContext.test.tsx
src/elements/common/annotator-context/types.js.flow
src/elements/common/annotator-context/types.ts
src/elements/common/annotator-context/useAnnotatorEvents.js.flow
src/elements/common/annotator-context/useAnnotatorEvents.ts
src/elements/common/annotator-context/withAnnotations.js.flow
src/elements/common/annotator-context/withAnnotations.tsx
src/elements/common/annotator-context/withAnnotatorContext.js.flow
src/elements/common/annotator-context/withAnnotatorContext.tsx
src/elements/content-sidebar/ActivitySidebar.js
src/elements/content-sidebar/__tests__/ActivitySidebar.test.js
src/elements/content-sidebar/__tests__/withSidebarAnnotations.test.js
src/elements/content-sidebar/withSidebarAnnotations.js

Added logic supporting Annotation replies related events communication.

feat(content-sidebar): added annotation replies events communication

---

src/components/checkbox/Checkbox.tsx
src/components/checkbox/__tests__/Checkbox.test.tsx

Reverts box/box-ui-elements#3122

feat(checkbox): revert allow stopPropagation on onClick events

---

src/elements/content-sidebar/ActivitySidebar.js
src/elements/content-sidebar/__tests__/__snapshots__/ActivitySidebar.test.js.snap
src/elements/content-sidebar/activity-feed/activity-feed/ActiveState.js
src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.js
src/elements/content-sidebar/activity-feed/annotations/AnnotationActivity.js
src/elements/content-sidebar/activity-feed/annotations/AnnotationActivity.scss
src/elements/content-sidebar/activity-feed/annotations/AnnotationActivityLink.scss
src/elements/content-sidebar/activity-feed/annotations/__tests__/AnnotationActivity.test.js

show / hide AnnotationActivityLink based on hasVerions ActivitySidebar property

feat(annotations): hide AnnotationActivityLink based on hasVersions prop

---

src/elements/content-sidebar/activity-feed/annotations/AnnotationActivityMenu.js
src/elements/content-sidebar/activity-feed/annotations/AnnotationActivityMenu.scss
src/elements/content-sidebar/activity-feed/comment/Comment.js
src/elements/content-sidebar/activity-feed/comment/Comment.scss
src/elements/content-sidebar/activity-feed/common/activity-status/ActivityStatus.scss

Fix visual issues:
- adjust margin for `resolved` pill
- change fill for `X` icon to be consistent with other icons

feat(threaded-replies): fix styling for resolve

---

src/features/content-explorer/content-explorer-modal-container/ContentExplorerModalContainer.js
src/features/content-explorer/content-explorer-modal/ContentExplorerModal.js
src/features/content-explorer/content-explorer/ContentExplorer.js
src/features/content-explorer/item-list/ItemList.js

Adding rowHeight prop to ContentExplorerModal component so we could customize the row height in admin-console ui.

feat: add rowHeight prop to ContentExplorerModal

---

src/api/Feed.js

`total_replies_count` property on parent was not updated properly after deleting its reply

fix(replies): fix total_replies_count value update after delete reply

---

src/elements/content-sidebar/activity-feed/activity-feed/ActivityThread.js
src/elements/content-sidebar/activity-feed/activity-feed/ActivityThread.scss
src/elements/content-sidebar/activity-feed/annotation-thread/AnnotationThread.js
src/elements/content-sidebar/activity-feed/annotation-thread/AnnotationThread.scss
src/elements/content-sidebar/activity-feed/annotation-thread/AnnotationThreadContent.js
src/elements/content-sidebar/activity-feed/annotation-thread/AnnotationThreadContent.scss
src/elements/content-sidebar/activity-feed/annotation-thread/useAnnotationThread.js

- Added reply form that is separated from the `ActivityThread`
- Improved UI to meet the design requirements
- Added `getUserProfileUrl` prop (and support for it) to `AnnotationThread`  in order to display linked user names

feat(annotation-thread): added reply form, UI and other minor fixes

---

src/elements/content-sidebar/activity-feed/activity-feed/ActivityThread.scss
src/elements/content-sidebar/activity-feed/activity-feed/ActivityThreadReplies.js
src/elements/content-sidebar/activity-feed/activity-feed/ActivityThreadReplyForm.js

- Added white background to the comment form
- Addressed code review findings from https://github.com/box/box-ui-elements/pull/3162

fix(content-sidebar): select and hover state for threaded feed items

---

.github/pull_request_template.md

chore(template): Updated pull request template

---

src/elements/content-picker/Footer.js
src/elements/content-picker/__tests__/Footer.test.js

fix(content-picker): add accessible names to Footer

---

src/features/content-explorer/item-list/ItemList.js
src/features/content-explorer/item-list/__tests__/ItemList.test.js

fix(itemlist): Remove header section when list is empty

---

src/components/tooltip/Tooltip.tsx
src/features/unified-share-modal/UnifiedShareForm.js
src/features/unified-share-modal/__tests__/__snapshots__/UnifiedShareForm.test.js.snap

fix(usm): tooltip should be dialog

---

src/elements/common/sub-header/Sort.js

PR to match examples here: https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-editor/
Result:

fix(sub-header): sort menu item accessibility

---

README.md

docs(packages): describe supported packages

---

package.json
src/components/grid-view/__tests__/__snapshots__/GridView.test.js.snap
src/elements/content-explorer/ItemList.js
src/features/virtualized-table/__tests__/__snapshots__/BaseVirtualizedTable.test.js.snap
src/features/virtualized-table/__tests__/__snapshots__/DraggableVirtualizedTable.test.js.snap
src/features/virtualized-table/__tests__/__snapshots__/VirtualizedTable.test.js.snap
yarn.lock

Replaced the `columnHeader` role with a `gridcell` role for empty column headers
The two empty column headers are:
1. above the icon column
2. above the 3 dots and share column

fix(content-explorer): fix itemlist column header role

---

src/elements/common/item/iconCellRenderer.js

chore: add file annotation back to iconCellRenderer

---

src/elements/content-explorer/ContentExplorer.js

fix(content-explorer): enable create folder with trailing space in name

---

i18n/en-US.properties
src/features/content-explorer/content-explorer-modal-container/ContentExplorerModalContainer.js
src/features/content-explorer/content-explorer-modal/ContentExplorerModal.js
src/features/content-explorer/content-explorer/ContentExplorer.js
src/features/content-explorer/content-explorer/ContentExplorer.scss
src/features/content-explorer/content-explorer/ContentExplorerFolderTreeBreadcrumbs.js
src/features/content-explorer/content-explorer/ContentExplorerHeaderActions.js
src/features/content-explorer/content-explorer/__tests__/ContentExplorerFolderTreeBreadcrumbs.test.js
src/features/content-explorer/content-explorer/__tests__/ContentExplorerHeaderActions.test.js
src/features/content-explorer/content-explorer/__tests__/__snapshots__/ContentExplorer.test.js.snap
src/features/content-explorer/content-explorer/constants.js
src/features/content-explorer/messages.js

Child of: https://github.com/box/box-ui-elements/pull/3237

feat(content-explorer): adding folder tree

---

src/elements/common/header/Header.js
src/elements/common/header/Logo.js
src/elements/common/header/__tests__/Header.test.js

Matches the search inputs `aria-label` and `placeholder` messages

fix: Fix aria-label for BE header search

---

src/components/badgeable/Badgeable.scss
src/components/pill-selector-dropdown/_mixins.scss
src/features/presence/PresenceAvatarList.scss
src/styles/common/_buttons.scss

fix(scss): Replace all division for dart-sass

---

src/features/content-explorer/content-explorer/ContentExplorer.js
src/features/content-explorer/content-explorer/__tests__/__snapshots__/ContentExplorer.test.js.snap

fix(content-explorer): Include subfolders subheader fix

---

src/components/tooltip/Tooltip.tsx
src/features/unified-share-modal/UnifiedShareForm.js
src/features/unified-share-modal/__tests__/__snapshots__/UnifiedShareForm.test.js.snap

This reverts commit f52ad0e513f7253e3ba4b6276e250f7126046cd1.

fix(tooltip): Revert "fix(usm): tooltip should be dialog (#3226)"

---

src/features/content-explorer/content-explorer-modal-container/ContentExplorerModalContainer.js
src/features/content-explorer/content-explorer-modal/ContentExplorerModal.js
src/features/content-explorer/content-explorer/ContentExplorer.js
src/features/content-explorer/content-explorer/ContentExplorer.scss
src/features/content-explorer/content-explorer/ContentExplorerActionButtons.js
src/features/content-explorer/content-explorer/__tests__/ContentExplorerActionButtons.test.js
src/features/content-explorer/content-explorer/__tests__/__snapshots__/ContentExplorer.test.js.snap

Modal when nothing is selected:
When item is selected with toggle:
When Inside or in folder above the selected item:

feat(content-explorer): clickable status message for include subfolders

---

src/components/media-query/__tests__/withMediaQuery.test.js
src/components/media-query/stories/MediaQuery.stories.js
src/components/media-query/stories/MediaQuery.stories.md
src/components/media-query/types.js
src/components/media-query/useMediaQuery.js

logic to determine if user is on a touch device

feat(mediaquery): add isTouchScreen logic

---

src/features/content-explorer/content-explorer/ContentExplorer.js

fix: add props to omit to avoid console warnings

---

i18n/en-US.properties
src/elements/content-sidebar/activity-feed/comment-form/CommentForm.js
src/elements/content-sidebar/activity-feed/comment/CreateReply.js
src/elements/content-sidebar/activity-feed/comment/CreateReply.scss
src/elements/content-sidebar/activity-feed/comment/__tests__/CreateReply.test.js
src/elements/content-sidebar/activity-feed/comment/messages.js

This PR includes the CreateReply component which will be used in the Replies component in another PR. This component is a toggle which switches from a button to a Comment form based on the props.

feat(threaded-replies): Create Reply button component

---

i18n/en-US.properties
src/elements/content-sidebar/activity-feed/comment/RepliesToggle.js
src/elements/content-sidebar/activity-feed/comment/RepliesToggle.scss
src/elements/content-sidebar/activity-feed/comment/__tests__/RepliesToggle.test.js
src/elements/content-sidebar/activity-feed/comment/messages.js

Splitting up the Replies PR: https://github.com/box/box-ui-elements/pull/3288  for easier review

feat(threaded-replies): Create RepliesToggle component

---

src/components/select-button/SelectButton.js
src/components/select-field/BaseSelectField.js

fix(select-field): add tether class for select dropdowns

---

src/elements/content-open-with/ContentOpenWith.scss

refactor: Use bdl-gray-65 for ContentOpenWith

---

examples/colors.md
scripts/styleguide.config.js
src/styles/_deprecated.scss
src/styles/colors.md
src/styles/constants/_colors.scss
src/styles/variables.js
src/styles/variables.json
src/styles/variables.ts

BREAKING CHANGE: bdl-gray-62 is replaced with bdl-gray-65

refactor: deprecate bdl-gray-62 color

---

i18n/en-US.properties
src/features/unified-share-modal/SharedLinkAccessDescription.js
src/features/unified-share-modal/SharedLinkAccessLabel.js
src/features/unified-share-modal/SharedLinkAccessMenu.js
src/features/unified-share-modal/SharedLinkSection.js
src/features/unified-share-modal/__tests__/SharedLinkAccessDescription.test.js
src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkAccessDescription.test.js.snap
src/features/unified-share-modal/__tests__/__snapshots__/SharedLinkSection.test.js.snap
src/features/unified-share-modal/messages.js

feat(sharing): Change message for shared links for Canvas files

---

src/constants.js

https://github.com/box/box-ui-elements/issues/3325

fix(preview): videos not loading on edge

---

.circleci/config.yml
.nvmrc
.yarnrc
DEVELOPING.md
package.json
yarn.lock

BREAKING CHANGE: Upgrade to node 18

chore(node): Upgrade to node 18

---

src/elements/content-picker/ContentPicker.js

similar to this PR: https://github.com/box/box-ui-elements/pull/3246 but for Content Picker

fix(content-picker): trim name input when creating folder

---

DEVELOPING.md
README.md
package.json
src/elements/README.md
test/openwith.html

BREAKING CHANGE: Internet Explorer 11 is no longer supported

feat: remove browser support for IE11

---

i18n/en-US.properties
src/features/content-answers/ContentAnswers.tsx
src/features/content-answers/ContentAnswersOpenButton.scss
src/features/content-answers/ContentAnswersOpenButton.tsx
src/features/content-answers/__tests__/ContentAnswersOpenButton.test.tsx
src/features/content-answers/messages.ts

**Initial Button**
**on hover**
**on focus**

feat(content-answers): create initial content-answers modal button component

---

src/elements/content-preview/ContentPreview.js
src/elements/content-preview/preview-header/PreviewHeader.js
src/elements/content-preview/preview-header/__tests__/PreviewHeader.test.js
src/features/content-answers/ContentAnswers.tsx
src/features/content-answers/ContentAnswersModal.tsx
src/features/content-answers/ContentAnswersModalFooter.tsx
src/features/content-answers/__tests__/ContentAnswers.test.tsx
src/features/content-answers/__tests__/ContentAnswersModal.test.tsx
src/features/content-answers/__tests__/ContentAnswersModalFooter.test.tsx

feat(content-answers): Avatar

---

src/api/Intelligence.js
src/api/__tests__/Intelligence.test.js
src/constants.js
src/features/content-answers/Answer.scss
src/features/content-answers/Answer.tsx
src/features/content-answers/ContentAnswersGridCard.scss
src/features/content-answers/ContentAnswersModal.scss
src/features/content-answers/ContentAnswersModal.tsx
src/features/content-answers/ContentAnswersModalContent.scss
src/features/content-answers/ContentAnswersModalContent.tsx
src/features/content-answers/ContentAnswersModalFooter.tsx
src/features/content-answers/LoadingElement.scss
src/features/content-answers/LoadingElement.tsx
src/features/content-answers/Question.scss
src/features/content-answers/Question.tsx
src/features/content-answers/__mocks__/mocks.ts
src/features/content-answers/__tests__/Answer.test.tsx
src/features/content-answers/__tests__/ContentAnswers.test.tsx
src/features/content-answers/__tests__/ContentAnswersGridCard.test.tsx
src/features/content-answers/__tests__/ContentAnswersModal.test.tsx
src/features/content-answers/__tests__/ContentAnswersModalContent.test.tsx
src/features/content-answers/__tests__/ContentAnswersModalFooter.test.tsx
src/features/content-answers/__tests__/Question.test.tsx

check the storybook to see changes
hooked up intelligence endpoint 
submitting a question, make a network request to retrieve the answer, this also clears the question from the textarea
question renders into window while waiting with a loading indicator 
when answer returns, it renders into the window below the question replacing the loading indicator 
hitting enter while there is text in the textarea submit the question too 
adjusted some styles to better match

feat(content-answers): Questions Answers Intelligence endpoint

---

src/features/content-explorer/content-explorer/ContentExplorer.js

refactor(content-explorer): Cleanup code

---

package.json
yarn.lock

chore(mocha): removed mocha

---

src/utils/__tests__/relativeTime.test.js

chore(relative-time): Account for leap year

---

src/elements/content-open-with/stories/ContentOpenWith.mdx
src/elements/content-open-with/stories/ContentOpenWith.stories.js
src/elements/content-picker/stories/ContentPicker.mdx

Added story and converted readme to MDX for storybook to render instead

chore(content-open-with): Added stories and mdx

---

.vscode/settings.json
i18n/en-US.properties
src/features/shared-link-settings-modal/ExpirationSection.js
src/features/shared-link-settings-modal/SharedLinkSettingsModal.js
src/features/shared-link-settings-modal/__tests__/ExpirationSection.test.js
src/features/shared-link-settings-modal/__tests__/SharedLinkSettingsModal.test.js

Changed `ExpirationSection.js` and `SharedLinkSettingsModal.js` to pass Intl timezone in dateFormat prop to `DatePicker` to format visible value in the input correctly according to users locale.

fix(shared-link-settings-modal): correct expiration date formatting

---

src/elements/content-sidebar/SidebarNav.js
src/elements/content-sidebar/__tests__/SidebarNav.test.js
src/icon/fill/DocGenIcon.js.flow
src/icon/fill/DocGenIcon.stories.tsx
src/icon/fill/DocGenIcon.tsx

bringingDocGen icon into BUIE for DocGen sidebar

feat(docgen): add docgen icon

---

package.json
yarn.lock

BREAKING CHANGE: upgrade hapi/address to resolve undefined buffer reference

fix: upgrade hapi address package dependency

---

src/elements/content-uploader/DroppableContent.js
src/elements/content-uploader/UploadInput.js
src/elements/content-uploader/__tests__/__snapshots__/UploadInput.test.js.snap
src/elements/content-uploader/stories/tests/ContentUploader-visual.stories.js

error single upload removed for being too unstabled

chore(content-uploader): Add visual regression tests

---

.storybook/typings.d.ts

chore(storybook): Added global types for storybook

---

src/components/table/__tests__/makeSelectable.test.js
src/components/table/makeSelectable.js

Update Quick Search Navigation logic to skip focus on additional elements.

fix(quick-search): Quick Search buttons and footer navigation

---

package.json
src/elements/content-sidebar/ContentSidebar.js
src/elements/content-sidebar/MetadataInstanceEditor.tsx
src/elements/content-sidebar/MetadataSidebarRedesign.tsx
src/elements/content-sidebar/__tests__/MetadataInstanceEditor.test.tsx
src/elements/content-sidebar/__tests__/MetadataSidebarRedesign.test.tsx
src/elements/content-sidebar/hooks/useSidebarMetadataFetcher.ts
src/elements/content-sidebar/stories/MetadataSidebarRedesign.stories.tsx
src/elements/content-sidebar/stories/tests/MetadataSidebarRedesign-visual.stories.tsx
src/test-utils/testing-library.tsx
yarn.lock

This PR adds showing list of already added Metadata Instances.
(original PR https://github.com/box/box-ui-elements/pull/3640 that was closed after closing `metadata-sidebar-redesign` branch)
* Bump `@box/metadata-editor` to latest version
* Wrap Sidebar content in `AutofillContextProvider`. This will be changed in future when we connect to real API
* Removed `UnsavedChangesModal` component, as it is already being shown by `MetadataInstanceForm` component. It was doubled and tests were failing, and overlay was darker.
* Added `TooltipProvider`. Some Metadata templates have additional description that is shown in Tooltips when users hover over metadata name.
* Added `MetadataInstanceList`. Now all added metadata instances are visible.
* Handled simple cases of `Cancel` behavior on …

feat(metadata-sidebar): Add metadata instance list

---

package.json
yarn.lock

Bumping blueprint-web version to 7.30.1

chore(blueprint-web): bump blueprint-web

---

src/elements/content-explorer/stories/tests/ContentExplorer-visual.stories.js
src/elements/content-sidebar/stories/tests/MetadataSidebarRedesign-visual.stories.tsx

Fix two failing storybook tests

fix(metadata-sidebar): Fix storybook tests

---

src/api/Metadata.js
src/api/__tests__/Metadata.test.js
src/api/__tests__/utils.test.js
src/api/utils.js
src/common/types/metadata.js
src/constants.js
src/utils/error.js

* Added new metadata template options fetcher

feat(taxonomy): added metadata options endpoint

---

package.json
yarn.lock

fixed autoscroll issue when non streaming answer is received. will automatically scroll to the bottom now

fix(content-answers): Bump content-answers

---

src/elements/content-sidebar/SidebarNav.js

Added `data-target-id` attribute with unique value to each `SidebarNavButton` in Sidebar.

feat(boxai-sidebar): Add target id attribute to Sidebar tabs buttons

---

src/elements/content-sidebar/additional-tabs/AdditionalTab.js
src/elements/content-sidebar/additional-tabs/__tests__/AdditionalTab.test.js
src/elements/content-sidebar/additional-tabs/__tests__/__snapshots__/AdditionalTab.test.js.snap
src/elements/content-sidebar/flowTypes.js

Adding new optional param `icon` to preview sidebar `AdditionalTab`

feat(preview-sidebar): Add optional icon param to sidebar

---

package.json
src/api/Intelligence.js
src/api/__tests__/Intelligence.test.js
src/elements/content-sidebar/MetadataSidebarRedesign.scss
src/elements/content-sidebar/MetadataSidebarRedesign.tsx
src/elements/content-sidebar/__tests__/MetadataSidebarRedesign.test.tsx
src/elements/content-sidebar/hooks/useSidebarMetadataFetcher.ts
src/elements/content-sidebar/stories/MetadataSidebarRedesign.stories.tsx
src/elements/content-sidebar/stories/__mocks__/MetadataSidebarRedesignedMocks.ts
src/elements/content-sidebar/stories/tests/MetadataSidebarRedesign-visual.stories.tsx
yarn.lock

QA reported we're showing wrong error notification when AI autofill action is run without internet connection. After accessing other tabs in sidebar we decided to show default error screen from `ErrorBoundry`.
I've also bumped version of `blueprint-web`, `blueprint-web-assets` and `metadata-editor` to get the new features in storybook.
As well as copied mocked responses from https://github.com/box/box-ui-elements/pull/3699

fix(metadata-editor): Fix error handling in metadata sidebar

---

src/elements/content-sidebar/additional-tabs/AdditionalTab.js
src/elements/content-sidebar/additional-tabs/__tests__/__snapshots__/AdditionalTab.test.js.snap

changing default icon for more apps icon button

feat(preview-sidebar): changing default icon for more apps icon

---

src/features/item-details/ItemProperties.scss

Some style changes to increase contrast according to accessibility requirements

fix(item-details): fixed contrast for accessibility

---

src/elements/content-sidebar/MetadataSidebarRedesign.scss

fix(metadata-editor): Fixed import syntax

---

src/elements/content-sidebar/hooks/useSidebarMetadataFetcher.ts

fix(metadata-editor): Disable AI suggestions taxonomy

---

src/elements/content-explorer/stories/tests/ContentExplorer-visual.stories.js

chore(chromatic): fix snapshots

---

src/elements/content-sidebar/BoxAISidebar.scss

Fixed width responsiveness for Box AI chat used in sidebar, this PR is a follow up one for https://github.com/box/box-ui-elements/pull/3786.
https://github.com/user-attachments/assets/c9ce12d9-ee32-4e4d-bd5a-70b8b9bba83f

feat(boxai-sidebar): Box AI responsive width

---

src/elements/content-sidebar/__tests__/useSidebarMetadataFetcher.test.tsx
src/elements/content-sidebar/hooks/useSidebarMetadataFetcher.ts
src/elements/content-sidebar/stories/__mocks__/MetadataSidebarRedesignedMocks.ts
src/elements/content-sidebar/stories/tests/MetadataSidebarRedesign-visual.stories.tsx

Fix bug when AI suggestions weren't populated for metadata template instance which is not created yet (right after choosing template from New Dropdown Menu)

fix(metadata-editor): Fix AI suggestion for newly created instance

---

src/elements/content-sidebar/AddTaskButton.js

fix(add-task-button): add flushSync to modal close

---

.circleci/config.yml
.storybook/preview.tsx
chromatic.config.json
scripts/check_generated_files.sh
scripts/commitlint.sh
src/elements/__mocks__/mockRequests.ts
src/elements/content-preview/stories/tests/ContentPreview-visual.stories.js
src/elements/content-sidebar/stories/tests/BoxAISidebar-visual.stories.tsx
src/elements/content-sidebar/stories/tests/MetadataSidebarRedesign-visual.stories.tsx

chore(circleci): caching again

---

.storybook/preview.tsx
src/components/time/ReadableTime.stories.js
src/elements/content-preview/stories/tests/ContentPreview-visual.stories.js
src/features/security-cloud-game/stories/SecurityCloudGame.stories.js

chore(chromatic): tuned configuration 

---

src/elements/content-sidebar/stories/tests/MetadataSidebarRedesign-visual.stories.tsx

chore(chromatic): fix MetadataSidebarRedesign custom template VRT

---

src/elements/content-explorer/Date.js.flow
src/elements/content-explorer/Date.tsx
src/elements/content-explorer/__tests__/Date.test.tsx

fix(content-explorer): Migrated Date

---

.storybook/preview-head.html

chore(chromatic): preview head preload fix

---

src/elements/content-preview/stories/ContentPreview.stories.js
src/elements/content-preview/stories/tests/ContentPreview-visual.stories.js
src/utils/createTheme.stories.js

chore(chromatic): disable flaky snapshots

---

src/elements/content-sidebar/BoxAISidebar.tsx

**Description**
Pass `isOpen` and `getSuggestedQuestions` to `BoxAISidebarContent` allowing suggested questions to load correctly for xlsx files. 
- `isOpen` indicates whether the AI Sidebar is open or closed. 
- `getSuggestedQuestions` It either returns a function to fetch suggested questions under certain conditions or null when no questions are available. 
Both props are utilized by `BoxAISidebarContent` when wrapped in `withApiWrapper`, to handle the logic for fetching and displaying suggested questions based on the file type and Sidebar state.
Suggested question for xlsx file:

fix(ai-sidebar): Pass additional props to BoxAISidebarContent

---

src/api/Feed.js
src/api/__tests__/Feed.test.js
src/api/fixtures.js
src/elements/content-sidebar/activity-feed/task-new/Task.js
src/elements/content-sidebar/activity-feed/task-new/__tests__/Task.test.js

fix(uaa-parity): Fix version promotion and deleted user task issues

---

src/elements/content-sidebar/BoxAISidebar.tsx
src/elements/content-sidebar/BoxAISidebarContent.tsx
src/elements/content-sidebar/context/BoxAISidebarContext.ts

fix(content-sidebar): Fixed circular dependency for box ai sidebar

---

src/elements/content-sidebar/SidebarContent.scss

On systems with scrollbars always visible a horizontal scrollbar is displayed in the content sidebar. We want to remove this behavior.

fix(content-sidebar): remove horizontal scrolling in content sidebar

---

src/elements/content-sidebar/BoxAISidebarContent.tsx
src/elements/content-sidebar/BoxAISidebarTitle.tsx
src/elements/content-sidebar/__tests__/BoxAISidebar.test.tsx
src/elements/content-sidebar/__tests__/BoxAISidebarTitle.test.tsx

Added back Box AI Title with conditional rendering. It will be visible right after Sidebar load when Agent Selector is disabled. When Agent Selector is enabled, title will become visible after the request for agents has ended and Agent Selector is not visible (there's either only 1 agent or request has failed or has been canceled).
In addition I've enabled Clear Conversation button in `IntelligenceModal`.
With Agent Selector disabled
With Agent Selector enabled when it's visible
With Agent Selector enabled when it's not visible (only 1 agent available)

fix(content-sidebar): Fix Box AI Sidebar Title render logic

---

src/constants.js
src/elements/content-sidebar/MetadataSidebarRedesign.tsx
src/elements/content-sidebar/SidebarPanels.js
src/elements/content-sidebar/__tests__/MetadataSidebarRedesign.test.tsx

feat(box-ai): Fetch structured text rep for metadata sidebar

---

i18n/en-US.properties
src/elements/common/messages.js
src/elements/content-sidebar/activity-feed/version/CollapsedVersion.js

fix(uaa-parity): Localization fix for collapsed version event

---

.flowconfig
src/components/select-field/props.js
src/features/unified-share-modal/flowTypes.js

had to update the flowconfig so that packages with a dist folder are located via flow

chore(flowtypes): Updated flowconfig to be more precise

---

src/elements/common/current-user/__tests__/withCurrentUser.test.tsx

BREAKING CHANGE noop to trigger a new major version in the stable release.

feat: BREAKING CHANGE noop for stable release

---

src/elements/content-uploader/Footer.tsx

BREAKING CHANGE: update peer dependencies for `@box/` packages
This PR is to trigger a breaking change in the next stable release.

feat: BREAKING CHANGE noop to trigger major version release

---

src/api/Feed.js
src/elements/content-sidebar/activity-feed/activity-feed/ActivityFeed.js
src/elements/content-sidebar/activity-feed/activity-feed/__tests__/ActivityFeed.test.js

UAA FF on with 500 error:
v2 Feed Items working properly:
UAA FF on with no errors:
UAA FF on with Empty state working properly:

fix(uaa-parity): Display error message for UAA errors

---

package.json
yarn.lock

resolves half of https://github.com/box/box-ui-elements/security/dependabot/240 by bumping semantic-release to latest
had to rename the release.config.js to .releaserc.js https://github.com/semantic-release/semantic-release/releases/tag/v23.0.0
v17-v22 were node minimum support moving up
v24 https://github.com/semantic-release/semantic-release/releases/tag/v24.0.0  
need conventional package to latest if they are installed

chore(semantic-release): Bump to v24

---

src/elements/common/content-answers/ContentAnswersOpenButton.scss

fixes https://github.com/box/box-ui-elements/issues/4073

fix(content-answers): fix CSS variable

---

package.json
yarn.lock

resolves https://github.com/box/box-ui-elements/security/dependabot/240

fix(flow-typed): Bumped to 4.1.0
